{
  "hash": "ed15af14aaa9e900f30db04624c2052e",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Cues, Partisanship, and Willingness-to-Pay for Energy\"\nbibliography: references.bib\ncsl: american-political-science-association.csl\nfig-cap-location: top\nfontfamily: ebgaramond\nlink-bibliography: false\nformat:\n  html:\n    author:\n      - name: Matthew C. Nowlin\n        email: matthew.nowlin@uta.edu\n        corresponding: true\n        affiliations:\n          - name: University of Texas at Arlington\n            department: Department of Political Science\n    template-partials:\n      - title-metadata.html\n  pdf:\n    author:\n      - name: \"Matthew C. Nowlin^[Associate Professor, Department of Political Science, University of Texas at Arlington. Email: matthew.nowlin@uta.edu]\"\n    include-in-header:\n      text: |\n        \\usepackage{setspace}\n        \\usepackage{dcolumn}\n        \\usepackage{float}\n        \\usepackage{amsmath}\n        \\usepackage{ulem}\n        \\addtokomafont{disposition}{\\rmfamily}\n        \\normalem\n  docx:\n    author:\n      - name: \"Matthew C. Nowlin^[Associate Professor, Department of Political Science, University of Texas at Arlington. Email: matthew.nowlin@uta.edu]\"\n    reference-doc: custom-reference-doc.docx\n    filters:\n      - path: filters/left-align-tables.lua\n        at: post-render\n---\n\n\n\n<!-- intended outlet is Energy Policy as a research note. 4500 word limit -->\n\n# Introduction\n\nShifting from fossil fuel sources of energy to renewables is needed to mitigate climate change. Yet, such a shift requires the commitment and support of the public. In general, the US public seems to support using more renewable sources, yet there are partisan differences in the degree of that support with Republicans tending to be more supportive of fossil fuels and Democrats tending to be more supportive of renewables [@bergquistEnergyPolicyPublic2020; @hamiltonChangeWindUS2018; @hawesClimateSciencePolitics2022]. Additionally, in the last several years, Republicans have become more supportive of fossil fuels and less supportive of renewables [@kennedyAmericansShiftingViews2026]. Finally, the rhetoric and actions of President Trump since beginning his second term have focused on expanding fossil fuels and reducing renewables. Such actions by such a divisive political actor can serve as a partisan cue for the public. \n\nCues have been shown to inform public opinion on climate change and energy preferences. For example, partisan and elite cues played a significant role in shaping opinion on climate change [@merkleyPartyCuesNews2021; @teslerEliteDominationPublic2018], and a climate change cue, or frame, can influence energy preferences [@feldmanClimateChangePolarizing2018]. Given the emphases of the second Trump administration regarding fossil fuels and renewables, it is possible that polarization among the public on energy sources may increase in response. In this paper, I explore how exposure to a Trump or climate cue, compared to no cue, influences how the US public prioritizes fossil fuels versus renewables as well as their willingness-to-pay (WTP) for those energy sources.\n\nAs noted, the public is responsive to cues when forming their views on energy issues; however, less is known about how cues may impact the WTP of the public. In brief, the literature on WTP for energy finds that the public is responsive to price volatility for both fossil fuels and renewables [@cardellaPriceVolatilityResidential2017], but in general are willing to pay more for renewable sources [@borchersDoesWillingnessPay2007; @nkansahWillingnessPayWind2019] and is WTP for research and development by the federal government aimed at reducing the use of fossil fuels [@liPublicSupportReducing2009]. However, concern about the environmental impacts of energy [@knappWillConsumersReally2020] and political beliefs [@aldyWillingnessPayPolitical2012] can shape the WTP for energy.\n\nIn this study, I expand on current research by testing the impacts of a Trump cue versus a climate change cue on the prioritization of and WTP for fossil fuels and renewable sources of energy. Overall, I find that political beliefs shape energy source prioritization as conservative Republicans tend to prioritize and have a higher WTP for fossil fuels and liberal Democrats prioritize and have a higher WTP for renewables. The cues have some interaction effects as conservative Republicans in the Trump cue prioritize fossil fuels somewhat more, and liberal Democrats in the climate cue prioritize renewables more, with interactions significant at *p*<0.10. Finally, there were no cue or interaction effects on the WTP for either energy source. \n\n# Cues, Public Opinion, and the Public's Willingness-to-Pay for Energy\n\nPartisan and elite cues shape public opinion on climate and energy issues, as the public tends to adopt the positions associated with their political party [@merkleyPartyCuesNews2021; @teslerEliteDominationPublic2018; @ehretPartisanBarriersBipartisanship2018]. Cues provide an information heuristic, or shortcut, that allows the public to form opinions regarding a host of issues. Additionally, cues provide guides for motivated reasoning, as individuals apply reasoning in service to matching their views with those of their preferred party. Apart from partisan cues, connecting energy policies to the polarized issue of climate change can also shape and polarize public opinion. For example, @feldmanClimateChangePolarizing2018 found that framing a low-carbon energy policy as a climate change solution, rather than as an air pollution or energy security measure, reduced support for that policy among Republicans. \n\nIn addition to beliefs and attitudes, partisanship is also likely to influence an individual's WTP. For example, conservatives were less likely to purchase an energy-efficient light bulb when it was labeled with an environmental message, as opposed to no label [@grometPoliticalIdeologyAffects2013]. A larger number of studies have examined stated WTP and political beliefs. @kotchenWillingnesstoPayPolicyInstrumentChoice2013 found that Republicans reported lower WTP for a national climate policy than Democrats and independents, but that this partisan gap was largely explained by differences in beliefs about whether climate change is occurring. Using a similar national WTP measure, @kotchenPublicWillingnessPay2017 estimated an average household WTP of \\$177 per year for a carbon tax, with respondents favoring that the revenue be spent on clean energy investment over other uses. More recently, @benegalCostSensitivityPartisan2024 found that partisan cue-taking, where respondents supported policies proposed by their party, outweighed sensitivity to the policy's stated cost. @scheuchVotersSupportAre2026 also found partisanship to be a significant predictor of WTP for local climate policy, alongside age and income. Overall, political beliefs seem to influence not just abstract support for climate and energy policy, but the dollar amounts people state that they are willing to pay.\n\nLooking to work that specifically examines public WTP for renewables and fossil fuels, several studies have found that the public is WTP more for renewables than other sources of energy. For example, @nkansahWillingnessPayWind2019 compared WTP for wind against natural gas generation specifically and found consumers willing to pay more for wind. Along similar lines, @murakamiConsumersWillingnessPay2015 placed fossil fuels, renewables, and nuclear power on the same WTP scale in the US and Japan, and found that respondents in both countries expressed positive WTP for increased renewable generation but negative WTP for increased nuclear generation, with US respondents expressing a stronger preference for renewables than Japanese respondents. However, @walterExaminingWillingnessPay2023 found that US respondents' preferences over fossil versus renewable energy futures depended on their geographic proximity to fossil fuel production and their opinion about anthropogenic climate change. Finally, @liPublicSupportReducing2009 estimated household WTP for a federal energy research and development fund aimed at reducing reliance on fossil fuels, and found broad support for that funding, suggesting that WTP responds to reducing fossil fuel use on its own without reference to another energy source. ^[It should be noted that WTP for energy is not just a function of partisanship or environmental beliefs. @cardellaPriceVolatilityResidential2017 found that price volatility, not just price level, shapes residential customers' generation-source decisions, and @knappWillConsumersReally2020 found that stated WTP for green electricity programs does not consistently translate into enrollment once a real premium is offered. @aldyWillingnessPayPolitical2012 likewise found that WTP for a national clean energy standard depended on how the standard was structured, in addition to the respondents' political affiliations.] \n\n## Theoretical Expectations \n\nPrevious research suggests that partisan cues are an important driver of energy preferences and that partisanship and environmental beliefs shape the WTP for energy sources. In this study, I use a survey experiment to examine the influence of a Trump cue and a climate change cue on preferences and the stated WTP for fossil fuels versus renewables. \n\nOverall, I expect that conservative Republicans will prefer and be WTP more for fossil fuels, and liberal Democrats will prefer and be WTP more for renewables. In addition, I expect there to be both general and partisan shifts in preferences and WTP based on the cues. Those who receive the Trump cue will prioritize fossil fuels and be willing to pay more for them, whereas those in the climate condition will prioritize renewable sources and be willing to pay more for them than those in the control condition. Finally, I expect the effects of the cues to depend on political beliefs. Specifically, conservative Republicans who receive the Trump cue will be more supportive of and WTP more for fossil fuels, whereas liberal Democrats who receive the climate cue will prefer and be WTP more for renewables. The comparison groups are those with other political beliefs and those in the control condition. \n\n# Data and Measures\n\nTo examine the importance of cues and political beliefs in energy preferences I use a survey experiment to examine respondents' prioritization of fossil fuels versus renewables as well as their WTP for those sources to generate electricity in response to a Trump cue or a climate change cue. Respondents were recruited using Cloud Research, which provides a quota-based sample of US residents, with quotas for age, race, and gender based on US Census data. Additionally, to further ensure as representative a sample as possible, I used the `survey` and `anesrake` packages in `R` to perform iterative raking to compute survey weights that weight respondents based on the US Census's 2023 American Community Survey (ACS) on demographic variables, including age, race, gender, and education. I also used the Pew Research Center's National Public Opinion Reference Survey (NPORS) from 2025 to weight the sample based on political party affiliation. I surveyed 3113 US residents in April 2026, who were randomly assigned to receive one of three treatments, including a cue about Trump's critiques of renewable energy and his support for fossil fuels (n = 1049), a climate change cue that stated scientists recommend moving away from fossil fuels to renewables to address climate change (n = 1013), or a control condition with no cue (n = 1051).\n\nAll respondents were shown the following paragraph: \n\n> The use of renewable energy sources for electricity, including wind energy, solar energy, and battery storage, has risen sharply in recent years. Indeed, most of the growth in new electricity generation in the U.S. has come from renewable sources. \n\nRespondents were then shown the following statement. Those in the Trump cue saw President Trump named specifically, while those in the climate cue and the control were shown _some have_\n\n> However, [_President Trump has_/_some have_] argued that renewable sources are not reliable and that we need to increase our reliance on fossil fuels (coal, oil, and natural gas) to ensure energy security.\n\nThose in the climate cue saw the following: \n\n> Additionally, scientists have warned that an increase in the use of fossil fuels will make climate change worse; therefore, we should increase our use of renewable sources.\n\nFinally, all respondents were shown: \n\n> Please consider how you think we should prioritize the development of fossil fuels and renewable sources to generate electricity.\n\nAfter receiving the cues, respondents were asked, on a 1 to 7 scale, if fossil fuels should be prioritized (= 1), fossil fuels and renewables should be prioritized equally (= 4), or renewable sources should be prioritized (= 7). Next, I asked respondents their willingness-to-pay (WTP) for fossil fuel and renewable sources using the Gabor-Granger method [@gaborPriceIndicatorQuality1966]. With the Gabor-Granger method, respondents are shown a random dollar amount and if they are willing to pay that amount, they are next shown a higher amount, and if they are not, they are shown a smaller amount. This approach is a well-established survey-based technique for estimating WTP. It dates to early applications of iterative-bidding price experiments [@jonesSurveyTechniqueMeasure1975] and was later formalized in marketing research [@wedelModelEffectsPsychological1998]. It remains one of the standard indirect approaches used to measure WTP [@lipovetskyPricingModelsMarketing2011; @breidertReviewMethodsMeasuring2006]. \n\nTo establish WTP, I first give respondents information about potential costs associated with each energy source, and the sources were presented in random order. In the WTP for fossil fuels question, I noted that costs associated with renewable energy have decreased and, therefore they may need to pay more to use fossil fuels. For renewable sources respondents were told about the need to increase distribution. Specifically, respondents were shown:  \n\n> The cost of generating electricity from renewable sources has decreased in recent years. In many places, renewable energy sources are often more cost-effective than fossil fuels. Would you support the increased use of fossil fuels if your electricity bill were to increase by the following each month?\n\n> Renewable sources have become cheaper in recent years; however, investments are needed to distribute the electricity they produce to homes and businesses. Would you support the increased use of renewable sources if your electricity bill were to increase by the following each month?\n\nTo estimate the maximum/minimum WTP, respondents were first shown a random dollar amount between \\$1 and \\$46, in five-dollar increments, and asked if they would be WTP that amount extra per-month in their electricity bill. If they indicated yes they were shown a larger, random dollar-amount, and if they indicated no they were shown a smaller dollar-amount. This continues until they reach the \\$46-maximum or \\$1-minimum. Respondents who indicated no at \\$1 were coded with a WTP of 0.  \n\nIn the following analysis, I examine the prioritization of fossil fuels vs. renewables and the WTP for those energy sources as a function of the cues and political beliefs. Political beliefs include conservative Republicans and liberal Democrats, with other political beliefs (moderate independents, conservative Democrats, liberal Republicans) as the excluded referents. The political belief measures were constructed based on responses to a self-reported, 7-point ideology scale (1 = very liberal, 2 = somewhat liberal, 3 = slightly liberal, 4 = middle of the road, 5 = slightly conservative, 6 = somewhat conservative, 7 = very conservative) and political party identification. Conservative Republican is coded 1 for respondents who identify as Republican and place themselves at 5, 6, or 7 on the ideology scale (slightly, somewhat, or very conservative), and liberal Democrat is coded 1 for respondents who identify as Democrat and place themselves at 1, 2, or 3 (slightly, somewhat, or very liberal).\n\n\n::: {#tbl-descriptives .cell tbl-cap='Descriptive statistics for the energy-priority scale and political belief measures (survey-weighted means and standard deviations)'}\n::: {.cell-output-display}\n\n\n|Variable                    | Mean|   SD| Min| Max|\n|:---------------------------|----:|----:|---:|---:|\n|Energy-priority scale (1-7) | 5.17| 1.74|   1|   7|\n|Liberal Democrat            | 0.37| 0.48|   0|   1|\n|Conservative Republican     | 0.40| 0.49|   0|   1|\n\n\n:::\n:::\n\n\nDescriptive statistics for the energy-priority scale and the political belief measures are shown in @tbl-descriptives. The mean on the energy-priority scale was 5.17 (SD = 1.74), which is above the midpoint of 4 and indicates that respondents, on average, leaned toward prioritizing renewables over fossil fuels. Regarding political beliefs, 37 percent of the weighted sample were liberal Democrats and 40 percent were conservative Republicans, with the remaining 23 percent holding other political beliefs. \n\n# Results\n\nFirst, I use OLS to examine the prioritization respondents gave to fossil fuels versus renewables as a function of the cues, their political beliefs, and the interaction between cues and political beliefs. The results are shown in @tbl-priority-ols.\n\n\n::: {#tbl-priority-ols .cell tbl-cap='Effect of cue condition, political beliefs, and their interaction on the energy source-priority scale (survey-weighted OLS; control condition and other/moderate identity as reference)'}\n::: {.cell-output-display}\n\n```{=html}\n<!-- preamble start -->\n\n    <script src=\"https://cdn.jsdelivr.net/gh/vincentarelbundock/tinytable@main/inst/tinytable.js\"></script>\n\n    <script>\n      // Create table-specific functions using external factory\n      const tableFns_30r2zxtxaujn1sfdiwc2 = TinyTable.createTableFunctions(\"tinytable_30r2zxtxaujn1sfdiwc2\");\n      // tinytable span after\n      window.addEventListener('load', function () {\n          var cellsToStyle = [\n            // tinytable style arrays after\n          { positions: [ { i: '20', j: 2 } ], css_id: 'tinytable_css_flfsxj8wpnq3fa4h7ajf',}, \n          { positions: [ { i: '18', j: 2 } ], css_id: 'tinytable_css_0r3gy72k91e24cqcak4f',}, \n          { positions: [ { i: '1', j: 2 }, { i: '2', j: 2 }, { i: '3', j: 2 }, { i: '4', j: 2 }, { i: '5', j: 2 }, { i: '6', j: 2 }, { i: '7', j: 2 }, { i: '8', j: 2 }, { i: '9', j: 2 }, { i: '10', j: 2 }, { i: '11', j: 2 }, { i: '12', j: 2 }, { i: '13', j: 2 }, { i: '14', j: 2 }, { i: '15', j: 2 }, { i: '16', j: 2 }, { i: '17', j: 2 }, { i: '19', j: 2 } ], css_id: 'tinytable_css_psox14ffdgscj74dd5vf',}, \n          { positions: [ { i: '0', j: 2 } ], css_id: 'tinytable_css_lpwyipsyi6hrwja7r9bk',}, \n          { positions: [ { i: '20', j: 1 } ], css_id: 'tinytable_css_yds9zo4f1i5bokhyenax',}, \n          { positions: [ { i: '18', j: 1 } ], css_id: 'tinytable_css_svw60ud5a9cpbhasjmje',}, \n          { positions: [ { i: '1', j: 1 }, { i: '2', j: 1 }, { i: '3', j: 1 }, { i: '4', j: 1 }, { i: '5', j: 1 }, { i: '6', j: 1 }, { i: '7', j: 1 }, { i: '8', j: 1 }, { i: '9', j: 1 }, { i: '10', j: 1 }, { i: '11', j: 1 }, { i: '12', j: 1 }, { i: '13', j: 1 }, { i: '14', j: 1 }, { i: '15', j: 1 }, { i: '16', j: 1 }, { i: '17', j: 1 }, { i: '19', j: 1 } ], css_id: 'tinytable_css_ae7ew1opgboqatxu1q29',}, \n          { positions: [ { i: '0', j: 1 } ], css_id: 'tinytable_css_1p4s02s1mb3pk2xlqgwq',}, \n          ];\n\n          // Loop over the arrays to style the cells\n          cellsToStyle.forEach(function (group) {\n              group.positions.forEach(function (cell) {\n                  tableFns_30r2zxtxaujn1sfdiwc2.styleCell(cell.i, cell.j, group.css_id);\n              });\n          });\n      });\n    </script>\n\n    <link rel=\"stylesheet\" href=\"https://cdn.jsdelivr.net/gh/vincentarelbundock/tinytable@main/inst/tinytable.css\">\n    <style>\n    /* tinytable css entries after */\n    #tinytable_30r2zxtxaujn1sfdiwc2 td.tinytable_css_flfsxj8wpnq3fa4h7ajf, #tinytable_30r2zxtxaujn1sfdiwc2 th.tinytable_css_flfsxj8wpnq3fa4h7ajf {  position: relative; --border-bottom: 1; --border-left: 0; --border-right: 0; --border-top: 0; --line-color-bottom: var(--tt-line-color); --line-color-left: var(--tt-line-color); --line-color-right: var(--tt-line-color); --line-color-top: var(--tt-line-color); --line-width-bottom: 0.08em; --line-width-left: 0.1em; --line-width-right: 0.1em; --line-width-top: 0.1em; --trim-bottom-left: 0%; --trim-bottom-right: 0%; --trim-left-bottom: 0%; --trim-left-top: 0%; --trim-right-bottom: 0%; --trim-right-top: 0%; --trim-top-left: 0%; --trim-top-right: 0%; ; text-align: center }\n    #tinytable_30r2zxtxaujn1sfdiwc2 td.tinytable_css_0r3gy72k91e24cqcak4f, #tinytable_30r2zxtxaujn1sfdiwc2 th.tinytable_css_0r3gy72k91e24cqcak4f {  position: relative; --border-bottom: 1; --border-left: 0; --border-right: 0; --border-top: 0; --line-color-bottom: var(--tt-line-color); --line-color-left: var(--tt-line-color); --line-color-right: var(--tt-line-color); --line-color-top: var(--tt-line-color); --line-width-bottom: 0.05em; --line-width-left: 0.1em; --line-width-right: 0.1em; --line-width-top: 0.1em; --trim-bottom-left: 0%; --trim-bottom-right: 0%; --trim-left-bottom: 0%; --trim-left-top: 0%; --trim-right-bottom: 0%; --trim-right-top: 0%; --trim-top-left: 0%; --trim-top-right: 0%; ; text-align: center }\n    #tinytable_30r2zxtxaujn1sfdiwc2 td.tinytable_css_psox14ffdgscj74dd5vf, #tinytable_30r2zxtxaujn1sfdiwc2 th.tinytable_css_psox14ffdgscj74dd5vf { text-align: center }\n    #tinytable_30r2zxtxaujn1sfdiwc2 td.tinytable_css_lpwyipsyi6hrwja7r9bk, #tinytable_30r2zxtxaujn1sfdiwc2 th.tinytable_css_lpwyipsyi6hrwja7r9bk {  position: relative; --border-bottom: 1; --border-left: 0; --border-right: 0; --border-top: 1; --line-color-bottom: var(--tt-line-color); --line-color-left: var(--tt-line-color); --line-color-right: var(--tt-line-color); --line-color-top: var(--tt-line-color); --line-width-bottom: 0.05em; --line-width-left: 0.1em; --line-width-right: 0.1em; --line-width-top: 0.08em; --trim-bottom-left: 0%; --trim-bottom-right: 0%; --trim-left-bottom: 0%; --trim-left-top: 0%; --trim-right-bottom: 0%; --trim-right-top: 0%; --trim-top-left: 0%; --trim-top-right: 0%; ; text-align: center }\n    #tinytable_30r2zxtxaujn1sfdiwc2 td.tinytable_css_yds9zo4f1i5bokhyenax, #tinytable_30r2zxtxaujn1sfdiwc2 th.tinytable_css_yds9zo4f1i5bokhyenax {  position: relative; --border-bottom: 1; --border-left: 0; --border-right: 0; --border-top: 0; --line-color-bottom: var(--tt-line-color); --line-color-left: var(--tt-line-color); --line-color-right: var(--tt-line-color); --line-color-top: var(--tt-line-color); --line-width-bottom: 0.08em; --line-width-left: 0.1em; --line-width-right: 0.1em; --line-width-top: 0.1em; --trim-bottom-left: 0%; --trim-bottom-right: 0%; --trim-left-bottom: 0%; --trim-left-top: 0%; --trim-right-bottom: 0%; --trim-right-top: 0%; --trim-top-left: 0%; --trim-top-right: 0%; ; text-align: left }\n    #tinytable_30r2zxtxaujn1sfdiwc2 td.tinytable_css_svw60ud5a9cpbhasjmje, #tinytable_30r2zxtxaujn1sfdiwc2 th.tinytable_css_svw60ud5a9cpbhasjmje {  position: relative; --border-bottom: 1; --border-left: 0; --border-right: 0; --border-top: 0; --line-color-bottom: var(--tt-line-color); --line-color-left: var(--tt-line-color); --line-color-right: var(--tt-line-color); --line-color-top: var(--tt-line-color); --line-width-bottom: 0.05em; --line-width-left: 0.1em; --line-width-right: 0.1em; --line-width-top: 0.1em; --trim-bottom-left: 0%; --trim-bottom-right: 0%; --trim-left-bottom: 0%; --trim-left-top: 0%; --trim-right-bottom: 0%; --trim-right-top: 0%; --trim-top-left: 0%; --trim-top-right: 0%; ; text-align: left }\n    #tinytable_30r2zxtxaujn1sfdiwc2 td.tinytable_css_ae7ew1opgboqatxu1q29, #tinytable_30r2zxtxaujn1sfdiwc2 th.tinytable_css_ae7ew1opgboqatxu1q29 { text-align: left }\n    #tinytable_30r2zxtxaujn1sfdiwc2 td.tinytable_css_1p4s02s1mb3pk2xlqgwq, #tinytable_30r2zxtxaujn1sfdiwc2 th.tinytable_css_1p4s02s1mb3pk2xlqgwq {  position: relative; --border-bottom: 1; --border-left: 0; --border-right: 0; --border-top: 1; --line-color-bottom: var(--tt-line-color); --line-color-left: var(--tt-line-color); --line-color-right: var(--tt-line-color); --line-color-top: var(--tt-line-color); --line-width-bottom: 0.05em; --line-width-left: 0.1em; --line-width-right: 0.1em; --line-width-top: 0.08em; --trim-bottom-left: 0%; --trim-bottom-right: 0%; --trim-left-bottom: 0%; --trim-left-top: 0%; --trim-right-bottom: 0%; --trim-right-top: 0%; --trim-top-left: 0%; --trim-top-right: 0%; ; text-align: left }\n    </style>\n    <div class=\"container\">\n      <table class=\"tinytable\" id=\"tinytable_30r2zxtxaujn1sfdiwc2\" style=\"width: auto; margin-left: auto; margin-right: auto;\" data-quarto-disable-processing='true'>\n        \n        <thead>\n              <tr>\n                <th scope=\"col\" data-row=\"0\" data-col=\"1\"> </th>\n                <th scope=\"col\" data-row=\"0\" data-col=\"2\">Priority scale</th>\n              </tr>\n        </thead>\n        <tfoot><tr><td colspan='2'>† p < 0.1, * p < 0.05, ** p < 0.01</td></tr></tfoot>\n        <tbody>\n                <tr>\n                  <td data-row=\"1\" data-col=\"1\">Trump cue</td>\n                  <td data-row=\"1\" data-col=\"2\">-0.016</td>\n                </tr>\n                <tr>\n                  <td data-row=\"2\" data-col=\"1\"></td>\n                  <td data-row=\"2\" data-col=\"2\">(0.159)</td>\n                </tr>\n                <tr>\n                  <td data-row=\"3\" data-col=\"1\">Climate cue</td>\n                  <td data-row=\"3\" data-col=\"2\">-0.137</td>\n                </tr>\n                <tr>\n                  <td data-row=\"4\" data-col=\"1\"></td>\n                  <td data-row=\"4\" data-col=\"2\">(0.153)</td>\n                </tr>\n                <tr>\n                  <td data-row=\"5\" data-col=\"1\">Liberal Democrat</td>\n                  <td data-row=\"5\" data-col=\"2\">0.674**</td>\n                </tr>\n                <tr>\n                  <td data-row=\"6\" data-col=\"1\"></td>\n                  <td data-row=\"6\" data-col=\"2\">(0.126)</td>\n                </tr>\n                <tr>\n                  <td data-row=\"7\" data-col=\"1\">Conservative Republican</td>\n                  <td data-row=\"7\" data-col=\"2\">-1.236**</td>\n                </tr>\n                <tr>\n                  <td data-row=\"8\" data-col=\"1\"></td>\n                  <td data-row=\"8\" data-col=\"2\">(0.150)</td>\n                </tr>\n                <tr>\n                  <td data-row=\"9\" data-col=\"1\">Trump cue × Liberal Democrat</td>\n                  <td data-row=\"9\" data-col=\"2\">0.137</td>\n                </tr>\n                <tr>\n                  <td data-row=\"10\" data-col=\"1\"></td>\n                  <td data-row=\"10\" data-col=\"2\">(0.184)</td>\n                </tr>\n                <tr>\n                  <td data-row=\"11\" data-col=\"1\">Climate cue × Liberal Democrat</td>\n                  <td data-row=\"11\" data-col=\"2\">0.341†</td>\n                </tr>\n                <tr>\n                  <td data-row=\"12\" data-col=\"1\"></td>\n                  <td data-row=\"12\" data-col=\"2\">(0.174)</td>\n                </tr>\n                <tr>\n                  <td data-row=\"13\" data-col=\"1\">Trump cue × Conservative Republican</td>\n                  <td data-row=\"13\" data-col=\"2\">-0.438†</td>\n                </tr>\n                <tr>\n                  <td data-row=\"14\" data-col=\"1\"></td>\n                  <td data-row=\"14\" data-col=\"2\">(0.235)</td>\n                </tr>\n                <tr>\n                  <td data-row=\"15\" data-col=\"1\">Climate cue × Conservative Republican</td>\n                  <td data-row=\"15\" data-col=\"2\">0.079</td>\n                </tr>\n                <tr>\n                  <td data-row=\"16\" data-col=\"1\"></td>\n                  <td data-row=\"16\" data-col=\"2\">(0.221)</td>\n                </tr>\n                <tr>\n                  <td data-row=\"17\" data-col=\"1\">(Intercept)</td>\n                  <td data-row=\"17\" data-col=\"2\">5.443**</td>\n                </tr>\n                <tr>\n                  <td data-row=\"18\" data-col=\"1\"></td>\n                  <td data-row=\"18\" data-col=\"2\">(0.109)</td>\n                </tr>\n                <tr>\n                  <td data-row=\"19\" data-col=\"1\">Num.Obs.</td>\n                  <td data-row=\"19\" data-col=\"2\">3113</td>\n                </tr>\n                <tr>\n                  <td data-row=\"20\" data-col=\"1\">Adj. R2</td>\n                  <td data-row=\"20\" data-col=\"2\">0.313</td>\n                </tr>\n        </tbody>\n      </table>\n    </div>\n<!-- hack to avoid NA insertion in last line -->\n```\n\n:::\n:::\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n![Predicted energy source-priority scale (1-7) by cue condition and political identity (survey-weighted OLS predictions with 95% CIs)](cue-WTP_files/figure-html/fig-priority-predicted-1.png){#fig-priority-predicted width=672}\n:::\n:::\n\n\nAs expected, conservative Republicans were more likely to prioritize fossil fuels than renewables, with an estimated coefficient of -1.24 on the 1 to 7 scale, and liberal Democrats prioritized renewables at 0.67. In terms of the interactions, conservative Republicans who received the Trump cue were more likely to prioritize fossil fuels (b = -0.44, *p* = 0.062), whereas liberal Democrats in the climate condition were more likely to prioritize renewables (b = 0.34). Overall, the predicted value on the 1 to 7 scale for conservative Republicans in the control group was 4.21, indicating a split roughly evenly between fossil fuels and renewables, and it was 3.75 for those receiving the Trump cue, indicating a significant shift toward prioritizing fossil fuels (difference = -0.45, *p* = 0.009). For liberal Democrats the predicted value was 6.12, indicating a priority for renewables, and the value was 6.32 in the climate condition (difference = 0.20, *p* = 0.015). The interactions of cue x political beliefs were significant at *p*<0.10; however, the cues themselves had no effect, on average, on energy source priority compared to the control condition.\n\nNext, I examine the percent of respondents at each possible dollar amount of the WTP measure for each source. Those results are in @tbl-wtp-dist.\n\n\n::: {#tbl-wtp-dist .cell tbl-cap='Distribution of willingness-to-pay for fossil fuel and renewable electricity (weighted percent of respondents choosing each dollar amount)'}\n::: {.cell-output-display}\n\n\n| WTP ($)| Fossil fuels (%)| Renewables (%)|\n|-------:|----------------:|--------------:|\n|       0|             47.0|           14.0|\n|       1|             14.7|           15.6|\n|       6|             10.6|           14.0|\n|      11|              5.6|            9.1|\n|      16|              4.9|            7.3|\n|      21|              2.7|            4.3|\n|      26|              2.9|            5.8|\n|      31|              1.2|            3.2|\n|      36|              2.1|            4.7|\n|      41|              1.9|            3.8|\n|      46|              6.3|           18.3|\n\n\n:::\n:::\n\n\nAs shown, nearly half of respondents, 47 percent, were not willing to pay any additional amount for fossil fuels, whereas 18.3 percent were willing to pay the max, \\$46 for renewables. Overall, the median WTP for fossil fuels was \\$1 with a mean of \\$8.33. For renewables the median WTP was \\$11 and the mean was \\$18.21. Comparing the differences in median and means, the median difference in WTP for renewables versus fossil fuels was \\$10. For the mean, the difference was \\$9.88, which is significant based on a survey-weighted paired t-test (*t* = 22.9, *df* = 3111, *p* < .001).\n\nGiven the large percentage of respondents with a WTP = \\$0 for fossil fuels, I model the WTP for fossil fuels in two parts. First, I use a logit model to see whether a respondent has any positive WTP. Next, using OLS, I examine the WTP for fossil fuels, among those who are WTP >0, and for renewables. The results of all three models are shown in @tbl-wtp-models.\n\n\n::: {#tbl-wtp-models .cell tbl-cap='Effect of cue condition, political beliefs, and their interaction on willingness-to-pay for fossil fuels (any positive WTP, and amount among those with any positive WTP) and for renewables (survey-weighted logit/OLS; control condition and other/moderate identity as reference)'}\n::: {.cell-output-display}\n\n```{=html}\n<!-- preamble start -->\n\n    <script src=\"https://cdn.jsdelivr.net/gh/vincentarelbundock/tinytable@main/inst/tinytable.js\"></script>\n\n    <script>\n      // Create table-specific functions using external factory\n      const tableFns_65gq1bny18nzwqswlgmw = TinyTable.createTableFunctions(\"tinytable_65gq1bny18nzwqswlgmw\");\n      // tinytable span after\n      window.addEventListener('load', function () {\n          var cellsToStyle = [\n            // tinytable style arrays after\n          { positions: [ { i: '21', j: 2 }, { i: '21', j: 3 }, { i: '21', j: 4 } ], css_id: 'tinytable_css_8j4fnk4yepl3bldd80xl',}, \n          { positions: [ { i: '18', j: 2 }, { i: '18', j: 3 }, { i: '18', j: 4 } ], css_id: 'tinytable_css_afs5q5avtmxhr4fenzzb',}, \n          { positions: [ { i: '1', j: 2 }, { i: '2', j: 2 }, { i: '3', j: 2 }, { i: '4', j: 2 }, { i: '5', j: 2 }, { i: '6', j: 2 }, { i: '7', j: 2 }, { i: '8', j: 2 }, { i: '9', j: 2 }, { i: '10', j: 2 }, { i: '11', j: 2 }, { i: '12', j: 2 }, { i: '13', j: 2 }, { i: '14', j: 2 }, { i: '15', j: 2 }, { i: '16', j: 2 }, { i: '17', j: 2 }, { i: '19', j: 2 }, { i: '20', j: 2 }, { i: '1', j: 3 }, { i: '2', j: 3 }, { i: '3', j: 3 }, { i: '4', j: 3 }, { i: '5', j: 3 }, { i: '6', j: 3 }, { i: '7', j: 3 }, { i: '8', j: 3 }, { i: '9', j: 3 }, { i: '10', j: 3 }, { i: '11', j: 3 }, { i: '12', j: 3 }, { i: '13', j: 3 }, { i: '14', j: 3 }, { i: '15', j: 3 }, { i: '16', j: 3 }, { i: '17', j: 3 }, { i: '19', j: 3 }, { i: '20', j: 3 }, { i: '1', j: 4 }, { i: '2', j: 4 }, { i: '3', j: 4 }, { i: '4', j: 4 }, { i: '5', j: 4 }, { i: '6', j: 4 }, { i: '7', j: 4 }, { i: '8', j: 4 }, { i: '9', j: 4 }, { i: '10', j: 4 }, { i: '11', j: 4 }, { i: '12', j: 4 }, { i: '13', j: 4 }, { i: '14', j: 4 }, { i: '15', j: 4 }, { i: '16', j: 4 }, { i: '17', j: 4 }, { i: '19', j: 4 }, { i: '20', j: 4 } ], css_id: 'tinytable_css_gu4n7rpasueuw3ty53bv',}, \n          { positions: [ { i: '0', j: 2 }, { i: '0', j: 3 }, { i: '0', j: 4 } ], css_id: 'tinytable_css_i204kl3v5am2ma1472i7',}, \n          { positions: [ { i: '21', j: 1 } ], css_id: 'tinytable_css_pkigk3ti1fzu04dz94i8',}, \n          { positions: [ { i: '18', j: 1 } ], css_id: 'tinytable_css_7uxbg2yfqima35eky5lx',}, \n          { positions: [ { i: '1', j: 1 }, { i: '2', j: 1 }, { i: '3', j: 1 }, { i: '4', j: 1 }, { i: '5', j: 1 }, { i: '6', j: 1 }, { i: '7', j: 1 }, { i: '8', j: 1 }, { i: '9', j: 1 }, { i: '10', j: 1 }, { i: '11', j: 1 }, { i: '12', j: 1 }, { i: '13', j: 1 }, { i: '14', j: 1 }, { i: '15', j: 1 }, { i: '16', j: 1 }, { i: '17', j: 1 }, { i: '19', j: 1 }, { i: '20', j: 1 } ], css_id: 'tinytable_css_qtxcrt0mr7jl7uzsft9w',}, \n          { positions: [ { i: '0', j: 1 } ], css_id: 'tinytable_css_4g91n67s9m84th1r8mbr',}, \n          ];\n\n          // Loop over the arrays to style the cells\n          cellsToStyle.forEach(function (group) {\n              group.positions.forEach(function (cell) {\n                  tableFns_65gq1bny18nzwqswlgmw.styleCell(cell.i, cell.j, group.css_id);\n              });\n          });\n      });\n    </script>\n\n    <link rel=\"stylesheet\" href=\"https://cdn.jsdelivr.net/gh/vincentarelbundock/tinytable@main/inst/tinytable.css\">\n    <style>\n    /* tinytable css entries after */\n    #tinytable_65gq1bny18nzwqswlgmw td.tinytable_css_8j4fnk4yepl3bldd80xl, #tinytable_65gq1bny18nzwqswlgmw th.tinytable_css_8j4fnk4yepl3bldd80xl {  position: relative; --border-bottom: 1; --border-left: 0; --border-right: 0; --border-top: 0; --line-color-bottom: var(--tt-line-color); --line-color-left: var(--tt-line-color); --line-color-right: var(--tt-line-color); --line-color-top: var(--tt-line-color); --line-width-bottom: 0.08em; --line-width-left: 0.1em; --line-width-right: 0.1em; --line-width-top: 0.1em; --trim-bottom-left: 0%; --trim-bottom-right: 0%; --trim-left-bottom: 0%; --trim-left-top: 0%; --trim-right-bottom: 0%; --trim-right-top: 0%; --trim-top-left: 0%; --trim-top-right: 0%; ; text-align: center }\n    #tinytable_65gq1bny18nzwqswlgmw td.tinytable_css_afs5q5avtmxhr4fenzzb, #tinytable_65gq1bny18nzwqswlgmw th.tinytable_css_afs5q5avtmxhr4fenzzb {  position: relative; --border-bottom: 1; --border-left: 0; --border-right: 0; --border-top: 0; --line-color-bottom: var(--tt-line-color); --line-color-left: var(--tt-line-color); --line-color-right: var(--tt-line-color); --line-color-top: var(--tt-line-color); --line-width-bottom: 0.05em; --line-width-left: 0.1em; --line-width-right: 0.1em; --line-width-top: 0.1em; --trim-bottom-left: 0%; --trim-bottom-right: 0%; --trim-left-bottom: 0%; --trim-left-top: 0%; --trim-right-bottom: 0%; --trim-right-top: 0%; --trim-top-left: 0%; --trim-top-right: 0%; ; text-align: center }\n    #tinytable_65gq1bny18nzwqswlgmw td.tinytable_css_gu4n7rpasueuw3ty53bv, #tinytable_65gq1bny18nzwqswlgmw th.tinytable_css_gu4n7rpasueuw3ty53bv { text-align: center }\n    #tinytable_65gq1bny18nzwqswlgmw td.tinytable_css_i204kl3v5am2ma1472i7, #tinytable_65gq1bny18nzwqswlgmw th.tinytable_css_i204kl3v5am2ma1472i7 {  position: relative; --border-bottom: 1; --border-left: 0; --border-right: 0; --border-top: 1; --line-color-bottom: var(--tt-line-color); --line-color-left: var(--tt-line-color); --line-color-right: var(--tt-line-color); --line-color-top: var(--tt-line-color); --line-width-bottom: 0.05em; --line-width-left: 0.1em; --line-width-right: 0.1em; --line-width-top: 0.08em; --trim-bottom-left: 0%; --trim-bottom-right: 0%; --trim-left-bottom: 0%; --trim-left-top: 0%; --trim-right-bottom: 0%; --trim-right-top: 0%; --trim-top-left: 0%; --trim-top-right: 0%; ; text-align: center }\n    #tinytable_65gq1bny18nzwqswlgmw td.tinytable_css_pkigk3ti1fzu04dz94i8, #tinytable_65gq1bny18nzwqswlgmw th.tinytable_css_pkigk3ti1fzu04dz94i8 {  position: relative; --border-bottom: 1; --border-left: 0; --border-right: 0; --border-top: 0; --line-color-bottom: var(--tt-line-color); --line-color-left: var(--tt-line-color); --line-color-right: var(--tt-line-color); --line-color-top: var(--tt-line-color); --line-width-bottom: 0.08em; --line-width-left: 0.1em; --line-width-right: 0.1em; --line-width-top: 0.1em; --trim-bottom-left: 0%; --trim-bottom-right: 0%; --trim-left-bottom: 0%; --trim-left-top: 0%; --trim-right-bottom: 0%; --trim-right-top: 0%; --trim-top-left: 0%; --trim-top-right: 0%; ; text-align: left }\n    #tinytable_65gq1bny18nzwqswlgmw td.tinytable_css_7uxbg2yfqima35eky5lx, #tinytable_65gq1bny18nzwqswlgmw th.tinytable_css_7uxbg2yfqima35eky5lx {  position: relative; --border-bottom: 1; --border-left: 0; --border-right: 0; --border-top: 0; --line-color-bottom: var(--tt-line-color); --line-color-left: var(--tt-line-color); --line-color-right: var(--tt-line-color); --line-color-top: var(--tt-line-color); --line-width-bottom: 0.05em; --line-width-left: 0.1em; --line-width-right: 0.1em; --line-width-top: 0.1em; --trim-bottom-left: 0%; --trim-bottom-right: 0%; --trim-left-bottom: 0%; --trim-left-top: 0%; --trim-right-bottom: 0%; --trim-right-top: 0%; --trim-top-left: 0%; --trim-top-right: 0%; ; text-align: left }\n    #tinytable_65gq1bny18nzwqswlgmw td.tinytable_css_qtxcrt0mr7jl7uzsft9w, #tinytable_65gq1bny18nzwqswlgmw th.tinytable_css_qtxcrt0mr7jl7uzsft9w { text-align: left }\n    #tinytable_65gq1bny18nzwqswlgmw td.tinytable_css_4g91n67s9m84th1r8mbr, #tinytable_65gq1bny18nzwqswlgmw th.tinytable_css_4g91n67s9m84th1r8mbr {  position: relative; --border-bottom: 1; --border-left: 0; --border-right: 0; --border-top: 1; --line-color-bottom: var(--tt-line-color); --line-color-left: var(--tt-line-color); --line-color-right: var(--tt-line-color); --line-color-top: var(--tt-line-color); --line-width-bottom: 0.05em; --line-width-left: 0.1em; --line-width-right: 0.1em; --line-width-top: 0.08em; --trim-bottom-left: 0%; --trim-bottom-right: 0%; --trim-left-bottom: 0%; --trim-left-top: 0%; --trim-right-bottom: 0%; --trim-right-top: 0%; --trim-top-left: 0%; --trim-top-right: 0%; ; text-align: left }\n    </style>\n    <div class=\"container\">\n      <table class=\"tinytable\" id=\"tinytable_65gq1bny18nzwqswlgmw\" style=\"width: auto; margin-left: auto; margin-right: auto;\" data-quarto-disable-processing='true'>\n        \n        <thead>\n              <tr>\n                <th scope=\"col\" data-row=\"0\" data-col=\"1\"> </th>\n                <th scope=\"col\" data-row=\"0\" data-col=\"2\">Fossil fuels: Any WTP (logit)</th>\n                <th scope=\"col\" data-row=\"0\" data-col=\"3\">Fossil fuels: Amount, if WTP > $0 (OLS)</th>\n                <th scope=\"col\" data-row=\"0\" data-col=\"4\">Renewables: Amount (OLS)</th>\n              </tr>\n        </thead>\n        <tfoot><tr><td colspan='4'>† p < 0.1, * p < 0.05, ** p < 0.01</td></tr></tfoot>\n        <tbody>\n                <tr>\n                  <td data-row=\"1\" data-col=\"1\">Trump cue</td>\n                  <td data-row=\"1\" data-col=\"2\">-0.263</td>\n                  <td data-row=\"1\" data-col=\"3\">-3.607</td>\n                  <td data-row=\"1\" data-col=\"4\">-1.495</td>\n                </tr>\n                <tr>\n                  <td data-row=\"2\" data-col=\"1\"></td>\n                  <td data-row=\"2\" data-col=\"2\">(0.204)</td>\n                  <td data-row=\"2\" data-col=\"3\">(2.265)</td>\n                  <td data-row=\"2\" data-col=\"4\">(1.828)</td>\n                </tr>\n                <tr>\n                  <td data-row=\"3\" data-col=\"1\">Climate cue</td>\n                  <td data-row=\"3\" data-col=\"2\">0.100</td>\n                  <td data-row=\"3\" data-col=\"3\">-1.509</td>\n                  <td data-row=\"3\" data-col=\"4\">-1.604</td>\n                </tr>\n                <tr>\n                  <td data-row=\"4\" data-col=\"1\"></td>\n                  <td data-row=\"4\" data-col=\"2\">(0.206)</td>\n                  <td data-row=\"4\" data-col=\"3\">(2.250)</td>\n                  <td data-row=\"4\" data-col=\"4\">(1.741)</td>\n                </tr>\n                <tr>\n                  <td data-row=\"5\" data-col=\"1\">Liberal Democrat</td>\n                  <td data-row=\"5\" data-col=\"2\">-0.413*</td>\n                  <td data-row=\"5\" data-col=\"3\">-0.075</td>\n                  <td data-row=\"5\" data-col=\"4\">5.703**</td>\n                </tr>\n                <tr>\n                  <td data-row=\"6\" data-col=\"1\"></td>\n                  <td data-row=\"6\" data-col=\"2\">(0.182)</td>\n                  <td data-row=\"6\" data-col=\"3\">(2.130)</td>\n                  <td data-row=\"6\" data-col=\"4\">(1.569)</td>\n                </tr>\n                <tr>\n                  <td data-row=\"7\" data-col=\"1\">Conservative Republican</td>\n                  <td data-row=\"7\" data-col=\"2\">0.704**</td>\n                  <td data-row=\"7\" data-col=\"3\">-3.275</td>\n                  <td data-row=\"7\" data-col=\"4\">-6.620**</td>\n                </tr>\n                <tr>\n                  <td data-row=\"8\" data-col=\"1\"></td>\n                  <td data-row=\"8\" data-col=\"2\">(0.205)</td>\n                  <td data-row=\"8\" data-col=\"3\">(2.092)</td>\n                  <td data-row=\"8\" data-col=\"4\">(1.626)</td>\n                </tr>\n                <tr>\n                  <td data-row=\"9\" data-col=\"1\">Trump cue × Liberal Democrat</td>\n                  <td data-row=\"9\" data-col=\"2\">0.007</td>\n                  <td data-row=\"9\" data-col=\"3\">3.124</td>\n                  <td data-row=\"9\" data-col=\"4\">1.656</td>\n                </tr>\n                <tr>\n                  <td data-row=\"10\" data-col=\"1\"></td>\n                  <td data-row=\"10\" data-col=\"2\">(0.257)</td>\n                  <td data-row=\"10\" data-col=\"3\">(2.871)</td>\n                  <td data-row=\"10\" data-col=\"4\">(2.234)</td>\n                </tr>\n                <tr>\n                  <td data-row=\"11\" data-col=\"1\">Climate cue × Liberal Democrat</td>\n                  <td data-row=\"11\" data-col=\"2\">-0.270</td>\n                  <td data-row=\"11\" data-col=\"3\">1.507</td>\n                  <td data-row=\"11\" data-col=\"4\">3.136</td>\n                </tr>\n                <tr>\n                  <td data-row=\"12\" data-col=\"1\"></td>\n                  <td data-row=\"12\" data-col=\"2\">(0.259)</td>\n                  <td data-row=\"12\" data-col=\"3\">(3.026)</td>\n                  <td data-row=\"12\" data-col=\"4\">(2.167)</td>\n                </tr>\n                <tr>\n                  <td data-row=\"13\" data-col=\"1\">Trump cue × Conservative Republican</td>\n                  <td data-row=\"13\" data-col=\"2\">0.423</td>\n                  <td data-row=\"13\" data-col=\"3\">3.919</td>\n                  <td data-row=\"13\" data-col=\"4\">0.320</td>\n                </tr>\n                <tr>\n                  <td data-row=\"14\" data-col=\"1\"></td>\n                  <td data-row=\"14\" data-col=\"2\">(0.299)</td>\n                  <td data-row=\"14\" data-col=\"3\">(2.964)</td>\n                  <td data-row=\"14\" data-col=\"4\">(2.337)</td>\n                </tr>\n                <tr>\n                  <td data-row=\"15\" data-col=\"1\">Climate cue × Conservative Republican</td>\n                  <td data-row=\"15\" data-col=\"2\">-0.042</td>\n                  <td data-row=\"15\" data-col=\"3\">3.665</td>\n                  <td data-row=\"15\" data-col=\"4\">2.935</td>\n                </tr>\n                <tr>\n                  <td data-row=\"16\" data-col=\"1\"></td>\n                  <td data-row=\"16\" data-col=\"2\">(0.293)</td>\n                  <td data-row=\"16\" data-col=\"3\">(2.917)</td>\n                  <td data-row=\"16\" data-col=\"4\">(2.311)</td>\n                </tr>\n                <tr>\n                  <td data-row=\"17\" data-col=\"1\">(Intercept)</td>\n                  <td data-row=\"17\" data-col=\"2\">0.048</td>\n                  <td data-row=\"17\" data-col=\"3\">17.374**</td>\n                  <td data-row=\"17\" data-col=\"4\">18.665**</td>\n                </tr>\n                <tr>\n                  <td data-row=\"18\" data-col=\"1\"></td>\n                  <td data-row=\"18\" data-col=\"2\">(0.145)</td>\n                  <td data-row=\"18\" data-col=\"3\">(1.712)</td>\n                  <td data-row=\"18\" data-col=\"4\">(1.271)</td>\n                </tr>\n                <tr>\n                  <td data-row=\"19\" data-col=\"1\">Num.Obs.</td>\n                  <td data-row=\"19\" data-col=\"2\">3113</td>\n                  <td data-row=\"19\" data-col=\"3\">1433</td>\n                  <td data-row=\"19\" data-col=\"4\">3113</td>\n                </tr>\n                <tr>\n                  <td data-row=\"20\" data-col=\"1\">Adj. R2</td>\n                  <td data-row=\"20\" data-col=\"2\"></td>\n                  <td data-row=\"20\" data-col=\"3\">0.002</td>\n                  <td data-row=\"20\" data-col=\"4\">0.104</td>\n                </tr>\n                <tr>\n                  <td data-row=\"21\" data-col=\"1\">McFadden's pseudo R2</td>\n                  <td data-row=\"21\" data-col=\"2\">0.061</td>\n                  <td data-row=\"21\" data-col=\"3\"></td>\n                  <td data-row=\"21\" data-col=\"4\"></td>\n                </tr>\n        </tbody>\n      </table>\n    </div>\n<!-- hack to avoid NA insertion in last line -->\n```\n\n:::\n:::\n\n\nFor fossil fuels, conservative Republicans were significantly more likely than the reference group to have any positive WTP (b = 0.70, log-odds scale), predicted at 68.0% in the control condition compared to 41.0% for liberal Democrats (b = -0.41, *p* = 0.023). However, the cues were not significant nor were the interactions between the cues and political beliefs. The WTP amounts are shown in @fig-wtp-fossil-predicted and @fig-wtp-renewable-predicted. \n\n\n::: {.cell}\n::: {.cell-output-display}\n![Predicted willingness-to-pay for fossil fuels, among respondents with any positive WTP, by cue condition and political identity (survey-weighted OLS predictions with 95% CIs)](cue-WTP_files/figure-html/fig-wtp-fossil-predicted-1.png){#fig-wtp-fossil-predicted width=672}\n:::\n:::\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n![Predicted willingness-to-pay for renewables by cue condition and political identity (survey-weighted OLS predictions with 95% CIs)](cue-WTP_files/figure-html/fig-wtp-renewable-predicted-1.png){#fig-wtp-renewable-predicted width=672}\n:::\n:::\n\n\nFor fossil fuels, neither the Trump cue nor its interaction with conservative Republican identity significantly predicted a WTP > \\$0 or, among those with positive WTP, the dollar amount. Overall, the predicted WTP > \\$0 for conservative Republicans was 68.0% in the control condition versus 71.3% in the Trump cue, and the predicted amount conditional on paying something was \\$14.10 versus \\$14.41. \n \nLooking to renewables, liberal Democrats were willing to pay \\$5.70 more, on average, and for those in the climate condition the amount increased further by \\$3.14 (*p* = 0.148), for a total predicted willingness to pay of \\$25.90 for renewables. Conservative Republicans, however, were willing to pay \\$6.62 less for renewables, for a predicted total of \\$12.04.\n\nOverall, a Trump cue made conservative Republicans more supportive of fossil fuels and a climate cue made liberal Democrats more supportive of renewables. However, respondents were, on average, more supportive of renewables in terms of both priority and WTP. Even conservative Republicans in the Trump cue had a WTP higher for renewables, \\$10.87, than fossil fuels, at \\$10.28.\n\nComparing the results to the expectations, the support is mixed. As expected, political beliefs shaped both preferences and WTP. Conservative Republicans prioritized fossil fuels more than those with other political beliefs, were more likely to have any positive WTP for fossil fuels, and were WTP less for renewables. Liberal Democrats, in contrast, prioritized renewables, were less likely to have any positive WTP for fossil fuels, and were WTP more for renewables. However, among those WTP something for fossil fuels, conservative Republicans were not WTP more than others. The expectation that the cues would shift preferences and WTP in general was not supported, as neither the Trump cue nor the climate cue significantly changed energy priority or WTP for either source compared to the control condition. Finally, the expectation that the effects of the cues would depend on political beliefs received partial support. Conservative Republicans in the Trump cue shifted their priority toward fossil fuels (*p* = 0.062) and liberal Democrats in the climate cue shifted their priority toward renewables (*p* = 0.051), though both interactions were only marginally significant, at *p*<0.10. Yet, these shifts did not carry over to WTP, as none of the interactions between the cues and political beliefs significantly predicted WTP for fossil fuels or renewables. These results suggest that cues are likely more effective at moving the priority the public gives to energy sources than the amount they are willing to pay.\n\n# Discussion and Conclusion\n\nA clean energy transition is needed to mitigate climate change, and public support is needed for the energy transition. However, President Trump's rhetoric and actions on energy may serve to polarize the public. This study examined how exposure to a Trump cue or a climate change cue shapes the US public's prioritization of, and willingness-to-pay for, fossil fuel versus renewable electricity, and how these responses are shaped by political beliefs. The results show that support for energy sources is polarized along partisan lines, both in how respondents prioritized fossil fuels against renewables and in the dollar amounts they were willing to pay, and that a Trump cue pushed conservative Republicans further toward fossil fuels while a climate cue pushed liberal Democrats further toward renewables. However, respondents were, on average, more supportive of renewables than fossil fuels on both measures, and even conservative Republicans exposed to the Trump cue reported a higher WTP for renewables than for fossil fuels. Together, these findings suggest that cues may further exacerbate existing partisan divisions. \n\nThe cue effects were also uneven across the two outcomes. Political beliefs conditioned the effect of the cues on prioritization, but not on WTP. For example, the Trump cue did not significantly change WTP for fossil fuels among conservative Republicans. This may be because a single cue is a weaker treatment than the sustained rhetoric respondents may encounter. In addition, a cue about a political figure may be too diffuse to move WTP, especially in times of concern about rising energy costs.^[I ran a robustness check that included a measure of the respondent's concern about the cost of energy. The results are similar to what is reported here, and are shown in the supplemental material.] The climate cue, by contrast, was associated with a larger, though not statistically significant, increase in WTP for renewables among liberal Democrats, consistent with the idea that a cue tied to a scientific rationale for renewables resonates most with those already predisposed toward that position.\n\nThese results carry several implications for climate and energy policy. First, respondents across the political spectrum reported some positive WTP for renewables, and even conservative Republicans exposed to the Trump cue were WTP more for renewables than for fossil fuels. This suggests that renewable energy investment likely has general public support even in a polarized environment. Second, the responsiveness of conservative Republicans and liberal Democrats to identity-congruent cues indicates that elite rhetoric, including rhetoric tied to a single prominent figure, has the capacity to widen the partisan gap in energy preferences further, which is a risk for policymakers seeking durable, bipartisan support for energy policy. Third, because the cues shifted prioritization among conservative Republicans and liberal Democrats rather than the sample overall, and did not shift WTP, messaging strategies aimed at building broad coalitions for the energy transition likely benefit from emphasizing shared, cross-partisan benefits of renewables, such as reliability or local economic development, rather than frames tied to a specific political figure or to climate change.\n\nThis study has some limitations. The WTP measure relies on a hypothetical, stated-preference elicitation, and stated WTP does not always translate into WTP once a real price change is introduced. The cues were also each delivered once, in a single survey context, and their effects may not persist or generalize to the repeated, cumulative exposure people experience outside of a survey. Future research should examine whether repeated exposure to partisan cues over time widens the WTP gap identified here, and whether the gap closes when respondents are asked to pay the stated amount rather than simply report it.\n\n\\newpage\n\n# References",
    "supporting": [
      "cue-WTP_files/figure-html"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}