<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.9.38">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Matthew C. Nowlin">
<meta name="keywords" content="willingness-to-pay, partisan cues, renewable energy, fossil fuels, survey experiment">

<title>Cues, Partisanship, and Willingness-to-Pay for Energy</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for citations */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
}
.hanging-indent div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}</style>


<script src="cue-WTP_files/libs/clipboard/clipboard.min.js"></script>
<script src="cue-WTP_files/libs/quarto-html/quarto.js" type="module"></script>
<script src="cue-WTP_files/libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="cue-WTP_files/libs/quarto-html/popper.min.js"></script>
<script src="cue-WTP_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="cue-WTP_files/libs/quarto-html/anchor.min.js"></script>
<link href="cue-WTP_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="cue-WTP_files/libs/quarto-html/quarto-syntax-highlighting-15634bcf2e68342d4ad2dfa704d543f6.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="cue-WTP_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="cue-WTP_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="cue-WTP_files/libs/bootstrap/bootstrap-138a6193a3bd40baf1e627da441a4734.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script defer="" src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body class="quarto-light">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">
<div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
<div class="quarto-alternate-formats"><h2>Other Formats</h2><ul><li><a href="cue-WTP.pdf"><i class="bi bi-file-pdf"></i>PDF</a></li><li><a href="cue-WTP.docx"><i class="bi bi-file-word"></i>MS Word</a></li></ul></div></div>
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Cues, Partisanship, and Willingness-to-Pay for Energy</h1>
</div>


<div class="quarto-title-meta-author">
  <div class="quarto-title-meta-heading">Author</div>
  <div class="quarto-title-meta-heading">Affiliation</div>

    <div class="quarto-title-meta-contents">
    <p class="author">Matthew C. Nowlin <a href="mailto:matthew.nowlin@uta.edu" class="quarto-title-author-email"><i class="bi bi-envelope"></i></a> </p>
  </div>
  <div class="quarto-title-meta-contents">
        <p class="affiliation">
            Department of Political Science, University of Texas at Arlington
          </p>
      </div>
  </div>

<div class="quarto-title-meta">

    
  
  
  </div>

<div>
  <div class="abstract">
    <div class="block-title">Abstract</div>
    <p>The second Trump administration has promoted fossil fuels and criticized renewable energy, which may serve as a partisan cue that further polarizes the US public on energy. Using a survey experiment with a quota-based sample of US residents (N = 3,113), I examine how a Trump cue and a climate change cue shape how the public prioritizes fossil fuels versus renewables, as well as their willingness-to-pay (WTP) for each source measured with the Gabor-Granger method. Political beliefs strongly predicted both outcomes, as conservative Republicans prioritized fossil fuels and were WTP less for renewables, whereas liberal Democrats prioritized renewables and were WTP more for them. Neither cue had an average effect on priority or WTP. There is some evidence that the Trump cue moved conservative Republicans toward fossil fuels and the climate cue moved liberal Democrats toward renewables on the priority scale, though these interactions were only marginally significant. The cues did not reliably shift WTP for either source. The results suggest that cues are more likely to move costless expressions of energy preferences than the amount the public states it is willing to pay.</p>
  </div>
</div>

<div>
  <div class="keywords">
    <div class="block-title">Keywords</div>
    <p>willingness-to-pay, partisan cues, renewable energy, fossil fuels, survey experiment</p>
  </div>
</div>

</header>


<!-- intended outlet is Energy Policy. 8000 word limit -->
<section id="introduction" class="level1">
<h1>Introduction</h1>
<p>Shifting from fossil fuel sources of energy to renewables is needed to mitigate climate change. Yet, such a shift requires the commitment and support of the public. In general, the US public seems to support using more renewable sources, yet there are partisan differences in the degree of that support with Republicans tending to be more supportive of fossil fuels and Democrats tending to be more supportive of renewables <span class="citation" data-cites="bergquistEnergyPolicyPublic2020 hamiltonChangeWindUS2018 hawesClimateSciencePolitics2022">(<a href="#ref-bergquistEnergyPolicyPublic2020" role="doc-biblioref">Bergquist, Konisky, and Kotcher 2020</a>; <a href="#ref-hamiltonChangeWindUS2018" role="doc-biblioref">Hamilton et al. 2018</a>; <a href="#ref-hawesClimateSciencePolitics2022" role="doc-biblioref">Hawes and Nowlin 2022</a>)</span>. Additionally, in the last several years, Republicans have become more supportive of fossil fuels and less supportive of renewables <span class="citation" data-cites="kennedyAmericansShiftingViews2026">(<a href="#ref-kennedyAmericansShiftingViews2026" role="doc-biblioref">Kennedy and Kikuchi 2026</a>)</span>. Finally, the rhetoric and actions of President Trump since beginning his second term have focused on expanding fossil fuels and reducing renewables. Such actions by such a divisive political actor can serve as a partisan cue for the public.</p>
<p>Cues have been shown to inform public opinion on climate change and energy preferences. For example, partisan and elite cues played a significant role in shaping opinion on climate change <span class="citation" data-cites="merkleyPartyCuesNews2021 teslerEliteDominationPublic2018">(<a href="#ref-merkleyPartyCuesNews2021" role="doc-biblioref">Merkley and Stecula 2021</a>; <a href="#ref-teslerEliteDominationPublic2018" role="doc-biblioref">Tesler 2018</a>)</span>, and a climate change cue, or frame, can influence energy preferences <span class="citation" data-cites="feldmanClimateChangePolarizing2018">(<a href="#ref-feldmanClimateChangePolarizing2018" role="doc-biblioref">Feldman and Hart 2018</a>)</span>. Given the emphases of the second Trump administration regarding fossil fuels and renewables, it is possible that polarization among the public on energy sources may increase in response. In this paper, I explore how exposure to a Trump or climate cue, compared to an unattributed argument for fossil fuels, influences how the US public prioritizes fossil fuels versus renewables as well as their willingness-to-pay (WTP) for those energy sources.</p>
<p>As noted, the public is responsive to cues when forming their views on energy issues; however, less is known about how cues may impact the WTP of the public. The closest work, by <span class="citation" data-cites="benegalCostSensitivityPartisan2024">Benegal and Green (<a href="#ref-benegalCostSensitivityPartisan2024" role="doc-biblioref">2024</a>)</span>, found that partisan cue-taking outweighed sensitivity to cost in support for the Green New Deal, yet the outcome in that study was support for a policy with a stated cost rather than the amount respondents would add to their own electricity bill for a specific energy source. Additionally, few studies compare the effect of a cue on a costless expression of preference, such as how energy sources should be prioritized, with its effect on a costly one, such as WTP, among the same respondents. In brief, the literature on WTP for energy finds that the public is responsive to price volatility for both fossil fuels and renewables <span class="citation" data-cites="cardellaPriceVolatilityResidential2017">(<a href="#ref-cardellaPriceVolatilityResidential2017" role="doc-biblioref">Cardella, Ewing, and Williams 2017</a>)</span>, but in general are willing to pay more for renewable sources <span class="citation" data-cites="borchersDoesWillingnessPay2007 nkansahWillingnessPayWind2019">(<a href="#ref-borchersDoesWillingnessPay2007" role="doc-biblioref">Borchers, Duke, and Parsons 2007</a>; <a href="#ref-nkansahWillingnessPayWind2019" role="doc-biblioref">Nkansah and Collins 2019</a>)</span> and is WTP for research and development by the federal government aimed at reducing the use of fossil fuels <span class="citation" data-cites="liPublicSupportReducing2009">(<a href="#ref-liPublicSupportReducing2009" role="doc-biblioref">Li et al. 2009</a>)</span>. However, concern about the environmental impacts of energy <span class="citation" data-cites="knappWillConsumersReally2020">(<a href="#ref-knappWillConsumersReally2020" role="doc-biblioref">Knapp et al. 2020</a>)</span> and political beliefs <span class="citation" data-cites="aldyWillingnessPayPolitical2012">(<a href="#ref-aldyWillingnessPayPolitical2012" role="doc-biblioref">Aldy, Kotchen, and Leiserowitz 2012</a>)</span> can shape the WTP for energy.</p>
<p>In this study, I expand on current research by testing the impacts of a Trump cue versus a climate change cue on the prioritization of and WTP for fossil fuels and renewable sources of energy. Overall, I find that political beliefs shape energy source prioritization as conservative Republicans tend to prioritize and have a higher WTP for fossil fuels and liberal Democrats prioritize and have a higher WTP for renewables. Neither cue had an average effect on either outcome. There is some evidence that conservative Republicans in the Trump cue prioritize fossil fuels more, and liberal Democrats in the climate cue prioritize renewables more, though these interactions are only marginally significant and do not hold after adjusting for multiple comparisons. Finally, the cues did not reliably shift WTP for either energy source, which suggests that cues are more likely to move costless expressions of preference than costly ones.</p>
</section>
<section id="cues-public-opinion-and-the-publics-willingness-to-pay-for-energy" class="level1">
<h1>Cues, Public Opinion, and the Public’s Willingness-to-Pay for Energy</h1>
<p>Partisan and elite cues shape public opinion on climate and energy issues, as the public tends to adopt the positions associated with their political party <span class="citation" data-cites="merkleyPartyCuesNews2021 teslerEliteDominationPublic2018 ehretPartisanBarriersBipartisanship2018">(<a href="#ref-ehretPartisanBarriersBipartisanship2018" role="doc-biblioref">Ehret, Van Boven, and Sherman 2018</a>; <a href="#ref-merkleyPartyCuesNews2021" role="doc-biblioref">Merkley and Stecula 2021</a>; <a href="#ref-teslerEliteDominationPublic2018" role="doc-biblioref">Tesler 2018</a>)</span>. Cues provide an information heuristic, or shortcut, that allows the public to form opinions regarding a host of issues. Additionally, cues provide guides for motivated reasoning, as individuals apply reasoning in service to matching their views with those of their preferred party. Such motivated reasoning has been found in energy policy specifically. <span class="citation" data-cites="bolsenInfluencePartisanMotivated2014">Bolsen, Druckman, and Cook (<a href="#ref-bolsenInfluencePartisanMotivated2014" role="doc-biblioref">2014</a>)</span> found that party endorsements of an energy law led partisans to support the law when their party endorsed it and to oppose it when the other party did, and <span class="citation" data-cites="druckmanHowElitePartisan2013">Druckman, Peterson, and Slothuus (<a href="#ref-druckmanHowElitePartisan2013" role="doc-biblioref">2013</a>)</span> found, in experiments on drilling and immigration, that elite polarization intensifies the influence of party endorsements on opinion. Given the polarized elite environment surrounding energy, a cue tied to President Trump is likely to be a strong signal to partisans of both parties. Apart from partisan cues, connecting energy policies to the polarized issue of climate change can also shape and polarize public opinion. For example, <span class="citation" data-cites="feldmanClimateChangePolarizing2018">Feldman and Hart (<a href="#ref-feldmanClimateChangePolarizing2018" role="doc-biblioref">2018</a>)</span> found that framing a low-carbon energy policy as a climate change solution, rather than as an air pollution or energy security measure, reduced support for that policy among Republicans.</p>
<p>In addition to beliefs and attitudes, partisanship is also likely to influence an individual’s WTP. For example, conservatives were less likely to purchase an energy-efficient light bulb when it was labeled with an environmental message, as opposed to no label <span class="citation" data-cites="grometPoliticalIdeologyAffects2013">(<a href="#ref-grometPoliticalIdeologyAffects2013" role="doc-biblioref">Gromet, Kunreuther, and Larrick 2013</a>)</span>. A larger number of studies have examined stated WTP and political beliefs. <span class="citation" data-cites="kotchenWillingnesstoPayPolicyInstrumentChoice2013">Kotchen, Boyle, and Leiserowitz (<a href="#ref-kotchenWillingnesstoPayPolicyInstrumentChoice2013" role="doc-biblioref">2013</a>)</span> found that Republicans reported lower WTP for a national climate policy than Democrats and independents, but that this partisan gap was largely explained by differences in beliefs about whether climate change is occurring. Using a similar national WTP measure, <span class="citation" data-cites="kotchenPublicWillingnessPay2017">Kotchen, Turk, and Leiserowitz (<a href="#ref-kotchenPublicWillingnessPay2017" role="doc-biblioref">2017</a>)</span> estimated an average household WTP of $177 per year for a carbon tax, with respondents favoring that the revenue be spent on clean energy investment over other uses. More recently, <span class="citation" data-cites="benegalCostSensitivityPartisan2024">Benegal and Green (<a href="#ref-benegalCostSensitivityPartisan2024" role="doc-biblioref">2024</a>)</span> found that partisan cue-taking, where respondents supported policies proposed by their party, outweighed sensitivity to the policy’s stated cost. <span class="citation" data-cites="scheuchVotersSupportAre2026">Scheuch (<a href="#ref-scheuchVotersSupportAre2026" role="doc-biblioref">2026</a>)</span> also found partisanship to be a significant predictor of WTP for local climate policy, alongside age and income. Overall, political beliefs seem to influence not just abstract support for climate and energy policy, but the dollar amounts people state that they are willing to pay.</p>
<p>Yet, the influence of cues may differ between costless and costly expressions of preference. Stating how energy sources should be prioritized costs a respondent nothing, so agreeing with a trusted source or disagreeing with a disliked one is easy. Indeed, research on expressive responding has found that partisan differences in survey responses shrink when respondents are given an incentive to answer accurately, which suggests that some partisan responses are an expression of support for one’s party rather than a sincere belief <span class="citation" data-cites="bullockPartisanBiasFactual2015 priorYouCannotBe2015a">(<a href="#ref-bullockPartisanBiasFactual2015" role="doc-biblioref">Bullock et al. 2015</a>; <a href="#ref-priorYouCannotBe2015a" role="doc-biblioref">Prior, Sood, and Khanna 2015</a>)</span>. Stating a WTP, in contrast, asks respondents to consider a cost to their own household. A cue may therefore move how respondents prioritize energy sources without moving the amount they are willing to pay, as the cost of following the cue becomes concrete. However, <span class="citation" data-cites="benegalCostSensitivityPartisan2024">Benegal and Green (<a href="#ref-benegalCostSensitivityPartisan2024" role="doc-biblioref">2024</a>)</span> found that partisan cue-taking can outweigh cost sensitivity, so whether cue effects carry over from priority to WTP is an open question.</p>
<p>Looking to work that specifically examines public WTP for renewables and fossil fuels, several studies have found that the public is WTP more for renewables than other sources of energy. For example, <span class="citation" data-cites="nkansahWillingnessPayWind2019">Nkansah and Collins (<a href="#ref-nkansahWillingnessPayWind2019" role="doc-biblioref">2019</a>)</span> compared WTP for wind against natural gas generation specifically and found consumers willing to pay more for wind. Along similar lines, <span class="citation" data-cites="murakamiConsumersWillingnessPay2015">Murakami et al. (<a href="#ref-murakamiConsumersWillingnessPay2015" role="doc-biblioref">2015</a>)</span> placed fossil fuels, renewables, and nuclear power on the same WTP scale in the US and Japan, and found that respondents in both countries expressed positive WTP for increased renewable generation but negative WTP for increased nuclear generation, with US respondents expressing a stronger preference for renewables than Japanese respondents. However, <span class="citation" data-cites="walterExaminingWillingnessPay2023">Walter, Thacher, and Chermak (<a href="#ref-walterExaminingWillingnessPay2023" role="doc-biblioref">2023</a>)</span> found that US respondents’ preferences over fossil versus renewable energy futures depended on their geographic proximity to fossil fuel production and their opinion about anthropogenic climate change. Finally, <span class="citation" data-cites="liPublicSupportReducing2009">Li et al. (<a href="#ref-liPublicSupportReducing2009" role="doc-biblioref">2009</a>)</span> estimated household WTP for a federal energy research and development fund aimed at reducing reliance on fossil fuels, and found broad support for that funding, suggesting that WTP responds to reducing fossil fuel use on its own without reference to another energy source. <a href="#fn1" class="footnote-ref" id="fnref1" role="doc-noteref"><sup>1</sup></a></p>
<section id="theoretical-expectations" class="level2">
<h2 class="anchored" data-anchor-id="theoretical-expectations">Theoretical Expectations</h2>
<p>Previous research suggests that partisan cues are an important driver of energy preferences and that partisanship and environmental beliefs shape the WTP for energy sources. In this study, I use a survey experiment to examine the influence of a Trump cue and a climate change cue on preferences and the stated WTP for fossil fuels versus renewables.</p>
<p>The experiment includes three conditions, and each is designed to manipulate something different. All respondents see an argument that renewables are not reliable and that fossil fuels are needed for energy security. In the baseline condition the argument is attributed to “some,” so the baseline is an unattributed argument for fossil fuels rather than the absence of a message. In the Trump condition the same argument is attributed to President Trump, so the comparison with the baseline isolates the effect of a partisan source cue. In the climate condition the unattributed argument is followed by a statement that scientists have warned that fossil fuels will make climate change worse and that renewables should be increased. The climate condition therefore combines a scientific source, a climate change frame, and a counterargument, and its comparison with the baseline captures the effect of that combined message. Because the two cue conditions differ from the baseline in different ways, I compare each cue with the baseline rather than comparing the size of the two cue effects with each other.</p>
<p>Based on the research discussed above, I posit the following hypotheses.</p>
<blockquote class="blockquote">
<p>H1a: Conservative Republicans will prioritize fossil fuels and be WTP more for fossil fuels than those with other political beliefs.</p>
</blockquote>
<blockquote class="blockquote">
<p>H1b: Liberal Democrats will prioritize renewables and be WTP more for renewables than those with other political beliefs.</p>
</blockquote>
<blockquote class="blockquote">
<p>H2a: Those who receive the Trump cue will prioritize fossil fuels and be WTP more for fossil fuels than those in the baseline condition.</p>
</blockquote>
<blockquote class="blockquote">
<p>H2b: Those who receive the climate cue will prioritize renewables and be WTP more for renewables than those in the baseline condition.</p>
</blockquote>
<blockquote class="blockquote">
<p>H3a: The effect of the Trump cue on prioritizing and WTP for fossil fuels will be larger among conservative Republicans than among those with other political beliefs.</p>
</blockquote>
<blockquote class="blockquote">
<p>H3b: The effect of the climate cue on prioritizing and WTP for renewables will be larger among liberal Democrats than among those with other political beliefs.</p>
</blockquote>
<p>In addition, I examine two research questions. First, cues from a disliked source may lead partisans to move away from the position of that source <span class="citation" data-cites="feldmanClimateChangePolarizing2018">(<a href="#ref-feldmanClimateChangePolarizing2018" role="doc-biblioref">Feldman and Hart 2018</a>)</span>, so I ask whether liberal Democrats move toward renewables in response to the Trump cue and whether conservative Republicans move toward fossil fuels in response to the climate cue (RQ1). Second, given the difference between costless and costly expressions of preference, I ask whether the effects of the cues on prioritization carry over to WTP (RQ2).</p>
</section>
</section>
<section id="data-and-measures" class="level1">
<h1>Data and Measures</h1>
<p>To examine the importance of cues and political beliefs in energy preferences I use a survey experiment to examine respondents’ prioritization of fossil fuels versus renewables as well as their WTP for those sources to generate electricity in response to a Trump cue or a climate change cue. Respondents were recruited using Cloud Research, which provides a quota-based sample of US residents, with quotas for age, race, and gender based on US Census data. Additionally, to further ensure as representative a sample as possible, I used the <code>survey</code> and <code>anesrake</code> packages in <code>R</code> to perform iterative raking to compute survey weights that weight respondents based on the US Census’s 2023 American Community Survey (ACS) on demographic variables, including age, race, gender, and education. I also used the Pew Research Center’s National Public Opinion Reference Survey (NPORS) from 2025 to weight the sample based on political party affiliation. With leaners assigned to a party, the NPORS targets were 45 percent Democratic, 46 percent Republican, and 9 percent identifying with neither party. I surveyed 3113 US residents in April 2026, who were randomly assigned to receive one of three treatments, including a cue about Trump’s critiques of renewable energy and his support for fossil fuels (n = 1049), a climate change cue that stated scientists recommend moving away from fossil fuels to renewables to address climate change (n = 1013), or a baseline condition in which the argument for fossil fuels was attributed to “some” (n = 1051).<a href="#fn2" class="footnote-ref" id="fnref2" role="doc-noteref"><sup>2</sup></a></p>
<p>All respondents were shown the following paragraph:</p>
<blockquote class="blockquote">
<p>The use of renewable energy sources for electricity, including wind energy, solar energy, and battery storage, has risen sharply in recent years. Indeed, most of the growth in new electricity generation in the U.S. has come from renewable sources.</p>
</blockquote>
<p>Respondents were then shown the following statement. Those in the Trump cue saw President Trump named specifically, while those in the climate cue and the baseline were shown <em>some have</em></p>
<blockquote class="blockquote">
<p>However, [<em>President Trump has</em>/<em>some have</em>] argued that renewable sources are not reliable and that we need to increase our reliance on fossil fuels (coal, oil, and natural gas) to ensure energy security.</p>
</blockquote>
<p>Those in the climate cue saw the following:</p>
<blockquote class="blockquote">
<p>Additionally, scientists have warned that an increase in the use of fossil fuels will make climate change worse; therefore, we should increase our use of renewable sources.</p>
</blockquote>
<p>Finally, all respondents were shown:</p>
<blockquote class="blockquote">
<p>Please consider how you think we should prioritize the development of fossil fuels and renewable sources to generate electricity.</p>
</blockquote>
<p>After receiving the cues, respondents were asked, on a 1 to 7 scale, if fossil fuels should be prioritized (= 1), fossil fuels and renewables should be prioritized equally (= 4), or renewable sources should be prioritized (= 7). Next, I asked respondents their willingness-to-pay (WTP) for fossil fuel and renewable sources using the Gabor-Granger method <span class="citation" data-cites="gaborPriceIndicatorQuality1966">(<a href="#ref-gaborPriceIndicatorQuality1966" role="doc-biblioref">Gabor and Granger 1966</a>)</span>. With the Gabor-Granger method, respondents are shown a random dollar amount and if they are willing to pay that amount, they are next shown a higher amount, and if they are not, they are shown a smaller amount. This approach is a well-established survey-based technique for estimating WTP. It dates to early applications of iterative-bidding price experiments <span class="citation" data-cites="jonesSurveyTechniqueMeasure1975">(<a href="#ref-jonesSurveyTechniqueMeasure1975" role="doc-biblioref">Jones 1975</a>)</span> and was later formalized in marketing research <span class="citation" data-cites="wedelModelEffectsPsychological1998">(<a href="#ref-wedelModelEffectsPsychological1998" role="doc-biblioref">Wedel and Leeflang 1998</a>)</span>. It remains one of the standard indirect approaches used to measure WTP <span class="citation" data-cites="lipovetskyPricingModelsMarketing2011 breidertReviewMethodsMeasuring2006">(<a href="#ref-breidertReviewMethodsMeasuring2006" role="doc-biblioref">Breidert, Hahsler, and Reutterer 2006</a>; <a href="#ref-lipovetskyPricingModelsMarketing2011" role="doc-biblioref">Lipovetsky, Magnan, and Zanetti-Polzi 2011</a>)</span>.</p>
<p>To establish WTP, I first give respondents information about potential costs associated with each energy source, and the sources were presented in random order. The prompts were written to give respondents a plausible reason that increasing the use of each source would raise their electricity bill. In the WTP for fossil fuels question, I noted that costs associated with renewable energy have decreased and, therefore they may need to pay more to use fossil fuels. For renewable sources respondents were told about the need to increase distribution. Specifically, respondents were shown the following prompts for fossil fuels and renewables, respectively.</p>
<blockquote class="blockquote">
<p>The cost of generating electricity from renewable sources has decreased in recent years. In many places, renewable energy sources are often more cost-effective than fossil fuels. Would you support the increased use of fossil fuels if your electricity bill were to increase by the following each month?</p>
</blockquote>
<blockquote class="blockquote">
<p>Renewable sources have become cheaper in recent years; however, investments are needed to distribute the electricity they produce to homes and businesses. Would you support the increased use of renewable sources if your electricity bill were to increase by the following each month?</p>
</blockquote>
<p>The two prompts are not symmetric. The fossil fuel prompt notes that renewables are often more cost-effective than fossil fuels, which likely gives respondents a reason not to pay more for fossil fuels, whereas the renewables prompt does not include a comparable reason not to pay for renewables. As a result, the difference between WTP for fossil fuels and WTP for renewables likely reflects the wording of the prompts as well as respondents’ preferences, and should be interpreted with caution. However, the wording of each prompt was the same in every condition, so the comparison of each cue with the baseline within each energy source is not affected by the asymmetry.</p>
<p>To estimate the maximum/minimum WTP, respondents were first shown a random dollar amount between $1 and $46, in five-dollar increments, and asked if they would be WTP that amount extra per-month in their electricity bill. If they indicated yes they were shown a larger, random dollar-amount, and if they indicated no they were shown a smaller dollar-amount. This continues until they reach the $46-maximum or $1-minimum. Each respondent’s WTP is the highest amount they accepted, and respondents who indicated no at $1 were coded with a WTP of 0. The starting and follow-up amounts were drawn at random, independently of the cue condition, but were not recorded. As such, I cannot control for the starting amount, which may anchor responses, though random assignment of the starting amount means anchoring is unlikely to differ across conditions.</p>
<p>In the following analysis, I examine the prioritization of fossil fuels vs.&nbsp;renewables and the WTP for those energy sources as a function of the cues and political beliefs. Political beliefs include conservative Republicans and liberal Democrats, with other political beliefs (moderates of either party, conservative Democrats, liberal Republicans, and those who identify with neither party) as the excluded referents. The political belief measures were constructed based on responses to a self-reported, 7-point ideology scale (1 = strongly liberal, 2 = liberal, 3 = slightly liberal, 4 = middle of the road, 5 = slightly conservative, 6 = conservative, 7 = strongly conservative) and political party identification. Respondents who identified as independent or with another party were asked whether they lean toward the Democratic or Republican Party, and those who lean toward a party are coded as identifying with that party. Before leaners are assigned, 34 percent of respondents identified as independent or with another party, and after leaners are assigned, only 15 percent identified with neither party. Conservative Republican is coded 1 for respondents who identify as Republican and place themselves at 5, 6, or 7 on the ideology scale (slightly conservative, conservative, or strongly conservative), and liberal Democrat is coded 1 for respondents who identify as Democrat and place themselves at 1, 2, or 3 (strongly liberal, liberal, or slightly liberal). Party identification and ideology were measured after the outcome questions, so the cues could, in principle, have shifted how respondents identified. However, the distribution of political beliefs did not differ across conditions (<span class="math inline">\(\chi^2\)</span> = 5.20, <em>df</em> = 4, <em>p</em> = 0.268).</p>
<div class="cell">
<div id="tbl-descriptives" class="cell quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-descriptives-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;1: Descriptive statistics for the energy-priority scale, willingness-to-pay, and political belief measures (survey-weighted means and standard deviations, overall and survey-weighted means by condition)
</figcaption>
<div aria-describedby="tbl-descriptives-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<table class="cell caption-top table table-sm table-striped small">
<colgroup>
<col style="width: 35%">
<col style="width: 7%">
<col style="width: 7%">
<col style="width: 5%">
<col style="width: 5%">
<col style="width: 11%">
<col style="width: 12%">
<col style="width: 15%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Variable</th>
<th style="text-align: right;">Mean</th>
<th style="text-align: right;">SD</th>
<th style="text-align: right;">Min</th>
<th style="text-align: right;">Max</th>
<th style="text-align: right;">Baseline</th>
<th style="text-align: right;">Trump cue</th>
<th style="text-align: right;">Climate cue</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Energy-priority scale (1-7)</td>
<td style="text-align: right;">5.17</td>
<td style="text-align: right;">1.74</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">7</td>
<td style="text-align: right;">5.17</td>
<td style="text-align: right;">5.15</td>
<td style="text-align: right;">5.20</td>
</tr>
<tr class="even">
<td style="text-align: left;">WTP, fossil fuels (<span class="math inline">\()       |  8.33| 13.79|   0|  46|     8.55|      7.54|        8.86|
|WTP, renewables (\)</span>)</td>
<td style="text-align: right;">18.21</td>
<td style="text-align: right;">17.43</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">46</td>
<td style="text-align: right;">17.95</td>
<td style="text-align: right;">17.85</td>
<td style="text-align: right;">18.80</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Liberal Democrat</td>
<td style="text-align: right;">0.37</td>
<td style="text-align: right;">0.48</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">0.35</td>
<td style="text-align: right;">0.40</td>
<td style="text-align: right;">0.37</td>
</tr>
<tr class="even">
<td style="text-align: left;">Conservative Republican</td>
<td style="text-align: right;">0.40</td>
<td style="text-align: right;">0.49</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">0.41</td>
<td style="text-align: right;">0.36</td>
<td style="text-align: right;">0.42</td>
</tr>
</tbody>
</table>
</div>
</div>
</figure>
</div>
</div>
<p>Descriptive statistics for the energy-priority scale and the political belief measures are shown in <a href="#tbl-descriptives" class="quarto-xref">Table&nbsp;1</a>. The mean on the energy-priority scale was 5.17 (SD = 1.74), which is above the midpoint of 4 and indicates that respondents, on average, leaned toward prioritizing renewables over fossil fuels. Regarding political beliefs, 37 percent of the weighted sample were liberal Democrats and 40 percent were conservative Republicans, with the remaining 23 percent holding other political beliefs. These shares reflect the survey weights, which weight the sample to the party affiliation distribution in the NPORS. Unweighted, 48 percent of respondents were liberal Democrats and 24 percent were conservative Republicans, so the weights roughly double the share of conservative Republicans. To account for this, I also estimate each model without the weights, and those models are shown in the supplemental material.</p>
</section>
<section id="results" class="level1">
<h1>Results</h1>
<p>First, I use OLS to examine the prioritization respondents gave to fossil fuels versus renewables as a function of the cues, their political beliefs, and the interaction between cues and political beliefs. The results are shown in <a href="#tbl-priority-ols" class="quarto-xref">Table&nbsp;2</a>.</p>
<div class="cell">
<div id="tbl-priority-ols" class="cell quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-priority-ols-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;2: Effect of cue condition, political beliefs, and their interaction on the energy source-priority scale (survey-weighted OLS; baseline condition and other/moderate identity as reference)
</figcaption>
<div aria-describedby="tbl-priority-ols-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<!-- preamble start -->

    <script src="https://cdn.jsdelivr.net/gh/vincentarelbundock/tinytable@main/inst/tinytable.js"></script>

    <script>
      // Create table-specific functions using external factory
      const tableFns_tj3tlsk3uvtvht6pmu41 = TinyTable.createTableFunctions("tinytable_tj3tlsk3uvtvht6pmu41");
      // tinytable span after
      window.addEventListener('load', function () {
          var cellsToStyle = [
            // tinytable style arrays after
          { positions: [ { i: '20', j: 2 } ], css_id: 'tinytable_css_aewka90fcte25pgchwi2',}, 
          { positions: [ { i: '18', j: 2 } ], css_id: 'tinytable_css_l1jex5jx2bilia9m3g7a',}, 
          { positions: [ { i: '1', j: 2 }, { i: '2', j: 2 }, { i: '3', j: 2 }, { i: '4', j: 2 }, { i: '5', j: 2 }, { i: '6', j: 2 }, { i: '7', j: 2 }, { i: '8', j: 2 }, { i: '9', j: 2 }, { i: '10', j: 2 }, { i: '11', j: 2 }, { i: '12', j: 2 }, { i: '13', j: 2 }, { i: '14', j: 2 }, { i: '15', j: 2 }, { i: '16', j: 2 }, { i: '17', j: 2 }, { i: '19', j: 2 } ], css_id: 'tinytable_css_hjup0rn1y8fo9xf08jnm',}, 
          { positions: [ { i: '0', j: 2 } ], css_id: 'tinytable_css_oaxgoohihhxgglvcxpwy',}, 
          { positions: [ { i: '20', j: 1 } ], css_id: 'tinytable_css_dej1x6v0cjupkfn0t1xh',}, 
          { positions: [ { i: '18', j: 1 } ], css_id: 'tinytable_css_12o4rsrmula6rdfnuxbd',}, 
          { positions: [ { i: '1', j: 1 }, { i: '2', j: 1 }, { i: '3', j: 1 }, { i: '4', j: 1 }, { i: '5', j: 1 }, { i: '6', j: 1 }, { i: '7', j: 1 }, { i: '8', j: 1 }, { i: '9', j: 1 }, { i: '10', j: 1 }, { i: '11', j: 1 }, { i: '12', j: 1 }, { i: '13', j: 1 }, { i: '14', j: 1 }, { i: '15', j: 1 }, { i: '16', j: 1 }, { i: '17', j: 1 }, { i: '19', j: 1 } ], css_id: 'tinytable_css_i5hz4tqfvzze5dpa2izb',}, 
          { positions: [ { i: '0', j: 1 } ], css_id: 'tinytable_css_ttecqcomjkwcfe47o7es',}, 
          ];

          // Loop over the arrays to style the cells
          cellsToStyle.forEach(function (group) {
              group.positions.forEach(function (cell) {
                  tableFns_tj3tlsk3uvtvht6pmu41.styleCell(cell.i, cell.j, group.css_id);
              });
          });
      });
    </script>

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/gh/vincentarelbundock/tinytable@main/inst/tinytable.css">
    <style>
    /* tinytable css entries after */
    #tinytable_tj3tlsk3uvtvht6pmu41 td.tinytable_css_aewka90fcte25pgchwi2, #tinytable_tj3tlsk3uvtvht6pmu41 th.tinytable_css_aewka90fcte25pgchwi2 {  position: relative; --border-bottom: 1; --border-left: 0; --border-right: 0; --border-top: 0; --line-color-bottom: var(--tt-line-color); --line-color-left: var(--tt-line-color); --line-color-right: var(--tt-line-color); --line-color-top: var(--tt-line-color); --line-width-bottom: 0.08em; --line-width-left: 0.1em; --line-width-right: 0.1em; --line-width-top: 0.1em; --trim-bottom-left: 0%; --trim-bottom-right: 0%; --trim-left-bottom: 0%; --trim-left-top: 0%; --trim-right-bottom: 0%; --trim-right-top: 0%; --trim-top-left: 0%; --trim-top-right: 0%; ; text-align: center }
    #tinytable_tj3tlsk3uvtvht6pmu41 td.tinytable_css_l1jex5jx2bilia9m3g7a, #tinytable_tj3tlsk3uvtvht6pmu41 th.tinytable_css_l1jex5jx2bilia9m3g7a {  position: relative; --border-bottom: 1; --border-left: 0; --border-right: 0; --border-top: 0; --line-color-bottom: var(--tt-line-color); --line-color-left: var(--tt-line-color); --line-color-right: var(--tt-line-color); --line-color-top: var(--tt-line-color); --line-width-bottom: 0.05em; --line-width-left: 0.1em; --line-width-right: 0.1em; --line-width-top: 0.1em; --trim-bottom-left: 0%; --trim-bottom-right: 0%; --trim-left-bottom: 0%; --trim-left-top: 0%; --trim-right-bottom: 0%; --trim-right-top: 0%; --trim-top-left: 0%; --trim-top-right: 0%; ; text-align: center }
    #tinytable_tj3tlsk3uvtvht6pmu41 td.tinytable_css_hjup0rn1y8fo9xf08jnm, #tinytable_tj3tlsk3uvtvht6pmu41 th.tinytable_css_hjup0rn1y8fo9xf08jnm { text-align: center }
    #tinytable_tj3tlsk3uvtvht6pmu41 td.tinytable_css_oaxgoohihhxgglvcxpwy, #tinytable_tj3tlsk3uvtvht6pmu41 th.tinytable_css_oaxgoohihhxgglvcxpwy {  position: relative; --border-bottom: 1; --border-left: 0; --border-right: 0; --border-top: 1; --line-color-bottom: var(--tt-line-color); --line-color-left: var(--tt-line-color); --line-color-right: var(--tt-line-color); --line-color-top: var(--tt-line-color); --line-width-bottom: 0.05em; --line-width-left: 0.1em; --line-width-right: 0.1em; --line-width-top: 0.08em; --trim-bottom-left: 0%; --trim-bottom-right: 0%; --trim-left-bottom: 0%; --trim-left-top: 0%; --trim-right-bottom: 0%; --trim-right-top: 0%; --trim-top-left: 0%; --trim-top-right: 0%; ; text-align: center }
    #tinytable_tj3tlsk3uvtvht6pmu41 td.tinytable_css_dej1x6v0cjupkfn0t1xh, #tinytable_tj3tlsk3uvtvht6pmu41 th.tinytable_css_dej1x6v0cjupkfn0t1xh {  position: relative; --border-bottom: 1; --border-left: 0; --border-right: 0; --border-top: 0; --line-color-bottom: var(--tt-line-color); --line-color-left: var(--tt-line-color); --line-color-right: var(--tt-line-color); --line-color-top: var(--tt-line-color); --line-width-bottom: 0.08em; --line-width-left: 0.1em; --line-width-right: 0.1em; --line-width-top: 0.1em; --trim-bottom-left: 0%; --trim-bottom-right: 0%; --trim-left-bottom: 0%; --trim-left-top: 0%; --trim-right-bottom: 0%; --trim-right-top: 0%; --trim-top-left: 0%; --trim-top-right: 0%; ; text-align: left }
    #tinytable_tj3tlsk3uvtvht6pmu41 td.tinytable_css_12o4rsrmula6rdfnuxbd, #tinytable_tj3tlsk3uvtvht6pmu41 th.tinytable_css_12o4rsrmula6rdfnuxbd {  position: relative; --border-bottom: 1; --border-left: 0; --border-right: 0; --border-top: 0; --line-color-bottom: var(--tt-line-color); --line-color-left: var(--tt-line-color); --line-color-right: var(--tt-line-color); --line-color-top: var(--tt-line-color); --line-width-bottom: 0.05em; --line-width-left: 0.1em; --line-width-right: 0.1em; --line-width-top: 0.1em; --trim-bottom-left: 0%; --trim-bottom-right: 0%; --trim-left-bottom: 0%; --trim-left-top: 0%; --trim-right-bottom: 0%; --trim-right-top: 0%; --trim-top-left: 0%; --trim-top-right: 0%; ; text-align: left }
    #tinytable_tj3tlsk3uvtvht6pmu41 td.tinytable_css_i5hz4tqfvzze5dpa2izb, #tinytable_tj3tlsk3uvtvht6pmu41 th.tinytable_css_i5hz4tqfvzze5dpa2izb { text-align: left }
    #tinytable_tj3tlsk3uvtvht6pmu41 td.tinytable_css_ttecqcomjkwcfe47o7es, #tinytable_tj3tlsk3uvtvht6pmu41 th.tinytable_css_ttecqcomjkwcfe47o7es {  position: relative; --border-bottom: 1; --border-left: 0; --border-right: 0; --border-top: 1; --line-color-bottom: var(--tt-line-color); --line-color-left: var(--tt-line-color); --line-color-right: var(--tt-line-color); --line-color-top: var(--tt-line-color); --line-width-bottom: 0.05em; --line-width-left: 0.1em; --line-width-right: 0.1em; --line-width-top: 0.08em; --trim-bottom-left: 0%; --trim-bottom-right: 0%; --trim-left-bottom: 0%; --trim-left-top: 0%; --trim-right-bottom: 0%; --trim-right-top: 0%; --trim-top-left: 0%; --trim-top-right: 0%; ; text-align: left }
    </style>
    <div class="container">
      <table class="tinytable" id="tinytable_tj3tlsk3uvtvht6pmu41" style="width: auto; margin-left: auto; margin-right: auto;" data-quarto-disable-processing="true">
        
        <thead>
              <tr>
                <th scope="col" data-row="0" data-col="1"> </th>
                <th scope="col" data-row="0" data-col="2">Priority scale</th>
              </tr>
        </thead>
        <tfoot><tr><td colspan="2">† p &lt; 0.1, * p &lt; 0.05, ** p &lt; 0.01</td></tr></tfoot>
        <tbody>
                <tr>
                  <td data-row="1" data-col="1">Trump cue</td>
                  <td data-row="1" data-col="2">-0.016</td>
                </tr>
                <tr>
                  <td data-row="2" data-col="1"></td>
                  <td data-row="2" data-col="2">(0.159)</td>
                </tr>
                <tr>
                  <td data-row="3" data-col="1">Climate cue</td>
                  <td data-row="3" data-col="2">-0.137</td>
                </tr>
                <tr>
                  <td data-row="4" data-col="1"></td>
                  <td data-row="4" data-col="2">(0.153)</td>
                </tr>
                <tr>
                  <td data-row="5" data-col="1">Liberal Democrat</td>
                  <td data-row="5" data-col="2">0.674**</td>
                </tr>
                <tr>
                  <td data-row="6" data-col="1"></td>
                  <td data-row="6" data-col="2">(0.126)</td>
                </tr>
                <tr>
                  <td data-row="7" data-col="1">Conservative Republican</td>
                  <td data-row="7" data-col="2">-1.236**</td>
                </tr>
                <tr>
                  <td data-row="8" data-col="1"></td>
                  <td data-row="8" data-col="2">(0.150)</td>
                </tr>
                <tr>
                  <td data-row="9" data-col="1">Trump cue × Liberal Democrat</td>
                  <td data-row="9" data-col="2">0.137</td>
                </tr>
                <tr>
                  <td data-row="10" data-col="1"></td>
                  <td data-row="10" data-col="2">(0.184)</td>
                </tr>
                <tr>
                  <td data-row="11" data-col="1">Climate cue × Liberal Democrat</td>
                  <td data-row="11" data-col="2">0.341†</td>
                </tr>
                <tr>
                  <td data-row="12" data-col="1"></td>
                  <td data-row="12" data-col="2">(0.174)</td>
                </tr>
                <tr>
                  <td data-row="13" data-col="1">Trump cue × Conservative Republican</td>
                  <td data-row="13" data-col="2">-0.438†</td>
                </tr>
                <tr>
                  <td data-row="14" data-col="1"></td>
                  <td data-row="14" data-col="2">(0.235)</td>
                </tr>
                <tr>
                  <td data-row="15" data-col="1">Climate cue × Conservative Republican</td>
                  <td data-row="15" data-col="2">0.079</td>
                </tr>
                <tr>
                  <td data-row="16" data-col="1"></td>
                  <td data-row="16" data-col="2">(0.221)</td>
                </tr>
                <tr>
                  <td data-row="17" data-col="1">(Intercept)</td>
                  <td data-row="17" data-col="2">5.443**</td>
                </tr>
                <tr>
                  <td data-row="18" data-col="1"></td>
                  <td data-row="18" data-col="2">(0.109)</td>
                </tr>
                <tr>
                  <td data-row="19" data-col="1">Num.Obs.</td>
                  <td data-row="19" data-col="2">3113</td>
                </tr>
                <tr>
                  <td data-row="20" data-col="1">Adj. R2</td>
                  <td data-row="20" data-col="2">0.313</td>
                </tr>
        </tbody>
      </table>
    </div>
<!-- hack to avoid NA insertion in last line -->
</div>
</div>
</figure>
</div>
</div>
<div class="cell">
<div class="cell-output-display">
<div id="fig-priority-predicted" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-fig" id="fig-priority-predicted-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;1: Predicted energy source-priority scale (1-7) by cue condition and political identity (survey-weighted OLS predictions with 95% CIs)
</figcaption>
<div aria-describedby="fig-priority-predicted-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="cue-WTP_files/figure-html/fig-priority-predicted-1.png" class="img-fluid figure-img" width="672">
</div>
</figure>
</div>
</div>
</div>
<p>As expected, conservative Republicans were more likely to prioritize fossil fuels than renewables, with an estimated coefficient of -1.24 on the 1 to 7 scale, and liberal Democrats prioritized renewables at 0.67. In terms of the interactions, which test whether the effect of a cue differs by political beliefs, the Trump cue moved conservative Republicans toward fossil fuels more than it moved those with other political beliefs (b = -0.44, <em>p</em> = 0.062), and the climate cue moved liberal Democrats toward renewables more than those with other political beliefs (b = 0.34, <em>p</em> = 0.051). Both interactions are only marginally significant. Additionally, these are 16 cue x political belief interactions across the four models presented here, and neither interaction is significant after a Holm adjustment for multiple comparisons (adjusted <em>p</em> = 0.94 and 0.81, respectively). Descriptively, the predicted value on the 1 to 7 scale for conservative Republicans in the baseline condition was 4.21, indicating a split roughly evenly between fossil fuels and renewables, and it was 3.75 for those receiving the Trump cue (difference = -0.45, <em>p</em> = 0.009). For liberal Democrats the predicted value was 6.12 in the baseline condition, indicating a priority for renewables, and 6.32 in the climate condition (difference = 0.20, <em>p</em> = 0.015). Without the survey weights, the climate cue x liberal Democrat interaction is significant (<em>p</em> = 0.014), whereas the Trump cue x conservative Republican interaction is not (<em>p</em> = 0.144). In contrast to the interactions, there is no evidence that liberal Democrats moved toward renewables in response to the Trump cue or that conservative Republicans moved toward fossil fuels in response to the climate cue.</p>
<p>Because the models include interactions, the coefficients for the Trump and climate cues are the effects of the cues among those with other political beliefs only. To estimate the average effect of each cue, I also estimate models with the cues alone, shown in the supplemental material. Neither cue had a significant average effect on energy source priority compared to the baseline (Trump cue b = -0.03, <em>p</em> = 0.785; climate cue b = 0.03, <em>p</em> = 0.775).</p>
<p>Next, I examine the percent of respondents at each possible dollar amount of the WTP measure for each source. Those results are in <a href="#tbl-wtp-dist" class="quarto-xref">Table&nbsp;3</a>.</p>
<div class="cell">
<div id="tbl-wtp-dist" class="cell quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-wtp-dist-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;3: Distribution of willingness-to-pay for fossil fuel and renewable electricity (weighted percent of respondents choosing each dollar amount). Each value is the highest monthly amount the respondent accepted, so the respondent’s WTP is at least that amount and below the next amount they rejected; $0 indicates the respondent rejected $1, and $46 indicates the respondent accepted the highest amount offered.
</figcaption>
<div aria-describedby="tbl-wtp-dist-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<table class="cell caption-top table table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: right;">WTP ($)</th>
<th style="text-align: right;">Fossil fuels (%)</th>
<th style="text-align: right;">Renewables (%)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">0</td>
<td style="text-align: right;">47.0</td>
<td style="text-align: right;">14.0</td>
</tr>
<tr class="even">
<td style="text-align: right;">1</td>
<td style="text-align: right;">14.7</td>
<td style="text-align: right;">15.6</td>
</tr>
<tr class="odd">
<td style="text-align: right;">6</td>
<td style="text-align: right;">10.6</td>
<td style="text-align: right;">14.0</td>
</tr>
<tr class="even">
<td style="text-align: right;">11</td>
<td style="text-align: right;">5.6</td>
<td style="text-align: right;">9.1</td>
</tr>
<tr class="odd">
<td style="text-align: right;">16</td>
<td style="text-align: right;">4.9</td>
<td style="text-align: right;">7.3</td>
</tr>
<tr class="even">
<td style="text-align: right;">21</td>
<td style="text-align: right;">2.7</td>
<td style="text-align: right;">4.3</td>
</tr>
<tr class="odd">
<td style="text-align: right;">26</td>
<td style="text-align: right;">2.9</td>
<td style="text-align: right;">5.8</td>
</tr>
<tr class="even">
<td style="text-align: right;">31</td>
<td style="text-align: right;">1.2</td>
<td style="text-align: right;">3.2</td>
</tr>
<tr class="odd">
<td style="text-align: right;">36</td>
<td style="text-align: right;">2.1</td>
<td style="text-align: right;">4.7</td>
</tr>
<tr class="even">
<td style="text-align: right;">41</td>
<td style="text-align: right;">1.9</td>
<td style="text-align: right;">3.8</td>
</tr>
<tr class="odd">
<td style="text-align: right;">46</td>
<td style="text-align: right;">6.3</td>
<td style="text-align: right;">18.3</td>
</tr>
</tbody>
</table>
</div>
</div>
</figure>
</div>
</div>
<p>As shown, nearly half of respondents, 47 percent, were not willing to pay any additional amount for fossil fuels, whereas 18.3 percent were willing to pay the max, $46 for renewables. Overall, the median WTP for fossil fuels was $1 with a mean of $8.33. For renewables the median WTP was $11 and the mean was $18.21. Comparing the differences in median and means, the median difference in WTP for renewables versus fossil fuels was $10. For the mean, the difference was $9.88, which is significant based on a survey-weighted paired t-test (<em>t</em> = 22.9, <em>df</em> = 3111, <em>p</em> &lt; .001). However, because the fossil fuel prompt included a reason not to pay for fossil fuels, the size of this difference is likely overstated and should be interpreted with caution.</p>
<p>Given the large percentage of respondents with a WTP = $0 for fossil fuels, I model the WTP for fossil fuels in two parts. First, I use a logit model to see whether a respondent has any positive WTP. Next, using OLS, I examine the WTP for fossil fuels, among those who are WTP &gt;0, and for renewables. The results of all three models are shown in <a href="#tbl-wtp-models" class="quarto-xref">Table&nbsp;4</a>. Because WTP is bounded at $0 and $46, I also estimate a censored-normal (Tobit) model for each source, which treats $0 as censored from below and $46 as censored from above. Those models are shown in the supplemental material.</p>
<div class="cell">
<div id="tbl-wtp-models" class="cell quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-wtp-models-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;4: Effect of cue condition, political beliefs, and their interaction on willingness-to-pay for fossil fuels (any positive WTP, and amount among those with any positive WTP) and for renewables (survey-weighted logit/OLS; baseline condition and other/moderate identity as reference)
</figcaption>
<div aria-describedby="tbl-wtp-models-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<!-- preamble start -->

    <script src="https://cdn.jsdelivr.net/gh/vincentarelbundock/tinytable@main/inst/tinytable.js"></script>

    <script>
      // Create table-specific functions using external factory
      const tableFns_acoqi7uazx45g7s9u1xp = TinyTable.createTableFunctions("tinytable_acoqi7uazx45g7s9u1xp");
      // tinytable span after
      window.addEventListener('load', function () {
          var cellsToStyle = [
            // tinytable style arrays after
          { positions: [ { i: '21', j: 2 }, { i: '21', j: 3 }, { i: '21', j: 4 } ], css_id: 'tinytable_css_ckr96uicku6pszxawfqs',}, 
          { positions: [ { i: '18', j: 2 }, { i: '18', j: 3 }, { i: '18', j: 4 } ], css_id: 'tinytable_css_dgruu8doelxin427lwf7',}, 
          { positions: [ { i: '1', j: 2 }, { i: '2', j: 2 }, { i: '3', j: 2 }, { i: '4', j: 2 }, { i: '5', j: 2 }, { i: '6', j: 2 }, { i: '7', j: 2 }, { i: '8', j: 2 }, { i: '9', j: 2 }, { i: '10', j: 2 }, { i: '11', j: 2 }, { i: '12', j: 2 }, { i: '13', j: 2 }, { i: '14', j: 2 }, { i: '15', j: 2 }, { i: '16', j: 2 }, { i: '17', j: 2 }, { i: '19', j: 2 }, { i: '20', j: 2 }, { i: '1', j: 3 }, { i: '2', j: 3 }, { i: '3', j: 3 }, { i: '4', j: 3 }, { i: '5', j: 3 }, { i: '6', j: 3 }, { i: '7', j: 3 }, { i: '8', j: 3 }, { i: '9', j: 3 }, { i: '10', j: 3 }, { i: '11', j: 3 }, { i: '12', j: 3 }, { i: '13', j: 3 }, { i: '14', j: 3 }, { i: '15', j: 3 }, { i: '16', j: 3 }, { i: '17', j: 3 }, { i: '19', j: 3 }, { i: '20', j: 3 }, { i: '1', j: 4 }, { i: '2', j: 4 }, { i: '3', j: 4 }, { i: '4', j: 4 }, { i: '5', j: 4 }, { i: '6', j: 4 }, { i: '7', j: 4 }, { i: '8', j: 4 }, { i: '9', j: 4 }, { i: '10', j: 4 }, { i: '11', j: 4 }, { i: '12', j: 4 }, { i: '13', j: 4 }, { i: '14', j: 4 }, { i: '15', j: 4 }, { i: '16', j: 4 }, { i: '17', j: 4 }, { i: '19', j: 4 }, { i: '20', j: 4 } ], css_id: 'tinytable_css_icj725dbmbv5uaodn081',}, 
          { positions: [ { i: '0', j: 2 }, { i: '0', j: 3 }, { i: '0', j: 4 } ], css_id: 'tinytable_css_068in3adexgc1h17wf0v',}, 
          { positions: [ { i: '21', j: 1 } ], css_id: 'tinytable_css_4bw16ef86iv6p2lwshj8',}, 
          { positions: [ { i: '18', j: 1 } ], css_id: 'tinytable_css_xgmybn2qmnm1wtaclwbr',}, 
          { positions: [ { i: '1', j: 1 }, { i: '2', j: 1 }, { i: '3', j: 1 }, { i: '4', j: 1 }, { i: '5', j: 1 }, { i: '6', j: 1 }, { i: '7', j: 1 }, { i: '8', j: 1 }, { i: '9', j: 1 }, { i: '10', j: 1 }, { i: '11', j: 1 }, { i: '12', j: 1 }, { i: '13', j: 1 }, { i: '14', j: 1 }, { i: '15', j: 1 }, { i: '16', j: 1 }, { i: '17', j: 1 }, { i: '19', j: 1 }, { i: '20', j: 1 } ], css_id: 'tinytable_css_201ijye0fu1pd1gy7ew0',}, 
          { positions: [ { i: '0', j: 1 } ], css_id: 'tinytable_css_7jpszxcexzynwet71ndu',}, 
          ];

          // Loop over the arrays to style the cells
          cellsToStyle.forEach(function (group) {
              group.positions.forEach(function (cell) {
                  tableFns_acoqi7uazx45g7s9u1xp.styleCell(cell.i, cell.j, group.css_id);
              });
          });
      });
    </script>

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/gh/vincentarelbundock/tinytable@main/inst/tinytable.css">
    <style>
    /* tinytable css entries after */
    #tinytable_acoqi7uazx45g7s9u1xp td.tinytable_css_ckr96uicku6pszxawfqs, #tinytable_acoqi7uazx45g7s9u1xp th.tinytable_css_ckr96uicku6pszxawfqs {  position: relative; --border-bottom: 1; --border-left: 0; --border-right: 0; --border-top: 0; --line-color-bottom: var(--tt-line-color); --line-color-left: var(--tt-line-color); --line-color-right: var(--tt-line-color); --line-color-top: var(--tt-line-color); --line-width-bottom: 0.08em; --line-width-left: 0.1em; --line-width-right: 0.1em; --line-width-top: 0.1em; --trim-bottom-left: 0%; --trim-bottom-right: 0%; --trim-left-bottom: 0%; --trim-left-top: 0%; --trim-right-bottom: 0%; --trim-right-top: 0%; --trim-top-left: 0%; --trim-top-right: 0%; ; text-align: center }
    #tinytable_acoqi7uazx45g7s9u1xp td.tinytable_css_dgruu8doelxin427lwf7, #tinytable_acoqi7uazx45g7s9u1xp th.tinytable_css_dgruu8doelxin427lwf7 {  position: relative; --border-bottom: 1; --border-left: 0; --border-right: 0; --border-top: 0; --line-color-bottom: var(--tt-line-color); --line-color-left: var(--tt-line-color); --line-color-right: var(--tt-line-color); --line-color-top: var(--tt-line-color); --line-width-bottom: 0.05em; --line-width-left: 0.1em; --line-width-right: 0.1em; --line-width-top: 0.1em; --trim-bottom-left: 0%; --trim-bottom-right: 0%; --trim-left-bottom: 0%; --trim-left-top: 0%; --trim-right-bottom: 0%; --trim-right-top: 0%; --trim-top-left: 0%; --trim-top-right: 0%; ; text-align: center }
    #tinytable_acoqi7uazx45g7s9u1xp td.tinytable_css_icj725dbmbv5uaodn081, #tinytable_acoqi7uazx45g7s9u1xp th.tinytable_css_icj725dbmbv5uaodn081 { text-align: center }
    #tinytable_acoqi7uazx45g7s9u1xp td.tinytable_css_068in3adexgc1h17wf0v, #tinytable_acoqi7uazx45g7s9u1xp th.tinytable_css_068in3adexgc1h17wf0v {  position: relative; --border-bottom: 1; --border-left: 0; --border-right: 0; --border-top: 1; --line-color-bottom: var(--tt-line-color); --line-color-left: var(--tt-line-color); --line-color-right: var(--tt-line-color); --line-color-top: var(--tt-line-color); --line-width-bottom: 0.05em; --line-width-left: 0.1em; --line-width-right: 0.1em; --line-width-top: 0.08em; --trim-bottom-left: 0%; --trim-bottom-right: 0%; --trim-left-bottom: 0%; --trim-left-top: 0%; --trim-right-bottom: 0%; --trim-right-top: 0%; --trim-top-left: 0%; --trim-top-right: 0%; ; text-align: center }
    #tinytable_acoqi7uazx45g7s9u1xp td.tinytable_css_4bw16ef86iv6p2lwshj8, #tinytable_acoqi7uazx45g7s9u1xp th.tinytable_css_4bw16ef86iv6p2lwshj8 {  position: relative; --border-bottom: 1; --border-left: 0; --border-right: 0; --border-top: 0; --line-color-bottom: var(--tt-line-color); --line-color-left: var(--tt-line-color); --line-color-right: var(--tt-line-color); --line-color-top: var(--tt-line-color); --line-width-bottom: 0.08em; --line-width-left: 0.1em; --line-width-right: 0.1em; --line-width-top: 0.1em; --trim-bottom-left: 0%; --trim-bottom-right: 0%; --trim-left-bottom: 0%; --trim-left-top: 0%; --trim-right-bottom: 0%; --trim-right-top: 0%; --trim-top-left: 0%; --trim-top-right: 0%; ; text-align: left }
    #tinytable_acoqi7uazx45g7s9u1xp td.tinytable_css_xgmybn2qmnm1wtaclwbr, #tinytable_acoqi7uazx45g7s9u1xp th.tinytable_css_xgmybn2qmnm1wtaclwbr {  position: relative; --border-bottom: 1; --border-left: 0; --border-right: 0; --border-top: 0; --line-color-bottom: var(--tt-line-color); --line-color-left: var(--tt-line-color); --line-color-right: var(--tt-line-color); --line-color-top: var(--tt-line-color); --line-width-bottom: 0.05em; --line-width-left: 0.1em; --line-width-right: 0.1em; --line-width-top: 0.1em; --trim-bottom-left: 0%; --trim-bottom-right: 0%; --trim-left-bottom: 0%; --trim-left-top: 0%; --trim-right-bottom: 0%; --trim-right-top: 0%; --trim-top-left: 0%; --trim-top-right: 0%; ; text-align: left }
    #tinytable_acoqi7uazx45g7s9u1xp td.tinytable_css_201ijye0fu1pd1gy7ew0, #tinytable_acoqi7uazx45g7s9u1xp th.tinytable_css_201ijye0fu1pd1gy7ew0 { text-align: left }
    #tinytable_acoqi7uazx45g7s9u1xp td.tinytable_css_7jpszxcexzynwet71ndu, #tinytable_acoqi7uazx45g7s9u1xp th.tinytable_css_7jpszxcexzynwet71ndu {  position: relative; --border-bottom: 1; --border-left: 0; --border-right: 0; --border-top: 1; --line-color-bottom: var(--tt-line-color); --line-color-left: var(--tt-line-color); --line-color-right: var(--tt-line-color); --line-color-top: var(--tt-line-color); --line-width-bottom: 0.05em; --line-width-left: 0.1em; --line-width-right: 0.1em; --line-width-top: 0.08em; --trim-bottom-left: 0%; --trim-bottom-right: 0%; --trim-left-bottom: 0%; --trim-left-top: 0%; --trim-right-bottom: 0%; --trim-right-top: 0%; --trim-top-left: 0%; --trim-top-right: 0%; ; text-align: left }
    </style>
    <div class="container">
      <table class="tinytable" id="tinytable_acoqi7uazx45g7s9u1xp" style="width: auto; margin-left: auto; margin-right: auto;" data-quarto-disable-processing="true">
        
        <thead>
              <tr>
                <th scope="col" data-row="0" data-col="1"> </th>
                <th scope="col" data-row="0" data-col="2">Fossil fuels: Any WTP (logit)</th>
                <th scope="col" data-row="0" data-col="3">Fossil fuels: Amount, if WTP &gt; $0 (OLS)</th>
                <th scope="col" data-row="0" data-col="4">Renewables: Amount (OLS)</th>
              </tr>
        </thead>
        <tfoot><tr><td colspan="4">† p &lt; 0.1, * p &lt; 0.05, ** p &lt; 0.01</td></tr></tfoot>
        <tbody>
                <tr>
                  <td data-row="1" data-col="1">Trump cue</td>
                  <td data-row="1" data-col="2">-0.263</td>
                  <td data-row="1" data-col="3">-3.607</td>
                  <td data-row="1" data-col="4">-1.495</td>
                </tr>
                <tr>
                  <td data-row="2" data-col="1"></td>
                  <td data-row="2" data-col="2">(0.204)</td>
                  <td data-row="2" data-col="3">(2.265)</td>
                  <td data-row="2" data-col="4">(1.828)</td>
                </tr>
                <tr>
                  <td data-row="3" data-col="1">Climate cue</td>
                  <td data-row="3" data-col="2">0.100</td>
                  <td data-row="3" data-col="3">-1.509</td>
                  <td data-row="3" data-col="4">-1.604</td>
                </tr>
                <tr>
                  <td data-row="4" data-col="1"></td>
                  <td data-row="4" data-col="2">(0.206)</td>
                  <td data-row="4" data-col="3">(2.250)</td>
                  <td data-row="4" data-col="4">(1.741)</td>
                </tr>
                <tr>
                  <td data-row="5" data-col="1">Liberal Democrat</td>
                  <td data-row="5" data-col="2">-0.413*</td>
                  <td data-row="5" data-col="3">-0.075</td>
                  <td data-row="5" data-col="4">5.703**</td>
                </tr>
                <tr>
                  <td data-row="6" data-col="1"></td>
                  <td data-row="6" data-col="2">(0.182)</td>
                  <td data-row="6" data-col="3">(2.130)</td>
                  <td data-row="6" data-col="4">(1.569)</td>
                </tr>
                <tr>
                  <td data-row="7" data-col="1">Conservative Republican</td>
                  <td data-row="7" data-col="2">0.704**</td>
                  <td data-row="7" data-col="3">-3.275</td>
                  <td data-row="7" data-col="4">-6.620**</td>
                </tr>
                <tr>
                  <td data-row="8" data-col="1"></td>
                  <td data-row="8" data-col="2">(0.205)</td>
                  <td data-row="8" data-col="3">(2.092)</td>
                  <td data-row="8" data-col="4">(1.626)</td>
                </tr>
                <tr>
                  <td data-row="9" data-col="1">Trump cue × Liberal Democrat</td>
                  <td data-row="9" data-col="2">0.007</td>
                  <td data-row="9" data-col="3">3.124</td>
                  <td data-row="9" data-col="4">1.656</td>
                </tr>
                <tr>
                  <td data-row="10" data-col="1"></td>
                  <td data-row="10" data-col="2">(0.257)</td>
                  <td data-row="10" data-col="3">(2.871)</td>
                  <td data-row="10" data-col="4">(2.234)</td>
                </tr>
                <tr>
                  <td data-row="11" data-col="1">Climate cue × Liberal Democrat</td>
                  <td data-row="11" data-col="2">-0.270</td>
                  <td data-row="11" data-col="3">1.507</td>
                  <td data-row="11" data-col="4">3.136</td>
                </tr>
                <tr>
                  <td data-row="12" data-col="1"></td>
                  <td data-row="12" data-col="2">(0.259)</td>
                  <td data-row="12" data-col="3">(3.026)</td>
                  <td data-row="12" data-col="4">(2.167)</td>
                </tr>
                <tr>
                  <td data-row="13" data-col="1">Trump cue × Conservative Republican</td>
                  <td data-row="13" data-col="2">0.423</td>
                  <td data-row="13" data-col="3">3.919</td>
                  <td data-row="13" data-col="4">0.320</td>
                </tr>
                <tr>
                  <td data-row="14" data-col="1"></td>
                  <td data-row="14" data-col="2">(0.299)</td>
                  <td data-row="14" data-col="3">(2.964)</td>
                  <td data-row="14" data-col="4">(2.337)</td>
                </tr>
                <tr>
                  <td data-row="15" data-col="1">Climate cue × Conservative Republican</td>
                  <td data-row="15" data-col="2">-0.042</td>
                  <td data-row="15" data-col="3">3.665</td>
                  <td data-row="15" data-col="4">2.935</td>
                </tr>
                <tr>
                  <td data-row="16" data-col="1"></td>
                  <td data-row="16" data-col="2">(0.293)</td>
                  <td data-row="16" data-col="3">(2.917)</td>
                  <td data-row="16" data-col="4">(2.311)</td>
                </tr>
                <tr>
                  <td data-row="17" data-col="1">(Intercept)</td>
                  <td data-row="17" data-col="2">0.048</td>
                  <td data-row="17" data-col="3">17.374**</td>
                  <td data-row="17" data-col="4">18.665**</td>
                </tr>
                <tr>
                  <td data-row="18" data-col="1"></td>
                  <td data-row="18" data-col="2">(0.145)</td>
                  <td data-row="18" data-col="3">(1.712)</td>
                  <td data-row="18" data-col="4">(1.271)</td>
                </tr>
                <tr>
                  <td data-row="19" data-col="1">Num.Obs.</td>
                  <td data-row="19" data-col="2">3113</td>
                  <td data-row="19" data-col="3">1433</td>
                  <td data-row="19" data-col="4">3113</td>
                </tr>
                <tr>
                  <td data-row="20" data-col="1">Adj. R2</td>
                  <td data-row="20" data-col="2"></td>
                  <td data-row="20" data-col="3">0.002</td>
                  <td data-row="20" data-col="4">0.104</td>
                </tr>
                <tr>
                  <td data-row="21" data-col="1">McFadden's pseudo R2</td>
                  <td data-row="21" data-col="2">0.061</td>
                  <td data-row="21" data-col="3"></td>
                  <td data-row="21" data-col="4"></td>
                </tr>
        </tbody>
      </table>
    </div>
<!-- hack to avoid NA insertion in last line -->
</div>
</div>
</figure>
</div>
</div>
<p>For fossil fuels, conservative Republicans were significantly more likely than the reference group to have any positive WTP (b = 0.70, log-odds scale), predicted at 68.0% in the baseline condition compared to 41.0% for liberal Democrats (b = -0.41, <em>p</em> = 0.023). However, neither the cues nor the interactions between the cues and political beliefs were significant. The WTP amounts are shown in <a href="#fig-wtp-fossil-predicted" class="quarto-xref">Figure&nbsp;2</a> and <a href="#fig-wtp-renewable-predicted" class="quarto-xref">Figure&nbsp;3</a>.</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-wtp-fossil-predicted" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-fig" id="fig-wtp-fossil-predicted-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;2: Predicted willingness-to-pay for fossil fuels, among respondents with any positive WTP, by cue condition and political identity (survey-weighted OLS predictions with 95% CIs)
</figcaption>
<div aria-describedby="fig-wtp-fossil-predicted-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="cue-WTP_files/figure-html/fig-wtp-fossil-predicted-1.png" class="img-fluid figure-img" width="672">
</div>
</figure>
</div>
</div>
</div>
<div class="cell">
<div class="cell-output-display">
<div id="fig-wtp-renewable-predicted" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-fig" id="fig-wtp-renewable-predicted-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;3: Predicted willingness-to-pay for renewables by cue condition and political identity (survey-weighted OLS predictions with 95% CIs)
</figcaption>
<div aria-describedby="fig-wtp-renewable-predicted-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="cue-WTP_files/figure-html/fig-wtp-renewable-predicted-1.png" class="img-fluid figure-img" width="672">
</div>
</figure>
</div>
</div>
</div>
<p>For fossil fuels, neither the Trump cue nor its interaction with conservative Republican identity significantly predicted a WTP &gt; $0 or, among those with positive WTP, the dollar amount. Overall, the predicted WTP &gt; $0 for conservative Republicans was 68.0% in the baseline condition versus 71.3% in the Trump cue, and the predicted amount conditional on paying something was $14.10 versus $14.41. In the Tobit model of fossil fuel WTP, the Trump cue x conservative Republican interaction is significant (b = 7.78, <em>p</em> = 0.038). However, this interaction reflects a lower WTP for fossil fuels in the Trump cue among those with other political beliefs (b = -5.66, <em>p</em> = 0.047) rather than a higher WTP among conservative Republicans, whose WTP for fossil fuels in the Trump cue did not differ from the baseline (difference = 2.12, <em>p</em> = 0.381). The interaction is also not significant after adjusting for multiple comparisons (Holm-adjusted <em>p</em> = 0.65).</p>
<p>Looking to renewables, liberal Democrats were willing to pay $5.70 more, on average, and conservative Republicans were willing to pay $6.62 less, for a predicted total of $12.04 in the baseline condition. The climate cue was associated with a higher WTP for renewables among liberal Democrats (b = 3.14, <em>p</em> = 0.148), but the estimate was nearly as large among conservative Republicans, and neither interaction was significant.</p>
<p>The absence of significant interactions for WTP should not be read as evidence that the cues have no effect on WTP. With 80 percent power and <span class="math inline">\(\alpha\)</span> = .05, the smallest interaction effects the design could reliably detect are $6.07 to 6.55 for renewables and $8.04 to 8.48 for the amount of fossil fuel WTP, compared with 0.49 to 0.66 points for the priority scale. Smaller effects of the cues on WTP cannot be ruled out. Additionally, neither cue had a significant average effect on WTP for either source in the models with the cues alone (all <em>p</em> <span class="math inline">\(\geq\)</span> 0.135).</p>
<p>Overall, respondents leaned toward renewables on the priority scale, and the WTP for renewables was higher than for fossil fuels, though the size of the WTP difference likely reflects the wording of the prompts. The difference in WTP was also not uniform across groups. For example, among conservative Republicans in the Trump cue, the WTP for renewables did not differ significantly from the WTP for fossil fuels (difference = $0.59, <em>p</em> = 0.669).</p>
<p>Comparing the results to the hypotheses, the support is mixed. As expected, political beliefs shaped both preferences and WTP, largely supporting H1a and H1b. Conservative Republicans prioritized fossil fuels more than those with other political beliefs, were more likely to have any positive WTP for fossil fuels, and were WTP less for renewables. Liberal Democrats, in contrast, prioritized renewables, were less likely to have any positive WTP for fossil fuels, and were WTP more for renewables. However, among those WTP something for fossil fuels, conservative Republicans were not WTP more than others. H2a and H2b were not supported, as neither the Trump cue nor the climate cue had a significant average effect on energy priority or WTP for either source compared to the baseline condition. H3a and H3b received limited support. There is some evidence that the Trump cue moved conservative Republicans toward fossil fuels (<em>p</em> = 0.062) and the climate cue moved liberal Democrats toward renewables (<em>p</em> = 0.051) on the priority scale, but both interactions were only marginally significant and neither holds after adjusting for multiple comparisons. Regarding RQ1, there was no evidence that either cue led partisans to move away from the position of the source. Regarding RQ2, the shifts in priority did not carry over to WTP, as none of the interactions between the cues and political beliefs reliably predicted WTP for fossil fuels or renewables. These results suggest that cues are likely more effective at moving the priority the public gives to energy sources than the amount they are willing to pay, though the design could not detect small effects on WTP.</p>
</section>
<section id="discussion-and-conclusion" class="level1">
<h1>Discussion and Conclusion</h1>
<p>A clean energy transition is needed to mitigate climate change, and public support is needed for the energy transition. However, President Trump’s rhetoric and actions on energy may serve to polarize the public. This study examined how exposure to a Trump cue or a climate change cue shapes the US public’s prioritization of, and willingness-to-pay for, fossil fuel versus renewable electricity, and how these responses are shaped by political beliefs. The results show that support for energy sources is polarized along partisan lines, both in how respondents prioritized fossil fuels against renewables and in the dollar amounts they were willing to pay. There is also some evidence that a Trump cue moved conservative Republicans toward fossil fuels and a climate cue moved liberal Democrats toward renewables, though these effects were marginal and should be considered tentative. Together, these findings suggest that cues may further exacerbate existing partisan divisions in how the public prioritizes energy sources.</p>
<p>The cue effects were also uneven across the two outcomes. Political beliefs appear to condition the effect of the cues on prioritization, but not on WTP. For example, the Trump cue did not significantly change WTP for fossil fuels among conservative Republicans. This is likely because stating a priority is costless, whereas stating a WTP asks respondents to consider a cost to their own household. Agreeing with a trusted source, or reacting to a cue, may be easy when nothing is at stake, but the concrete cost of an increase in an electricity bill may limit the influence of cues, especially in times of concern about rising energy costs.<a href="#fn3" class="footnote-ref" id="fnref3" role="doc-noteref"><sup>3</sup></a> Additionally, a single cue is likely a weaker treatment than the sustained rhetoric respondents may encounter outside of a survey. However, the design could only detect relatively large interaction effects on WTP, so small effects of the cues on WTP cannot be ruled out.</p>
<p>These results carry several implications for climate and energy policy. First, respondents, on average, leaned toward prioritizing renewables over fossil fuels, with a mean of 5.17 on the 1 to 7 scale, and 86 percent of respondents reported some positive WTP for renewables. This suggests that renewable energy investment likely has general public support even in a polarized environment, though the size of the WTP gap between renewables and fossil fuels should be interpreted with caution. Second, if the tentative responsiveness of conservative Republicans and liberal Democrats to identity-congruent cues holds, elite rhetoric, including rhetoric tied to a single prominent figure, may widen the partisan gap in energy preferences further, which is a risk for policymakers seeking durable, bipartisan support for energy policy. Third, because the cues did not shift prioritization in the sample overall and did not reliably shift WTP, messaging strategies aimed at building broad coalitions for the energy transition likely benefit from emphasizing shared, cross-partisan benefits of renewables, such as reliability or local economic development, rather than frames tied to a specific political figure or to climate change.</p>
<p>This study has some limitations. First, respondents were recruited from an opt-in, quota-based panel rather than a probability sample, and the survey weights substantially increase the share of conservative Republicans. Second, the WTP prompts were not symmetric, as the fossil fuel prompt included a reason not to pay for fossil fuels, which likely inflates the difference between WTP for renewables and fossil fuels. Third, the conditions were not parallel. The Trump cue changed only the source of the argument for fossil fuels, whereas the climate cue added a scientific source, a climate change frame, and a counterargument, so the effects of the two cues cannot be compared directly. Fourth, party identification and ideology were measured after the outcomes, though their distribution did not differ across conditions. Fifth, the survey did not include attention or manipulation checks, and the starting amounts for the WTP questions were not recorded. Finally, the WTP measure relies on a hypothetical, stated-preference elicitation, and stated WTP does not always translate into WTP once a real price change is introduced. The cues were also each delivered once, in a single survey context, and their effects may not persist or generalize to the repeated, cumulative exposure people experience outside of a survey.</p>
<p>Future research should examine whether repeated exposure to partisan cues over time widens the partisan gap in energy preferences identified here, and whether the cues have larger effects on WTP when respondents are asked to pay the stated amount rather than simply report it. Future research should also use parallel cue conditions and symmetric WTP prompts, and test whether cue effects on costless and costly expressions of preference differ within the same respondents.</p>
</section>
<section id="statements-and-declarations" class="level1 unnumbered">
<h1 class="unnumbered">Statements and Declarations</h1>
<p><strong>Ethics approval.</strong> This study was reviewed and approved by the University of Texas at Arlington Institutional Review Board [PROTOCOL NUMBER], and all respondents provided informed consent.</p>
<p><strong>Pre-registration.</strong> The study was not pre-registered.</p>
<p><strong>Data availability.</strong> The code to reproduce the analysis is available at <a href="https://github.com/mnowlin/cue-WTP" class="uri">https://github.com/mnowlin/cue-WTP</a>. The survey data will be made available upon publication.</p>
<div style="page-break-after: always;"></div>
</section>
<section id="references" class="level1 unnumbered">


</section>


<div id="quarto-appendix" class="default"><section class="quarto-appendix-contents" role="doc-bibliography" id="quarto-bibliography"><h2 class="anchored quarto-appendix-heading">References</h2><div id="refs" class="references csl-bib-body hanging-indent" role="list">
<div id="ref-aldyWillingnessPayPolitical2012" class="csl-entry" role="listitem">
Aldy, Joseph E., Matthew J. Kotchen, and Anthony A. Leiserowitz. 2012. <span>“Willingness to <span>Pay</span> and <span>Political Support</span> for a <span>US National Clean Energy Standard</span>.”</span> <em>Nature Climate Change</em> 2(8): 596–99.
</div>
<div id="ref-benegalCostSensitivityPartisan2024" class="csl-entry" role="listitem">
Benegal, Salil, and Jon Green. 2024. <span>“Cost <span>Sensitivity</span>, <span>Partisan Cues</span>, and <span>Support</span> for the <span>Green New Deal</span>.”</span> <em>Journal of Environmental Studies and Sciences</em> 14(4): 763–75.
</div>
<div id="ref-bergquistEnergyPolicyPublic2020" class="csl-entry" role="listitem">
Bergquist, Parrish, David M Konisky, and John Kotcher. 2020. <span>“Energy <span>Policy</span> and <span>Public Opinion</span>: <span>Patterns</span>, <span>Trends</span> and <span>Future Directions</span>.”</span> <em>Progress in Energy</em> 2(3): 032003.
</div>
<div id="ref-bolsenInfluencePartisanMotivated2014" class="csl-entry" role="listitem">
Bolsen, Toby, James N. Druckman, and Fay Lomax Cook. 2014. <span>“The <span>Influence</span> of <span>Partisan Motivated Reasoning</span> on <span>Public Opinion</span>.”</span> <em>Political Behavior</em> 36(2): 235–62.
</div>
<div id="ref-borchersDoesWillingnessPay2007" class="csl-entry" role="listitem">
Borchers, Allison M., Joshua M. Duke, and George R. Parsons. 2007. <span>“Does <span>Willingness</span> to <span>Pay</span> for <span>Green Energy Differ</span> by <span>Source</span>?”</span> <em>Energy Policy</em> 35(6): 3327–34.
</div>
<div id="ref-breidertReviewMethodsMeasuring2006" class="csl-entry" role="listitem">
Breidert, Christoph, Michael Hahsler, and Thomas Reutterer. 2006. <span>“A <span>Review</span> of <span>Methods</span> for <span class="nocase">Measuring Willingness-to-Pay</span>.”</span> <em>Innovative Marketing</em> 2(4): 8–32.
</div>
<div id="ref-bullockPartisanBiasFactual2015" class="csl-entry" role="listitem">
Bullock, John G., Alan S. Gerber, Seth J. Hill, and Gregory A. Huber. 2015. <span>“Partisan <span>Bias</span> in <span>Factual Beliefs</span> about <span>Politics</span>.”</span> <em>Quarterly Journal of Political Science</em> 10(4): 519–78.
</div>
<div id="ref-cardellaPriceVolatilityResidential2017" class="csl-entry" role="listitem">
Cardella, Eric, Bradley T. Ewing, and Ryan B. Williams. 2017. <span>“Price <span>Volatility</span> and <span>Residential Electricity Decisions</span>: <span>Experimental Evidence</span> on the <span>Convergence</span> of <span>Energy Generating Source</span>.”</span> <em>Energy Economics</em> 62: 428–37.
</div>
<div id="ref-druckmanHowElitePartisan2013" class="csl-entry" role="listitem">
Druckman, James N., Erik Peterson, and Rune Slothuus. 2013. <span>“How <span>Elite Partisan Polarization Affects Public Opinion Formation</span>.”</span> <em>American Political Science Review</em> 107(01): 57–79.
</div>
<div id="ref-ehretPartisanBarriersBipartisanship2018" class="csl-entry" role="listitem">
Ehret, Phillip J., Leaf Van Boven, and David K. Sherman. 2018. <span>“Partisan <span>Barriers</span> to <span>Bipartisanship</span>: <span>Understanding Climate Policy Polarization</span>.”</span> <em>Social Psychological and Personality Science</em> 9(3): 308–18.
</div>
<div id="ref-feldmanClimateChangePolarizing2018" class="csl-entry" role="listitem">
Feldman, Lauren, and P. Sol Hart. 2018. <span>“Climate <span>Change</span> as a <span>Polarizing Cue</span>: <span>Framing Effects</span> on <span>Public Support</span> for <span>Low-Carbon Energy Policies</span>.”</span> <em>Global Environmental Change</em> 51: 54–66.
</div>
<div id="ref-gaborPriceIndicatorQuality1966" class="csl-entry" role="listitem">
Gabor, André, and C. W. J. Granger. 1966. <span>“Price as an <span>Indicator</span> of <span>Quality</span>: <span>Report</span> on an <span>Enquiry</span>.”</span> <em>Economica</em> 33: 43–70.
</div>
<div id="ref-grometPoliticalIdeologyAffects2013" class="csl-entry" role="listitem">
Gromet, Dena M., Howard Kunreuther, and Richard P. Larrick. 2013. <span>“Political <span>Ideology Affects Energy-Efficiency Attitudes</span> and <span>Choices</span>.”</span> <em>Proceedings of the National Academy of Sciences</em> 110(23): 9314–19.
</div>
<div id="ref-hamiltonChangeWindUS2018" class="csl-entry" role="listitem">
Hamilton, Lawrence C., Erin Bell, Joel Hartter, and Jonathan D. Salerno. 2018. <span>“A <span>Change</span> in the <span>Wind</span>? <span>US Public Views</span> on <span>Renewable Energy</span> and <span>Climate Compared</span>.”</span> <em>Energy, Sustainability and Society</em> 8(1): 11.
</div>
<div id="ref-hawesClimateSciencePolitics2022" class="csl-entry" role="listitem">
Hawes, Rachel, and Matthew C. Nowlin. 2022. <span>“Climate <span>Science</span> or <span>Politics</span>? <span>Disentangling</span> the <span>Roles</span> of <span>Citizen Beliefs</span> and <span>Support</span> for <span>Energy</span> in the <span>United States</span>.”</span> <em>Energy Research &amp; Social Science</em> 85: 102419.
</div>
<div id="ref-jonesSurveyTechniqueMeasure1975" class="csl-entry" role="listitem">
Jones, D. Frank. 1975. <span>“A <span>Survey Technique</span> to <span>Measure Demand</span> Under <span>Various Pricing Strategies</span>.”</span> <em>Journal of Marketing</em> 39(3): 75–77.
</div>
<div id="ref-kennedyAmericansShiftingViews2026" class="csl-entry" role="listitem">
Kennedy, Brian, and Emma Kikuchi. 2026. <span>“Americans’ <span>Shifting Views</span> on <span>Energy Sources</span>, <span>Policy</span> in 2026.”</span> https://www.pewresearch.org/science/2026/04/03/americans-shifting-views-on-energy-issues/ (April 21, 2026).
</div>
<div id="ref-knappWillConsumersReally2020" class="csl-entry" role="listitem">
Knapp, Lauren, Eric O’Shaughnessy, Jenny Heeter, Sarah Mills, and John M. DeCicco. 2020. <span>“Will <span>Consumers Really Pay</span> for <span>Green Electricity</span>? <span>Comparing Stated</span> and <span>Revealed Preferences</span> for <span>Residential Programs</span> in the <span>United States</span>.”</span> <em>Energy Research &amp; Social Science</em> 65: 101457.
</div>
<div id="ref-kotchenWillingnesstoPayPolicyInstrumentChoice2013" class="csl-entry" role="listitem">
Kotchen, Matthew J., Kevin J. Boyle, and Anthony A. Leiserowitz. 2013. <span>“Willingness-to-<span>Pay</span> and <span>Policy-Instrument Choice</span> for <span>Climate-Change Policy</span> in the <span>United States</span>.”</span> <em>Energy Policy</em> 55: 617–25.
</div>
<div id="ref-kotchenPublicWillingnessPay2017" class="csl-entry" role="listitem">
Kotchen, Matthew J., Zachary M. Turk, and Anthony A. Leiserowitz. 2017. <span>“Public <span>Willingness</span> to <span>Pay</span> for a <span>US Carbon Tax</span> and <span>Preferences</span> for <span>Spending</span> the <span>Revenue</span>.”</span> <em>Environmental Research Letters</em> 12(9).
</div>
<div id="ref-liPublicSupportReducing2009" class="csl-entry" role="listitem">
Li, Hui, Hank C. Jenkins-Smith, Carol L. Silva, Robert P. Berrens, and Kerry G. Herron. 2009. <span>“Public <span>Support</span> for <span>Reducing US Reliance</span> on <span>Fossil Fuels</span>: <span class="nocase">Investigating Household Willingness-to-Pay</span> for <span>Energy Research</span> and <span>Development</span>.”</span> <em>Ecological Economics</em> 68(3): 731–42.
</div>
<div id="ref-lipovetskyPricingModelsMarketing2011" class="csl-entry" role="listitem">
Lipovetsky, Stan, Shon Magnan, and Andrea Zanetti-Polzi. 2011. <span>“Pricing <span>Models</span> in <span>Marketing Research</span>.”</span> <em>Intelligent Information Management</em> 3(5): 167–74.
</div>
<div id="ref-merkleyPartyCuesNews2021" class="csl-entry" role="listitem">
Merkley, Eric, and Dominik A. Stecula. 2021. <span>“Party <span>Cues</span> in the <span>News</span>: <span>Democratic Elites</span>, <span>Republican Backlash</span>, and the <span>Dynamics</span> of <span>Climate Skepticism</span>.”</span> <em>British Journal of Political Science</em> 51(4): 1439–56.
</div>
<div id="ref-murakamiConsumersWillingnessPay2015" class="csl-entry" role="listitem">
Murakami, Kayo, Takanori Ida, Makoto Tanaka, and Lee Friedman. 2015. <span>“Consumers’ <span>Willingness</span> to <span>Pay</span> for <span>Renewable</span> and <span>Nuclear Energy</span>: <span>A Comparative Analysis Between</span> the <span>US</span> and <span>Japan</span>.”</span> <em>Energy Economics</em> 50: 178–89.
</div>
<div id="ref-nkansahWillingnessPayWind2019" class="csl-entry" role="listitem">
Nkansah, Kofi, and Alan R Collins. 2019. <span>“Willingness to <span>Pay</span> for <span>Wind</span> Versus <span>Natural Gas Generation</span> of <span>Electricity</span>.”</span> <em>Agricultural and Resource Economics Review</em> 48(1): 44–70.
</div>
<div id="ref-priorYouCannotBe2015a" class="csl-entry" role="listitem">
Prior, Markus, Gaurav Sood, and Kabir Khanna. 2015. <span>“You <span>Cannot</span> Be <span>Serious</span>: <span>The Impact</span> of <span>Accuracy Incentives</span> on <span>Partisan Bias</span> in <span>Reports</span> of <span>Economic Perceptions</span>.”</span> <em>Quarterly Journal of Political Science</em> 10(4): 489–518.
</div>
<div id="ref-scheuchVotersSupportAre2026" class="csl-entry" role="listitem">
Scheuch, Eric. 2026. <span>“Voters <span>Support</span> and <span>Are Willing</span> to <span>Pay</span> for <span>Local Climate Adaptation Policies</span>.”</span> <em>Urban Affairs Review</em>: 10780874261475229.
</div>
<div id="ref-teslerEliteDominationPublic2018" class="csl-entry" role="listitem">
Tesler, Michael. 2018. <span>“Elite <span>Domination</span> of <span>Public Doubts About Climate Change</span> (<span>Not Evolution</span>).”</span> <em>Political Communication</em> 35(2): 306–26.
</div>
<div id="ref-walterExaminingWillingnessPay2023" class="csl-entry" role="listitem">
Walter, Kara A., Jennifer Thacher, and Janie M. Chermak. 2023. <span>“Examining <span>Willingness</span> to <span>Pay</span> for <span>Energy Futures</span> in a <span>Fossil</span> and <span>Renewable Energy-Rich Locale</span>.”</span> <em>Energy Policy</em> 181: 113661.
</div>
<div id="ref-wedelModelEffectsPsychological1998" class="csl-entry" role="listitem">
Wedel, Michel, and Peter S. H. Leeflang. 1998. <span>“A Model for the Effects of Psychological Pricing in <span>Gabor</span>–<span>Granger</span> Price Studies.”</span> <em>Journal of Economic Psychology</em> 19(2): 237–60.
</div>
</div></section><section id="footnotes" class="footnotes footnotes-end-of-document" role="doc-endnotes"><h2 class="anchored quarto-appendix-heading">Footnotes</h2>

<ol>
<li id="fn1"><p>It should be noted that WTP for energy is not just a function of partisanship or environmental beliefs. <span class="citation" data-cites="cardellaPriceVolatilityResidential2017">Cardella, Ewing, and Williams (<a href="#ref-cardellaPriceVolatilityResidential2017" role="doc-biblioref">2017</a>)</span> found that price volatility, not just price level, shapes residential customers’ generation-source decisions, and <span class="citation" data-cites="knappWillConsumersReally2020">Knapp et al. (<a href="#ref-knappWillConsumersReally2020" role="doc-biblioref">2020</a>)</span> found that stated WTP for green electricity programs does not consistently translate into enrollment once a real premium is offered. <span class="citation" data-cites="aldyWillingnessPayPolitical2012">Aldy, Kotchen, and Leiserowitz (<a href="#ref-aldyWillingnessPayPolitical2012" role="doc-biblioref">2012</a>)</span> likewise found that WTP for a national clean energy standard depended on how the standard was structured, in addition to the respondents’ political affiliations.<a href="#fnref1" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn2"><p>Randomization produced conditions that were similar on gender, college education, income, and concern about the cost of electricity, but the conditions differed somewhat in age and in the share of white respondents. A balance table is shown in the supplemental material, and the results are similar when controlling for demographics.<a href="#fnref2" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn3"><p>I ran a robustness check that included a measure of the respondent’s concern about the cost of energy. The results are similar to what is reported here, and are shown in the supplemental material.<a href="#fnref3" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
</ol>
</section></div></main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->




</body></html>