{
  "hash": "83a0b05f72af4900074736de6871f3cc",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Supplemental Materials: Cues, Partisanship, and Willingness-to-Pay for Energy\"\nbibliography: references.bib\ncsl: american-political-science-association.csl\nfig-cap-location: top\nfontfamily: ebgaramond\nlink-bibliography: false\nformat:\n  html:\n    author:\n      - name: Matthew C. Nowlin\n        email: matthew.nowlin@uta.edu\n        corresponding: true\n        affiliations:\n          - name: University of Texas at Arlington\n            department: Department of Political Science\n    template-partials:\n      - title-metadata.html\n  pdf:\n    author:\n      - name: \"Matthew C. Nowlin^[Associate Professor, Department of Political Science, University of Texas at Arlington. Email: matthew.nowlin@uta.edu]\"\n    include-in-header:\n      text: |\n        \\usepackage{setspace}\n        \\usepackage{dcolumn}\n        \\usepackage{float}\n        \\usepackage{amsmath}\n        \\usepackage{ulem}\n        \\addtokomafont{disposition}{\\rmfamily}\n        \\normalem\n  docx:\n    author:\n      - name: \"Matthew C. Nowlin^[Associate Professor, Department of Political Science, University of Texas at Arlington. Email: matthew.nowlin@uta.edu]\"\n    reference-doc: custom-reference-doc.docx\n---\n\n\n\n# Robustness Check: Controlling for Demographics\n\nThe main text models the effect of cue condition, political identity, and their interaction on energy-source prioritization and willingness-to-pay (WTP) without any additional controls. This appendix reports two robustness checks. This section re-estimates every main-text model controlling for age, male, white, education, and income; the following section adds concern about the cost of electricity to those demographic controls. As shown below, the coefficients, their significance, and the substantive conclusions are consistent with the main text.\n\nThe results for the energy source-priority scale are shown in @tbl-priority-ols-supp-demo, parallel to the priority-scale table in the main text.\n\n\n::: {#tbl-priority-ols-supp-demo .cell tbl-cap='Effect of cue condition, political beliefs, and their interaction on the energy source-priority scale, controlling for demographics (survey-weighted OLS; baseline condition and other/moderate identity as reference)'}\n::: {.cell-output-display}\n\n+---------------------------------------+----------------+\n|                                       | Priority scale |\n+=======================================+================+\n| Trump cue                             | -0.027         |\n+---------------------------------------+----------------+\n|                                       | (0.160)        |\n+---------------------------------------+----------------+\n| Climate cue                           | -0.131         |\n+---------------------------------------+----------------+\n|                                       | (0.154)        |\n+---------------------------------------+----------------+\n| Liberal Democrat                      | 0.657**        |\n+---------------------------------------+----------------+\n|                                       | (0.126)        |\n+---------------------------------------+----------------+\n| Conservative Republican               | -1.224**       |\n+---------------------------------------+----------------+\n|                                       | (0.149)        |\n+---------------------------------------+----------------+\n| Trump cue × Liberal Democrat          | 0.173          |\n+---------------------------------------+----------------+\n|                                       | (0.184)        |\n+---------------------------------------+----------------+\n| Climate cue × Liberal Democrat        | 0.372*         |\n+---------------------------------------+----------------+\n|                                       | (0.176)        |\n+---------------------------------------+----------------+\n| Trump cue × Conservative Republican   | -0.413†        |\n+---------------------------------------+----------------+\n|                                       | (0.234)        |\n+---------------------------------------+----------------+\n| Climate cue × Conservative Republican | 0.075          |\n+---------------------------------------+----------------+\n|                                       | (0.218)        |\n+---------------------------------------+----------------+\n| Age                                   | -0.010**       |\n+---------------------------------------+----------------+\n|                                       | (0.002)        |\n+---------------------------------------+----------------+\n| Male                                  | 0.226**        |\n+---------------------------------------+----------------+\n|                                       | (0.068)        |\n+---------------------------------------+----------------+\n| White                                 | 0.145†         |\n+---------------------------------------+----------------+\n|                                       | (0.078)        |\n+---------------------------------------+----------------+\n| Education                             | 0.041*         |\n+---------------------------------------+----------------+\n|                                       | (0.019)        |\n+---------------------------------------+----------------+\n| Income                                | 0.018          |\n+---------------------------------------+----------------+\n|                                       | (0.013)        |\n+---------------------------------------+----------------+\n| (Intercept)                           | 5.493**        |\n+---------------------------------------+----------------+\n|                                       | (0.162)        |\n+---------------------------------------+----------------+\n| Num.Obs.                              | 3113           |\n+---------------------------------------+----------------+\n| Adj. R2                               | 0.328          |\n+=======================================+================+\n| † p < 0.1, * p < 0.05, ** p < 0.01                     |\n+=======================================+================+\n:::\n:::\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n![Predicted energy source-priority scale (1-7) by cue condition and political identity, controlling for demographics (survey-weighted OLS predictions with 95% CIs; age, male, white, education, and income held at their survey-weighted means)](supplemental-materials_files/figure-docx/fig-priority-predicted-supp-demo-1.png){#fig-priority-predicted-supp-demo}\n:::\n:::\n\n\nAs in the main text, conservative Republicans were more likely to prioritize fossil fuels (b = -1.22, *p* < .001) and liberal Democrats more likely to prioritize renewables (b = 0.66, *p* < .001). The interaction terms significant at *p* $\\leq$ .10 in this specification are:\n\n- Conservative Republican: b = -1.22, *p* = 0.000\n- Liberal Democrat: b = 0.66, *p* = 0.000\n- Climate cue × Liberal Democrat: b = 0.37, *p* = 0.034\n- Trump cue × Conservative Republican: b = -0.41, *p* = 0.077\n\nThe results for the WTP models are shown in @tbl-wtp-models-supp-demo, parallel to the WTP models table in the main text.\n\n\n::: {#tbl-wtp-models-supp-demo .cell tbl-cap='Effect of cue condition, political beliefs, and their interaction on willingness-to-pay for fossil fuels (any positive WTP, and amount among those with any positive WTP) and for renewables, controlling for demographics (survey-weighted logit/OLS; baseline condition and other/moderate identity as reference)'}\n::: {.cell-output-display}\n\n+---------------------------------------+-------------------------------+-----------------------------------------+--------------------------+\n|                                       | Fossil fuels: Any WTP (logit) | Fossil fuels: Amount, if WTP > $0 (OLS) | Renewables: Amount (OLS) |\n+=======================================+===============================+=========================================+==========================+\n| Trump cue                             | -0.257                        | -3.326                                  | -1.525                   |\n+---------------------------------------+-------------------------------+-----------------------------------------+--------------------------+\n|                                       | (0.210)                       | (2.268)                                 | (1.853)                  |\n+---------------------------------------+-------------------------------+-----------------------------------------+--------------------------+\n| Climate cue                           | 0.088                         | -1.007                                  | -1.423                   |\n+---------------------------------------+-------------------------------+-----------------------------------------+--------------------------+\n|                                       | (0.209)                       | (2.231)                                 | (1.756)                  |\n+---------------------------------------+-------------------------------+-----------------------------------------+--------------------------+\n| Liberal Democrat                      | -0.377*                       | -0.357                                  | 5.203**                  |\n+---------------------------------------+-------------------------------+-----------------------------------------+--------------------------+\n|                                       | (0.186)                       | (2.116)                                 | (1.575)                  |\n+---------------------------------------+-------------------------------+-----------------------------------------+--------------------------+\n| Conservative Republican               | 0.743**                       | -3.018                                  | -6.790**                 |\n+---------------------------------------+-------------------------------+-----------------------------------------+--------------------------+\n|                                       | (0.209)                       | (2.091)                                 | (1.641)                  |\n+---------------------------------------+-------------------------------+-----------------------------------------+--------------------------+\n| Trump cue × Liberal Democrat          | -0.024                        | 3.119                                   | 2.048                    |\n+---------------------------------------+-------------------------------+-----------------------------------------+--------------------------+\n|                                       | (0.261)                       | (2.875)                                 | (2.242)                  |\n+---------------------------------------+-------------------------------+-----------------------------------------+--------------------------+\n| Climate cue × Liberal Democrat        | -0.302                        | 1.211                                   | 3.490                    |\n+---------------------------------------+-------------------------------+-----------------------------------------+--------------------------+\n|                                       | (0.262)                       | (2.977)                                 | (2.176)                  |\n+---------------------------------------+-------------------------------+-----------------------------------------+--------------------------+\n| Trump cue × Conservative Republican   | 0.425                         | 3.394                                   | 0.384                    |\n+---------------------------------------+-------------------------------+-----------------------------------------+--------------------------+\n|                                       | (0.302)                       | (2.937)                                 | (2.340)                  |\n+---------------------------------------+-------------------------------+-----------------------------------------+--------------------------+\n| Climate cue × Conservative Republican | -0.044                        | 3.088                                   | 2.927                    |\n+---------------------------------------+-------------------------------+-----------------------------------------+--------------------------+\n|                                       | (0.296)                       | (2.886)                                 | (2.310)                  |\n+---------------------------------------+-------------------------------+-----------------------------------------+--------------------------+\n| Age                                   | 0.007*                        | -0.015                                  | -0.101**                 |\n+---------------------------------------+-------------------------------+-----------------------------------------+--------------------------+\n|                                       | (0.003)                       | (0.033)                                 | (0.025)                  |\n+---------------------------------------+-------------------------------+-----------------------------------------+--------------------------+\n| Male                                  | -0.042                        | -0.180                                  | 0.601                    |\n+---------------------------------------+-------------------------------+-----------------------------------------+--------------------------+\n|                                       | (0.093)                       | (1.026)                                 | (0.718)                  |\n+---------------------------------------+-------------------------------+-----------------------------------------+--------------------------+\n| White                                 | -0.261*                       | 0.959                                   | 2.549**                  |\n+---------------------------------------+-------------------------------+-----------------------------------------+--------------------------+\n|                                       | (0.106)                       | (1.201)                                 | (0.854)                  |\n+---------------------------------------+-------------------------------+-----------------------------------------+--------------------------+\n| Education                             | -0.023                        | 1.166**                                 | 0.410*                   |\n+---------------------------------------+-------------------------------+-----------------------------------------+--------------------------+\n|                                       | (0.027)                       | (0.291)                                 | (0.207)                  |\n+---------------------------------------+-------------------------------+-----------------------------------------+--------------------------+\n| Income                                | -0.031†                       | 0.310                                   | 0.496**                  |\n+---------------------------------------+-------------------------------+-----------------------------------------+--------------------------+\n|                                       | (0.019)                       | (0.211)                                 | (0.144)                  |\n+---------------------------------------+-------------------------------+-----------------------------------------+--------------------------+\n| (Intercept)                           | 0.104                         | 12.291**                                | 18.209**                 |\n+---------------------------------------+-------------------------------+-----------------------------------------+--------------------------+\n|                                       | (0.221)                       | (2.457)                                 | (1.803)                  |\n+---------------------------------------+-------------------------------+-----------------------------------------+--------------------------+\n| Num.Obs.                              | 3113                          | 1433                                    | 3113                     |\n+---------------------------------------+-------------------------------+-----------------------------------------+--------------------------+\n| Adj. R2                               |                               | 0.022                                   | 0.122                    |\n+---------------------------------------+-------------------------------+-----------------------------------------+--------------------------+\n| McFadden's pseudo R2                  | 0.066                         |                                         |                          |\n+=======================================+===============================+=========================================+==========================+\n| † p < 0.1, * p < 0.05, ** p < 0.01                                                                                                         |\n+=======================================+===============================+=========================================+==========================+\n:::\n:::\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n![Predicted willingness-to-pay for fossil fuels, among respondents with any positive WTP, by cue condition and political identity, controlling for demographics (survey-weighted OLS predictions with 95% CIs; age, male, white, education, and income held at their survey-weighted means)](supplemental-materials_files/figure-docx/fig-wtp-fossil-predicted-supp-demo-1.png){#fig-wtp-fossil-predicted-supp-demo}\n:::\n:::\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n![Predicted willingness-to-pay for renewables by cue condition and political identity, controlling for demographics (survey-weighted OLS predictions with 95% CIs; age, male, white, education, and income held at their survey-weighted means)](supplemental-materials_files/figure-docx/fig-wtp-renewable-predicted-supp-demo-1.png){#fig-wtp-renewable-predicted-supp-demo}\n:::\n:::\n\n\nFor fossil fuels, conservative Republicans remained significantly more likely than the reference group to have any positive WTP (b = 0.74, log-odds scale, *p* < .001), and liberal Democrats less likely (b = -0.38, *p* = 0.043). For renewables, liberal Democrats were willing to pay \\$5.20 more on average (climate condition: an additional \\$3.49, *p* = 0.109), and conservative Republicans \\$6.79 less (*p* < .001) — the same pattern, and nearly the same magnitudes, reported in the main text without this control.\n\n**Summary.** Adding demographic controls does not change which cue x political-identity effects are significant, does not change the sign of any coefficient, and shifts coefficient magnitudes only trivially. The main text's cue and political-identity effects on energy prioritization and WTP are not an artifact of the demographic composition of respondents in each cue/identity group.\n\n\\newpage\n\n\n\n# Robustness Check: Controlling for Demographics and Concern about Energy Cost\n\nEnergy affordability was a salient concern during the period of data collection: respondents' mean concern about the cost of electricity was 7.88 on a 0 to 10 scale. Because this concern could plausibly confound cue and political-identity effects on prioritization and WTP, this section re-estimates every main-text model controlling for demographics (age, male, white, education, and income) plus concern about energy cost. As shown below, the coefficients, their significance, and the substantive conclusions are consistent with the main text.\n\nThe results for the energy source-priority scale are shown in @tbl-priority-ols-supp, parallel to the priority-scale table in the main text.\n\n\n::: {#tbl-priority-ols-supp .cell tbl-cap='Effect of cue condition, political beliefs, and their interaction on the energy source-priority scale, controlling for concern about energy cost (survey-weighted OLS; baseline condition and other/moderate identity as reference)'}\n::: {.cell-output-display}\n\n+---------------------------------------+----------------+\n|                                       | Priority scale |\n+=======================================+================+\n| Trump cue                             | -0.030         |\n+---------------------------------------+----------------+\n|                                       | (0.157)        |\n+---------------------------------------+----------------+\n| Climate cue                           | -0.122         |\n+---------------------------------------+----------------+\n|                                       | (0.152)        |\n+---------------------------------------+----------------+\n| Liberal Democrat                      | 0.647**        |\n+---------------------------------------+----------------+\n|                                       | (0.125)        |\n+---------------------------------------+----------------+\n| Conservative Republican               | -1.221**       |\n+---------------------------------------+----------------+\n|                                       | (0.148)        |\n+---------------------------------------+----------------+\n| Trump cue × Liberal Democrat          | 0.176          |\n+---------------------------------------+----------------+\n|                                       | (0.182)        |\n+---------------------------------------+----------------+\n| Climate cue × Liberal Democrat        | 0.354*         |\n+---------------------------------------+----------------+\n|                                       | (0.174)        |\n+---------------------------------------+----------------+\n| Trump cue × Conservative Republican   | -0.412†        |\n+---------------------------------------+----------------+\n|                                       | (0.232)        |\n+---------------------------------------+----------------+\n| Climate cue × Conservative Republican | 0.062          |\n+---------------------------------------+----------------+\n|                                       | (0.217)        |\n+---------------------------------------+----------------+\n| Concern about energy cost             | 0.041*         |\n+---------------------------------------+----------------+\n|                                       | (0.016)        |\n+---------------------------------------+----------------+\n| Age                                   | -0.011**       |\n+---------------------------------------+----------------+\n|                                       | (0.002)        |\n+---------------------------------------+----------------+\n| Male                                  | 0.239**        |\n+---------------------------------------+----------------+\n|                                       | (0.068)        |\n+---------------------------------------+----------------+\n| White                                 | 0.145†         |\n+---------------------------------------+----------------+\n|                                       | (0.078)        |\n+---------------------------------------+----------------+\n| Education                             | 0.044*         |\n+---------------------------------------+----------------+\n|                                       | (0.019)        |\n+---------------------------------------+----------------+\n| Income                                | 0.020          |\n+---------------------------------------+----------------+\n|                                       | (0.013)        |\n+---------------------------------------+----------------+\n| (Intercept)                           | 5.194**        |\n+---------------------------------------+----------------+\n|                                       | (0.200)        |\n+---------------------------------------+----------------+\n| Num.Obs.                              | 3113           |\n+---------------------------------------+----------------+\n| Adj. R2                               | 0.33           |\n+=======================================+================+\n| † p < 0.1, * p < 0.05, ** p < 0.01                     |\n+=======================================+================+\n:::\n:::\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n![Predicted energy source-priority scale (1-7) by cue condition and political identity, controlling for concern about energy cost (survey-weighted OLS predictions with 95% CIs; concern about energy cost, age, male, white, education, and income held at their survey-weighted means)](supplemental-materials_files/figure-docx/fig-priority-predicted-supp-1.png){#fig-priority-predicted-supp}\n:::\n:::\n\n\nAs in the main text, conservative Republicans were more likely to prioritize fossil fuels (b = -1.22, *p* < .001) and liberal Democrats more likely to prioritize renewables (b = 0.65, *p* < .001). The interaction terms significant at *p* $\\leq$ .10 in this specification are:\n\n- Conservative Republican: b = -1.22, *p* = 0.000\n- Liberal Democrat: b = 0.65, *p* = 0.000\n- Climate cue × Liberal Democrat: b = 0.35, *p* = 0.042\n- Trump cue × Conservative Republican: b = -0.41, *p* = 0.076\n\nThe results for the WTP models are shown in @tbl-wtp-models-supp, parallel to the WTP models table in the main text.\n\n\n::: {#tbl-wtp-models-supp .cell tbl-cap='Effect of cue condition, political beliefs, and their interaction on willingness-to-pay for fossil fuels (any positive WTP, and amount among those with any positive WTP) and for renewables, controlling for concern about energy cost (survey-weighted logit/OLS; baseline condition and other/moderate identity as reference)'}\n::: {.cell-output-display}\n\n+---------------------------------------+-------------------------------+-----------------------------------------+--------------------------+\n|                                       | Fossil fuels: Any WTP (logit) | Fossil fuels: Amount, if WTP > $0 (OLS) | Renewables: Amount (OLS) |\n+=======================================+===============================+=========================================+==========================+\n| Trump cue                             | -0.252                        | -3.410                                  | -1.494                   |\n+---------------------------------------+-------------------------------+-----------------------------------------+--------------------------+\n|                                       | (0.208)                       | (2.257)                                 | (1.862)                  |\n+---------------------------------------+-------------------------------+-----------------------------------------+--------------------------+\n| Climate cue                           | 0.074                         | -1.148                                  | -1.507                   |\n+---------------------------------------+-------------------------------+-----------------------------------------+--------------------------+\n|                                       | (0.206)                       | (2.230)                                 | (1.751)                  |\n+---------------------------------------+-------------------------------+-----------------------------------------+--------------------------+\n| Liberal Democrat                      | -0.362†                       | -0.010                                  | 5.299**                  |\n+---------------------------------------+-------------------------------+-----------------------------------------+--------------------------+\n|                                       | (0.185)                       | (2.097)                                 | (1.575)                  |\n+---------------------------------------+-------------------------------+-----------------------------------------+--------------------------+\n| Conservative Republican               | 0.742**                       | -2.897                                  | -6.818**                 |\n+---------------------------------------+-------------------------------+-----------------------------------------+--------------------------+\n|                                       | (0.208)                       | (2.076)                                 | (1.641)                  |\n+---------------------------------------+-------------------------------+-----------------------------------------+--------------------------+\n| Trump cue × Liberal Democrat          | -0.029                        | 3.186                                   | 2.015                    |\n+---------------------------------------+-------------------------------+-----------------------------------------+--------------------------+\n|                                       | (0.259)                       | (2.870)                                 | (2.248)                  |\n+---------------------------------------+-------------------------------+-----------------------------------------+--------------------------+\n| Climate cue × Liberal Democrat        | -0.273                        | 1.426                                   | 3.660†                   |\n+---------------------------------------+-------------------------------+-----------------------------------------+--------------------------+\n|                                       | (0.260)                       | (2.970)                                 | (2.170)                  |\n+---------------------------------------+-------------------------------+-----------------------------------------+--------------------------+\n| Trump cue × Conservative Republican   | 0.424                         | 3.506                                   | 0.373                    |\n+---------------------------------------+-------------------------------+-----------------------------------------+--------------------------+\n|                                       | (0.301)                       | (2.918)                                 | (2.345)                  |\n+---------------------------------------+-------------------------------+-----------------------------------------+--------------------------+\n| Climate cue × Conservative Republican | -0.024                        | 3.338                                   | 3.053                    |\n+---------------------------------------+-------------------------------+-----------------------------------------+--------------------------+\n|                                       | (0.294)                       | (2.876)                                 | (2.302)                  |\n+---------------------------------------+-------------------------------+-----------------------------------------+--------------------------+\n| Concern about energy cost             | -0.067**                      | -0.641**                                | -0.381*                  |\n+---------------------------------------+-------------------------------+-----------------------------------------+--------------------------+\n|                                       | (0.022)                       | (0.224)                                 | (0.166)                  |\n+---------------------------------------+-------------------------------+-----------------------------------------+--------------------------+\n| Age                                   | 0.008*                        | -0.002                                  | -0.093**                 |\n+---------------------------------------+-------------------------------+-----------------------------------------+--------------------------+\n|                                       | (0.003)                       | (0.034)                                 | (0.025)                  |\n+---------------------------------------+-------------------------------+-----------------------------------------+--------------------------+\n| Male                                  | -0.062                        | -0.430                                  | 0.485                    |\n+---------------------------------------+-------------------------------+-----------------------------------------+--------------------------+\n|                                       | (0.093)                       | (1.035)                                 | (0.718)                  |\n+---------------------------------------+-------------------------------+-----------------------------------------+--------------------------+\n| White                                 | -0.262*                       | 0.969                                   | 2.552**                  |\n+---------------------------------------+-------------------------------+-----------------------------------------+--------------------------+\n|                                       | (0.106)                       | (1.199)                                 | (0.854)                  |\n+---------------------------------------+-------------------------------+-----------------------------------------+--------------------------+\n| Education                             | -0.027                        | 1.148**                                 | 0.389†                   |\n+---------------------------------------+-------------------------------+-----------------------------------------+--------------------------+\n|                                       | (0.027)                       | (0.292)                                 | (0.208)                  |\n+---------------------------------------+-------------------------------+-----------------------------------------+--------------------------+\n| Income                                | -0.035†                       | 0.271                                   | 0.473**                  |\n+---------------------------------------+-------------------------------+-----------------------------------------+--------------------------+\n|                                       | (0.019)                       | (0.210)                                 | (0.145)                  |\n+---------------------------------------+-------------------------------+-----------------------------------------+--------------------------+\n| (Intercept)                           | 0.593*                        | 16.788**                                | 20.989**                 |\n+---------------------------------------+-------------------------------+-----------------------------------------+--------------------------+\n|                                       | (0.271)                       | (2.958)                                 | (2.146)                  |\n+---------------------------------------+-------------------------------+-----------------------------------------+--------------------------+\n| Num.Obs.                              | 3113                          | 1433                                    | 3113                     |\n+---------------------------------------+-------------------------------+-----------------------------------------+--------------------------+\n| Adj. R2                               |                               | 0.029                                   | 0.123                    |\n+---------------------------------------+-------------------------------+-----------------------------------------+--------------------------+\n| McFadden's pseudo R2                  | 0.069                         |                                         |                          |\n+=======================================+===============================+=========================================+==========================+\n| † p < 0.1, * p < 0.05, ** p < 0.01                                                                                                         |\n+=======================================+===============================+=========================================+==========================+\n:::\n:::\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n![Predicted willingness-to-pay for fossil fuels, among respondents with any positive WTP, by cue condition and political identity, controlling for concern about energy cost (survey-weighted OLS predictions with 95% CIs; concern about energy cost, age, male, white, education, and income held at their survey-weighted means)](supplemental-materials_files/figure-docx/fig-wtp-fossil-predicted-supp-1.png){#fig-wtp-fossil-predicted-supp}\n:::\n:::\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n![Predicted willingness-to-pay for renewables by cue condition and political identity, controlling for concern about energy cost (survey-weighted OLS predictions with 95% CIs; concern about energy cost, age, male, white, education, and income held at their survey-weighted means)](supplemental-materials_files/figure-docx/fig-wtp-renewable-predicted-supp-1.png){#fig-wtp-renewable-predicted-supp}\n:::\n:::\n\n\nFor fossil fuels, conservative Republicans remained significantly more likely than the reference group to have any positive WTP (b = 0.74, log-odds scale, *p* < .001), and liberal Democrats less likely (b = -0.36, *p* = 0.050). For renewables, liberal Democrats were willing to pay \\$5.30 more on average (climate condition: an additional \\$3.66, *p* = 0.092), and conservative Republicans \\$6.82 less (*p* < .001) — the same pattern, and nearly the same magnitudes, reported in the main text without this control.\n\n**Summary.** Adding concern about energy cost as a control does not change which cue x political-identity effects are significant, does not change the sign of any coefficient, and shifts coefficient magnitudes only trivially. The main text's cue and political-identity effects on energy prioritization and WTP are not an artifact of differential cost sensitivity across respondents.\n\n\\newpage\n\n\n\n# Robustness Check: Concern about Energy Cost Interacted with Cues and Political Identity\n\nThe prior section controls for concern about energy cost, entering it additively. This section asks whether the cost-concern effect itself varies by cue condition or political identity: every main-text model is re-estimated with concern about energy cost interacted with both cue conditions and with political identity, in addition to the demographic controls (age, male, white, education, income).\n\nThe results for the energy source-priority scale are shown in @tbl-priority-ols-cost-int.\n\n\n::: {#tbl-priority-ols-cost-int .cell tbl-cap='Effect of cue condition, political beliefs, and concern about energy cost, including cue x cost and identity x cost interactions, on the energy source-priority scale (survey-weighted OLS; baseline condition and other/moderate identity as reference)'}\n::: {.cell-output-display}\n\n+-----------------------------------------------------+----------------+\n|                                                     | Priority scale |\n+=====================================================+================+\n| Trump cue                                           | 0.241          |\n+-----------------------------------------------------+----------------+\n|                                                     | (0.333)        |\n+-----------------------------------------------------+----------------+\n| Climate cue                                         | 0.199          |\n+-----------------------------------------------------+----------------+\n|                                                     | (0.317)        |\n+-----------------------------------------------------+----------------+\n| Liberal Democrat                                    | 1.021**        |\n+-----------------------------------------------------+----------------+\n|                                                     | (0.285)        |\n+-----------------------------------------------------+----------------+\n| Conservative Republican                             | -0.199         |\n+-----------------------------------------------------+----------------+\n|                                                     | (0.352)        |\n+-----------------------------------------------------+----------------+\n| Trump cue × Liberal Democrat                        | 0.188          |\n+-----------------------------------------------------+----------------+\n|                                                     | (0.180)        |\n+-----------------------------------------------------+----------------+\n| Climate cue × Liberal Democrat                      | 0.351*         |\n+-----------------------------------------------------+----------------+\n|                                                     | (0.174)        |\n+-----------------------------------------------------+----------------+\n| Trump cue × Conservative Republican                 | -0.398†        |\n+-----------------------------------------------------+----------------+\n|                                                     | (0.229)        |\n+-----------------------------------------------------+----------------+\n| Climate cue × Conservative Republican               | 0.061          |\n+-----------------------------------------------------+----------------+\n|                                                     | (0.215)        |\n+-----------------------------------------------------+----------------+\n| Concern about energy cost                           | 0.134**        |\n+-----------------------------------------------------+----------------+\n|                                                     | (0.034)        |\n+-----------------------------------------------------+----------------+\n| Trump cue × Concern about energy cost               | -0.036         |\n+-----------------------------------------------------+----------------+\n|                                                     | (0.039)        |\n+-----------------------------------------------------+----------------+\n| Climate cue × Concern about energy cost             | -0.040         |\n+-----------------------------------------------------+----------------+\n|                                                     | (0.037)        |\n+-----------------------------------------------------+----------------+\n| Concern about energy cost × Liberal Democrat        | -0.050         |\n+-----------------------------------------------------+----------------+\n|                                                     | (0.033)        |\n+-----------------------------------------------------+----------------+\n| Concern about energy cost × Conservative Republican | -0.133**       |\n+-----------------------------------------------------+----------------+\n|                                                     | (0.042)        |\n+-----------------------------------------------------+----------------+\n| Age                                                 | -0.011**       |\n+-----------------------------------------------------+----------------+\n|                                                     | (0.002)        |\n+-----------------------------------------------------+----------------+\n| Male                                                | 0.241**        |\n+-----------------------------------------------------+----------------+\n|                                                     | (0.068)        |\n+-----------------------------------------------------+----------------+\n| White                                               | 0.151†         |\n+-----------------------------------------------------+----------------+\n|                                                     | (0.078)        |\n+-----------------------------------------------------+----------------+\n| Education                                           | 0.044*         |\n+-----------------------------------------------------+----------------+\n|                                                     | (0.019)        |\n+-----------------------------------------------------+----------------+\n| Income                                              | 0.020          |\n+-----------------------------------------------------+----------------+\n|                                                     | (0.013)        |\n+-----------------------------------------------------+----------------+\n| (Intercept)                                         | 4.464**        |\n+-----------------------------------------------------+----------------+\n|                                                     | (0.298)        |\n+-----------------------------------------------------+----------------+\n| Num.Obs.                                            | 3113           |\n+-----------------------------------------------------+----------------+\n| Adj. R2                                             | 0.335          |\n+=====================================================+================+\n| † p < 0.1, * p < 0.05, ** p < 0.01                                   |\n+=====================================================+================+\n:::\n:::\n\n\nConcern about energy cost had a significant positive effect on prioritizing fossil fuels over renewables (b = 0.13, *p* < .001). This effect was significantly weaker for conservative Republicans (b = -0.13, *p* = 0.001), consistent with cost concern already being incorporated into conservative Republicans' fossil-fuel-favoring baseline. The concern-about-cost terms significant at *p* $\\leq$ .10 in this specification are:\n\n- Concern about energy cost: b = 0.13, *p* = 0.000\n- Concern about energy cost × Conservative Republican: b = -0.13, *p* = 0.001\n\nThe results for the WTP models are shown in @tbl-wtp-models-cost-int.\n\n\n::: {#tbl-wtp-models-cost-int .cell tbl-cap='Effect of cue condition, political beliefs, and concern about energy cost, including cue x cost and identity x cost interactions, on willingness-to-pay for fossil fuels (any positive WTP, and amount among those with any positive WTP) and for renewables (survey-weighted logit/OLS; baseline condition and other/moderate identity as reference)'}\n::: {.cell-output-display}\n\n+-----------------------------------------------------+-------------------------------+-----------------------------------------+--------------------------+\n|                                                     | Fossil fuels: Any WTP (logit) | Fossil fuels: Amount, if WTP > $0 (OLS) | Renewables: Amount (OLS) |\n+=====================================================+===============================+=========================================+==========================+\n| Trump cue                                           | -0.128                        | -11.261*                                | -2.327                   |\n+-----------------------------------------------------+-------------------------------+-----------------------------------------+--------------------------+\n|                                                     | (0.447)                       | (4.676)                                 | (3.364)                  |\n+-----------------------------------------------------+-------------------------------+-----------------------------------------+--------------------------+\n| Climate cue                                         | 0.054                         | -5.880                                  | -2.915                   |\n+-----------------------------------------------------+-------------------------------+-----------------------------------------+--------------------------+\n|                                                     | (0.461)                       | (4.428)                                 | (3.459)                  |\n+-----------------------------------------------------+-------------------------------+-----------------------------------------+--------------------------+\n| Liberal Democrat                                    | -1.328**                      | -1.888                                  | 5.112                    |\n+-----------------------------------------------------+-------------------------------+-----------------------------------------+--------------------------+\n|                                                     | (0.437)                       | (4.558)                                 | (3.385)                  |\n+-----------------------------------------------------+-------------------------------+-----------------------------------------+--------------------------+\n| Conservative Republican                             | -0.183                        | -3.202                                  | -5.418                   |\n+-----------------------------------------------------+-------------------------------+-----------------------------------------+--------------------------+\n|                                                     | (0.485)                       | (4.449)                                 | (3.503)                  |\n+-----------------------------------------------------+-------------------------------+-----------------------------------------+--------------------------+\n| Trump cue × Liberal Democrat                        | -0.032                        | 2.468                                   | 1.990                    |\n+-----------------------------------------------------+-------------------------------+-----------------------------------------+--------------------------+\n|                                                     | (0.259)                       | (2.850)                                 | (2.254)                  |\n+-----------------------------------------------------+-------------------------------+-----------------------------------------+--------------------------+\n| Climate cue × Liberal Democrat                      | -0.273                        | 1.008                                   | 3.533                    |\n+-----------------------------------------------------+-------------------------------+-----------------------------------------+--------------------------+\n|                                                     | (0.260)                       | (2.992)                                 | (2.174)                  |\n+-----------------------------------------------------+-------------------------------+-----------------------------------------+--------------------------+\n| Trump cue × Conservative Republican                 | 0.418                         | 3.040                                   | 0.388                    |\n+-----------------------------------------------------+-------------------------------+-----------------------------------------+--------------------------+\n|                                                     | (0.301)                       | (2.928)                                 | (2.347)                  |\n+-----------------------------------------------------+-------------------------------+-----------------------------------------+--------------------------+\n| Climate cue × Conservative Republican               | -0.015                        | 3.099                                   | 3.018                    |\n+-----------------------------------------------------+-------------------------------+-----------------------------------------+--------------------------+\n|                                                     | (0.293)                       | (2.901)                                 | (2.300)                  |\n+-----------------------------------------------------+-------------------------------+-----------------------------------------+--------------------------+\n| Concern about energy cost                           | -0.149**                      | -1.294**                                | -0.412                   |\n+-----------------------------------------------------+-------------------------------+-----------------------------------------+--------------------------+\n|                                                     | (0.050)                       | (0.491)                                 | (0.386)                  |\n+-----------------------------------------------------+-------------------------------+-----------------------------------------+--------------------------+\n| Trump cue × Concern about energy cost               | -0.015                        | 1.074*                                  | 0.107                    |\n+-----------------------------------------------------+-------------------------------+-----------------------------------------+--------------------------+\n|                                                     | (0.051)                       | (0.534)                                 | (0.385)                  |\n+-----------------------------------------------------+-------------------------------+-----------------------------------------+--------------------------+\n| Climate cue × Concern about energy cost             | 0.001                         | 0.642                                   | 0.187                    |\n+-----------------------------------------------------+-------------------------------+-----------------------------------------+--------------------------+\n|                                                     | (0.053)                       | (0.512)                                 | (0.399)                  |\n+-----------------------------------------------------+-------------------------------+-----------------------------------------+--------------------------+\n| Concern about energy cost × Liberal Democrat        | 0.124*                        | 0.282                                   | 0.024                    |\n+-----------------------------------------------------+-------------------------------+-----------------------------------------+--------------------------+\n|                                                     | (0.051)                       | (0.514)                                 | (0.408)                  |\n+-----------------------------------------------------+-------------------------------+-----------------------------------------+--------------------------+\n| Concern about energy cost × Conservative Republican | 0.119*                        | 0.073                                   | -0.181                   |\n+-----------------------------------------------------+-------------------------------+-----------------------------------------+--------------------------+\n|                                                     | (0.057)                       | (0.497)                                 | (0.416)                  |\n+-----------------------------------------------------+-------------------------------+-----------------------------------------+--------------------------+\n| Age                                                 | 0.008*                        | -0.002                                  | -0.092**                 |\n+-----------------------------------------------------+-------------------------------+-----------------------------------------+--------------------------+\n|                                                     | (0.003)                       | (0.034)                                 | (0.025)                  |\n+-----------------------------------------------------+-------------------------------+-----------------------------------------+--------------------------+\n| Male                                                | -0.065                        | -0.373                                  | 0.482                    |\n+-----------------------------------------------------+-------------------------------+-----------------------------------------+--------------------------+\n|                                                     | (0.093)                       | (1.038)                                 | (0.716)                  |\n+-----------------------------------------------------+-------------------------------+-----------------------------------------+--------------------------+\n| White                                               | -0.260*                       | 0.802                                   | 2.541**                  |\n+-----------------------------------------------------+-------------------------------+-----------------------------------------+--------------------------+\n|                                                     | (0.105)                       | (1.208)                                 | (0.853)                  |\n+-----------------------------------------------------+-------------------------------+-----------------------------------------+--------------------------+\n| Education                                           | -0.029                        | 1.150**                                 | 0.387†                   |\n+-----------------------------------------------------+-------------------------------+-----------------------------------------+--------------------------+\n|                                                     | (0.027)                       | (0.291)                                 | (0.208)                  |\n+-----------------------------------------------------+-------------------------------+-----------------------------------------+--------------------------+\n| Income                                              | -0.033†                       | 0.283                                   | 0.478**                  |\n+-----------------------------------------------------+-------------------------------+-----------------------------------------+--------------------------+\n|                                                     | (0.019)                       | (0.210)                                 | (0.145)                  |\n+-----------------------------------------------------+-------------------------------+-----------------------------------------+--------------------------+\n| (Intercept)                                         | 1.235**                       | 21.574**                                | 21.209**                 |\n+-----------------------------------------------------+-------------------------------+-----------------------------------------+--------------------------+\n|                                                     | (0.445)                       | (4.462)                                 | (3.272)                  |\n+-----------------------------------------------------+-------------------------------+-----------------------------------------+--------------------------+\n| Num.Obs.                                            | 3113                          | 1433                                    | 3113                     |\n+-----------------------------------------------------+-------------------------------+-----------------------------------------+--------------------------+\n| Adj. R2                                             |                               | 0.03                                    | 0.123                    |\n+-----------------------------------------------------+-------------------------------+-----------------------------------------+--------------------------+\n| McFadden's pseudo R2                                | 0.071                         |                                         |                          |\n+=====================================================+===============================+=========================================+==========================+\n| † p < 0.1, * p < 0.05, ** p < 0.01                                                                                                                       |\n+=====================================================+===============================+=========================================+==========================+\n:::\n:::\n\n\nFor fossil fuels, concern about energy cost lowered the odds of any positive WTP (b = -0.15, log-odds scale, *p* = 0.003), but this penalty was significantly smaller for both liberal Democrats (b = 0.12, *p* = 0.016) and conservative Republicans (b = 0.12, *p* = 0.038) relative to the reference group. Among those with any positive fossil-fuel WTP, concern about energy cost lowered the amount they were willing to pay (b = -1.29, *p* = 0.008), and this penalty was significantly offset under the Trump cue (b = 1.07, *p* = 0.045). For renewables, none of the concern-about-cost terms reached significance. The concern-about-cost terms significant at *p* $\\leq$ .10 in each model are:\n\n**Fossil fuels, any positive WTP (logit):**\n\n- Concern about energy cost: b = -0.15, *p* = 0.003\n- Concern about energy cost × Liberal Democrat: b = 0.12, *p* = 0.016\n- Concern about energy cost × Conservative Republican: b = 0.12, *p* = 0.038\n\n**Fossil fuels, amount if WTP > \\$0 (OLS):**\n\n- Concern about energy cost: b = -1.29, *p* = 0.008\n- Trump cue × Concern about energy cost: b = 1.07, *p* = 0.045\n\n**Renewables, amount (OLS):**\n\n- None of the concern-about-cost terms were significant at *p* $\\leq$ .10.\n\n**Summary.** Concern about energy cost is not simply a nuisance control: it has a significant, partisanship-moderated relationship with fossil-fuel prioritization and WTP (weaker for both liberal Democrats and conservative Republicans than for the reference group), and its dampening effect on fossil-fuel WTP amount is significantly offset under the Trump cue. It shows no such moderated relationship with renewable-energy WTP. None of this changes the sign or significance of the main-text cue x political-identity effects (@tbl-priority-ols-supp and @tbl-wtp-models-supp), which are retained in this specification exactly as reported in the prior section.\n\n\\newpage\n\n\n\n# Covariate Balance across Conditions\n\n@tbl-balance shows the unweighted mean of each demographic variable, concern about the cost of electricity, and the two political belief measures in each condition, along with the *p*-value from a one-way F-test of each variable on condition. The conditions differ somewhat in age and in the share of white respondents, which is why the main-text models are also estimated with demographic controls. Party identification and ideology were measured after the outcome questions, so the political belief rows also test whether the cues changed how respondents identified. The distribution of political beliefs did not differ across conditions ($\\chi^2$ = 5.20, *df* = 4, *p* = 0.268).\n\n\n::: {#tbl-balance .cell tbl-cap='Unweighted means by condition and p-values from one-way F-tests of each variable on condition (political belief measures were asked after the outcome questions)'}\n::: {.cell-output-display}\n\n\n|Variable                                 | Baseline| Trump cue| Climate cue|p     |\n|:----------------------------------------|--------:|---------:|-----------:|:-----|\n|Age                                      |    42.63|     43.76|       44.51|0.019 |\n|Male                                     |     0.49|      0.48|        0.49|0.915 |\n|White                                    |     0.69|      0.70|        0.63|0.002 |\n|College degree                           |     0.56|      0.56|        0.55|0.772 |\n|Income (1-11)                            |     4.71|      4.55|        4.61|0.415 |\n|Concern about electricity cost (0-10)    |     7.73|      7.81|        7.87|0.326 |\n|Liberal Democrat (post-treatment)        |     0.46|      0.50|        0.48|0.172 |\n|Conservative Republican (post-treatment) |     0.25|      0.22|        0.26|0.195 |\n\n\n:::\n:::\n\n\n\\newpage\n\n# Average Effects of the Cues\n\nIn the main-text models, the cues are interacted with political beliefs, so the coefficients for the Trump and climate cues are the effects of the cues among those with other political beliefs only. @tbl-cue-only reports models with the cues alone, which estimate the average effect of each cue across the full sample. Neither cue had a significant average effect on energy source priority or on either WTP outcome.\n\n\n::: {#tbl-cue-only .cell tbl-cap='Average effect of each cue on the energy source-priority scale and willingness-to-pay, without political belief interactions (survey-weighted OLS/logit; baseline condition as reference)'}\n::: {.cell-output-display}\n\n+----------------------+----------------------+-------------------------------+-----------------------------------------+--------------------------+\n|                      | Priority scale (OLS) | Fossil fuels: Any WTP (logit) | Fossil fuels: Amount, if WTP > $0 (OLS) | Renewables: Amount (OLS) |\n+======================+======================+===============================+=========================================+==========================+\n| Trump cue            | -0.028               | -0.162                        | -0.740                                  | -0.097                   |\n+----------------------+----------------------+-------------------------------+-----------------------------------------+--------------------------+\n|                      | (0.103)              | (0.108)                       | (1.205)                                 | (0.925)                  |\n+----------------------+----------------------+-------------------------------+-----------------------------------------+--------------------------+\n| Climate cue          | 0.028                | -0.023                        | 0.745                                   | 0.857                    |\n+----------------------+----------------------+-------------------------------+-----------------------------------------+--------------------------+\n|                      | (0.098)              | (0.109)                       | (1.215)                                 | (0.938)                  |\n+----------------------+----------------------+-------------------------------+-----------------------------------------+--------------------------+\n| (Intercept)          | 5.174**              | 0.180*                        | 15.691**                                | 17.945**                 |\n+----------------------+----------------------+-------------------------------+-----------------------------------------+--------------------------+\n|                      | (0.064)              | (0.076)                       | (0.807)                                 | (0.648)                  |\n+----------------------+----------------------+-------------------------------+-----------------------------------------+--------------------------+\n| Num.Obs.             | 3113                 | 3113                          | 1433                                    | 3113                     |\n+----------------------+----------------------+-------------------------------+-----------------------------------------+--------------------------+\n| Adj. R2              | 0                    |                               | 0                                       | 0                        |\n+----------------------+----------------------+-------------------------------+-----------------------------------------+--------------------------+\n| McFadden's pseudo R2 |                      | 0.001                         |                                         |                          |\n+======================+======================+===============================+=========================================+==========================+\n| † p < 0.1, * p < 0.05, ** p < 0.01                                                                                                               |\n+======================+======================+===============================+=========================================+==========================+\n:::\n:::\n\n\n\\newpage\n\n# Multiple Comparisons and Minimum Detectable Effects\n\n@tbl-interaction-tests lists the 16 cue x political belief interaction terms from the four main-text models, with the unadjusted *p*-value, the *p*-value after a Holm adjustment across all 16 tests, and the minimum detectable effect (MDE). The MDE is the smallest interaction effect the design could detect with 80 percent power at a two-sided $\\alpha$ = .05, calculated as (1.96 + 0.84) times the standard error. No interaction is significant after the Holm adjustment. The MDEs for the WTP models are large relative to the estimated interactions, so small effects of the cues on WTP cannot be ruled out.\n\n\n::: {#tbl-interaction-tests .cell tbl-cap='Cue x political belief interaction terms from the main-text models, with Holm-adjusted p-values and minimum detectable effects (MDE; 80% power, two-sided alpha = .05). Logit estimates and MDEs are on the log-odds scale; OLS estimates and MDEs are in scale points or dollars.'}\n::: {.cell-output-display}\n\n\n|Model                                   |Term                                  |b     |SE   |p     |Holm p |MDE  |\n|:---------------------------------------|:-------------------------------------|:-----|:----|:-----|:------|:----|\n|Priority scale (OLS)                    |Trump cue × Liberal Democrat          |0.14  |0.18 |0.456 |1.000  |0.52 |\n|Priority scale (OLS)                    |Trump cue × Conservative Republican   |-0.44 |0.24 |0.062 |0.937  |0.66 |\n|Priority scale (OLS)                    |Climate cue × Liberal Democrat        |0.34  |0.17 |0.051 |0.809  |0.49 |\n|Priority scale (OLS)                    |Climate cue × Conservative Republican |0.08  |0.22 |0.720 |1.000  |0.62 |\n|Fossil fuels: Any WTP (logit)           |Trump cue × Liberal Democrat          |0.01  |0.26 |0.979 |1.000  |0.72 |\n|Fossil fuels: Any WTP (logit)           |Trump cue × Conservative Republican   |0.42  |0.30 |0.158 |1.000  |0.84 |\n|Fossil fuels: Any WTP (logit)           |Climate cue × Liberal Democrat        |-0.27 |0.26 |0.297 |1.000  |0.73 |\n|Fossil fuels: Any WTP (logit)           |Climate cue × Conservative Republican |-0.04 |0.29 |0.887 |1.000  |0.82 |\n|Fossil fuels: Amount, if WTP > $0 (OLS) |Trump cue × Liberal Democrat          |3.12  |2.87 |0.277 |1.000  |8.04 |\n|Fossil fuels: Amount, if WTP > $0 (OLS) |Trump cue × Conservative Republican   |3.92  |2.96 |0.186 |1.000  |8.30 |\n|Fossil fuels: Amount, if WTP > $0 (OLS) |Climate cue × Liberal Democrat        |1.51  |3.03 |0.618 |1.000  |8.48 |\n|Fossil fuels: Amount, if WTP > $0 (OLS) |Climate cue × Conservative Republican |3.67  |2.92 |0.209 |1.000  |8.17 |\n|Renewables: Amount (OLS)                |Trump cue × Liberal Democrat          |1.66  |2.23 |0.459 |1.000  |6.26 |\n|Renewables: Amount (OLS)                |Trump cue × Conservative Republican   |0.32  |2.34 |0.891 |1.000  |6.55 |\n|Renewables: Amount (OLS)                |Climate cue × Liberal Democrat        |3.14  |2.17 |0.148 |1.000  |6.07 |\n|Renewables: Amount (OLS)                |Climate cue × Conservative Republican |2.94  |2.31 |0.204 |1.000  |6.48 |\n\n\n:::\n:::\n\n\n\\newpage\n\n# Censored-Normal (Tobit) Models of Willingness-to-Pay\n\nThe Gabor-Granger WTP measure is bounded at \\$0, for respondents who rejected the \\$1 amount, and at \\$46, for respondents who accepted the highest amount. @tbl-tobit re-estimates the WTP models for both sources with a censored-normal (Tobit) model that treats \\$0 as censored from below and \\$46 as censored from above. Because the follow-up amounts were drawn at random and not recorded, the next amount a respondent rejected is unknown, so values between \\$1 and \\$41 are treated as observed. The same model is used for both sources.\n\n\n::: {#tbl-tobit .cell tbl-cap='Effect of cue condition, political beliefs, and their interaction on willingness-to-pay for fossil fuels and renewables (survey-weighted censored-normal regression, censored at $0 and $46; baseline condition and other/moderate identity as reference)'}\n::: {.cell-output-display}\n\n+---------------------------------------+----------------------+--------------------+\n|                                       | Fossil fuels (Tobit) | Renewables (Tobit) |\n+=======================================+======================+====================+\n| Trump cue                             | -5.659*              | -2.707             |\n+---------------------------------------+----------------------+--------------------+\n|                                       | (2.853)              | (2.595)            |\n+---------------------------------------+----------------------+--------------------+\n| Climate cue                           | -0.271               | -2.458             |\n+---------------------------------------+----------------------+--------------------+\n|                                       | (2.850)              | (2.400)            |\n+---------------------------------------+----------------------+--------------------+\n| Liberal Democrat                      | -5.305*              | 7.863**            |\n+---------------------------------------+----------------------+--------------------+\n|                                       | (2.663)              | (2.175)            |\n+---------------------------------------+----------------------+--------------------+\n| Conservative Republican               | 4.223                | -10.275**          |\n+---------------------------------------+----------------------+--------------------+\n|                                       | (2.621)              | (2.313)            |\n+---------------------------------------+----------------------+--------------------+\n| Trump cue × Liberal Democrat          | 1.807                | 3.124              |\n+---------------------------------------+----------------------+--------------------+\n|                                       | (3.607)              | (3.169)            |\n+---------------------------------------+----------------------+--------------------+\n| Climate cue × Liberal Democrat        | -2.029               | 4.507              |\n+---------------------------------------+----------------------+--------------------+\n|                                       | (3.693)              | (2.984)            |\n+---------------------------------------+----------------------+--------------------+\n| Trump cue × Conservative Republican   | 7.778*               | 1.279              |\n+---------------------------------------+----------------------+--------------------+\n|                                       | (3.757)              | (3.410)            |\n+---------------------------------------+----------------------+--------------------+\n| Climate cue × Conservative Republican | 3.021                | 4.315              |\n+---------------------------------------+----------------------+--------------------+\n|                                       | (3.712)              | (3.333)            |\n+---------------------------------------+----------------------+--------------------+\n| (Intercept)                           | 0.067                | 19.473**           |\n+---------------------------------------+----------------------+--------------------+\n|                                       | (2.115)              | (1.758)            |\n+---------------------------------------+----------------------+--------------------+\n| Num.Obs.                              | 3113                 | 3113               |\n+=======================================+======================+====================+\n| † p < 0.1, * p < 0.05, ** p < 0.01                                                |\n+=======================================+======================+====================+\n:::\n:::\n\n\nFor renewables, the results match the main text, as political beliefs predict WTP and none of the cue x political belief interactions is significant. For fossil fuels, the Trump cue x conservative Republican interaction is significant (b = 7.78, *p* = 0.038). However, the interaction reflects a lower WTP for fossil fuels in the Trump cue among those with other political beliefs (b = -5.66, *p* = 0.047), whereas conservative Republicans' WTP for fossil fuels in the Trump cue did not differ from the baseline (difference = 2.12, *p* = 0.381). The interaction is not significant after a Holm adjustment (adjusted *p* = 0.65).\n\n\\newpage\n\n# Unweighted Models\n\nThe survey weights roughly double the share of conservative Republicans relative to the unweighted sample, so @tbl-priority-unw and @tbl-wtp-unw re-estimate the main-text models without the weights. The political belief effects are similar. For the priority scale, the climate cue x liberal Democrat interaction is significant without the weights (*p* = 0.014), whereas the Trump cue x conservative Republican interaction is not (*p* = 0.144).\n\n\n::: {#tbl-priority-unw .cell tbl-cap='Effect of cue condition, political beliefs, and their interaction on the energy source-priority scale, unweighted (OLS with robust standard errors; baseline condition and other/moderate identity as reference)'}\n::: {.cell-output-display}\n\n+---------------------------------------+----------------+\n|                                       | Priority scale |\n+=======================================+================+\n| Trump cue                             | -0.061         |\n+---------------------------------------+----------------+\n|                                       | (0.118)        |\n+---------------------------------------+----------------+\n| Climate cue                           | -0.172         |\n+---------------------------------------+----------------+\n|                                       | (0.120)        |\n+---------------------------------------+----------------+\n| Liberal Democrat                      | 0.652**        |\n+---------------------------------------+----------------+\n|                                       | (0.097)        |\n+---------------------------------------+----------------+\n| Conservative Republican               | -1.250**       |\n+---------------------------------------+----------------+\n|                                       | (0.126)        |\n+---------------------------------------+----------------+\n| Trump cue × Liberal Democrat          | 0.232†         |\n+---------------------------------------+----------------+\n|                                       | (0.136)        |\n+---------------------------------------+----------------+\n| Climate cue × Liberal Democrat        | 0.339*         |\n+---------------------------------------+----------------+\n|                                       | (0.138)        |\n+---------------------------------------+----------------+\n| Trump cue × Conservative Republican   | -0.277         |\n+---------------------------------------+----------------+\n|                                       | (0.190)        |\n+---------------------------------------+----------------+\n| Climate cue × Conservative Republican | 0.233          |\n+---------------------------------------+----------------+\n|                                       | (0.187)        |\n+---------------------------------------+----------------+\n| (Intercept)                           | 5.525**        |\n+---------------------------------------+----------------+\n|                                       | (0.082)        |\n+---------------------------------------+----------------+\n| Num.Obs.                              | 3113           |\n+---------------------------------------+----------------+\n| Adj. R2                               | 0.29           |\n+=======================================+================+\n| † p < 0.1, * p < 0.05, ** p < 0.01                     |\n+=======================================+================+\n:::\n:::\n\n\n\n::: {#tbl-wtp-unw .cell tbl-cap='Effect of cue condition, political beliefs, and their interaction on willingness-to-pay for fossil fuels (any positive WTP, and amount among those with any positive WTP) and for renewables, unweighted (logit/OLS with robust standard errors; baseline condition and other/moderate identity as reference)'}\n::: {.cell-output-display}\n\n+---------------------------------------+-------------------------------+-----------------------------------------+--------------------------+\n|                                       | Fossil fuels: Any WTP (logit) | Fossil fuels: Amount, if WTP > $0 (OLS) | Renewables: Amount (OLS) |\n+=======================================+===============================+=========================================+==========================+\n| Trump cue                             | -0.238                        | -2.962                                  | -2.033                   |\n+---------------------------------------+-------------------------------+-----------------------------------------+--------------------------+\n|                                       | (0.165)                       | (1.892)                                 | (1.409)                  |\n+---------------------------------------+-------------------------------+-----------------------------------------+--------------------------+\n| Climate cue                           | -0.028                        | -2.282                                  | -1.689                   |\n+---------------------------------------+-------------------------------+-----------------------------------------+--------------------------+\n|                                       | (0.167)                       | (1.880)                                 | (1.435)                  |\n+---------------------------------------+-------------------------------+-----------------------------------------+--------------------------+\n| Liberal Democrat                      | -0.430**                      | -0.081                                  | 5.287**                  |\n+---------------------------------------+-------------------------------+-----------------------------------------+--------------------------+\n|                                       | (0.148)                       | (1.760)                                 | (1.258)                  |\n+---------------------------------------+-------------------------------+-----------------------------------------+--------------------------+\n| Conservative Republican               | 0.667**                       | -2.773                                  | -6.492**                 |\n+---------------------------------------+-------------------------------+-----------------------------------------+--------------------------+\n|                                       | (0.172)                       | (1.745)                                 | (1.375)                  |\n+---------------------------------------+-------------------------------+-----------------------------------------+--------------------------+\n| Trump cue × Liberal Democrat          | -0.041                        | 2.467                                   | 3.231†                   |\n+---------------------------------------+-------------------------------+-----------------------------------------+--------------------------+\n|                                       | (0.212)                       | (2.505)                                 | (1.771)                  |\n+---------------------------------------+-------------------------------+-----------------------------------------+--------------------------+\n| Climate cue × Liberal Democrat        | -0.141                        | 1.376                                   | 3.047†                   |\n+---------------------------------------+-------------------------------+-----------------------------------------+--------------------------+\n|                                       | (0.214)                       | (2.529)                                 | (1.799)                  |\n+---------------------------------------+-------------------------------+-----------------------------------------+--------------------------+\n| Trump cue × Conservative Republican   | 0.440†                        | 3.575                                   | 1.529                    |\n+---------------------------------------+-------------------------------+-----------------------------------------+--------------------------+\n|                                       | (0.252)                       | (2.557)                                 | (1.978)                  |\n+---------------------------------------+-------------------------------+-----------------------------------------+--------------------------+\n| Climate cue × Conservative Republican | 0.123                         | 3.664                                   | 3.279                    |\n+---------------------------------------+-------------------------------+-----------------------------------------+--------------------------+\n|                                       | (0.249)                       | (2.524)                                 | (2.005)                  |\n+---------------------------------------+-------------------------------+-----------------------------------------+--------------------------+\n| (Intercept)                           | -0.046                        | 18.282**                                | 19.590**                 |\n+---------------------------------------+-------------------------------+-----------------------------------------+--------------------------+\n|                                       | (0.115)                       | (1.323)                                 | (0.994)                  |\n+---------------------------------------+-------------------------------+-----------------------------------------+--------------------------+\n| Num.Obs.                              | 3113                          | 1433                                    | 3113                     |\n+---------------------------------------+-------------------------------+-----------------------------------------+--------------------------+\n| Adj. R2                               |                               | -0.001                                  | 0.085                    |\n+---------------------------------------+-------------------------------+-----------------------------------------+--------------------------+\n| McFadden's pseudo R2                  | 0.052                         |                                         |                          |\n+=======================================+===============================+=========================================+==========================+\n| † p < 0.1, * p < 0.05, ** p < 0.01                                                                                                         |\n+=======================================+===============================+=========================================+==========================+\n:::\n:::\n\n\n\\newpage\n\n# References\n",
    "supporting": [
      "supplemental-materials_files/figure-docx"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": null,
    "postProcess": false
  }
}